### ISSUE TITLE
"Find" functionality crashes the app

### ISSUE THREAD

**Issue by ben-albon** [vkbo/novelWriter#1015]
Whenever I try and use the find function the app becomes unresponsive, and I have to force quit.

I'm running on Windows 10, with version 1.6 of the app.

I recently upgraded from version 1.5.1 - this crash did not happen on 1.5.1.

**Comment by vkbo** [comment]
Hmm, there is not enough information here for me to reproduce this issue. The find function works as expected both on Windows and Linux using the example project for 1.6 at my end. I did make changes to this feature between 1.5.x and 1.6, so it's likely an issue with how the number of results in the document is counted.

Could you clarify:
* Does this happen on any open document?
* If no, can you identify if there is anything special about the document where this happens?
* Which search options are enabled when this happens, and does it matter which options are enabled/disabled?
* Does it make a difference if you search for something that exists in the document or something that doesn't?
* Does it behave the same if you click buttons or use keyboard shortcuts or other ways to initiate the search?
* Are you just search through the text, or are you performing any other actions as well that may be interfering with the feature?

**Comment by vkbo** [comment]
HAH! I had an idea, tested it, and managed to get it to hang. Finally.

One case where it goes into an infinite search loop is with a RegEx search with `.*`. I suspected it could get stuck where the number of results are counted, and it did indeed. I'll make a fix.

I'd still like to know how you triggered the bug?

**Comment by ben-albon** [comment]
* this seems to happen with any open document, and in any project
* the serach prompt does not appear - as soon as I click Search -> Search (or press Ctl+F) the app becomes unresponseive (no dialog is displayed)
* no other actions are being performed

Qt version 5.15.2

I hope this helps!

**Comment by vkbo** [comment]
Actually, it doesn't help at all, because that doesn't happen at my end!

In any case, I still suspect the problem is in the same spot that I just patched up in #1016. It's the only new code from 1.5.x that can go into a loop and hang like that. I just made a release 1.6.1. I expect it will fix your issue too. I certainly hope so.

I found a corner case in the Qt find call, that the novelwriter find call is built on, where it will say it found a result but not actually return one. In that case it would end up searching in the same location in the document infinitely. In the new release, any search that triggers this behaviour will immediately break and exit the loop. I also added a hard cap on 1000 results, so it will now say "1000+" in the find box if it hits that limit.

Please let me know if 1.6.1 fixes the problem, and then we can close this issue.

**Comment by ben-albon** [comment]
Sorry, I didn't see that you made a new release already (that was fast!)

Can confirm that the issue is resolved in 1.6.1 - thank you!

**Comment by vkbo** [comment]
Well, I don't like bugs that crash novelWriter, so I generally try to fix them right away if I have the time :)
