### ISSUE TITLE
Invalid selection on "Folder merge" and "Document split" does not cancel the action

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1032]
**Reproduce:**
- Select a **document** in the project tree.
- Choose the menu entry "**Merge Folder to Document**".
- Error window appears: "Element selected in the project tree must be a folder." <-- expected. Click OK.
- The usual window for folder merging appears. <-- unexpected, because the initial action was invalid and there is nothing to do here.

Analogue selecting a **folder** and wanting to **"Split Document to Folder"**.

Related: When **nothing** is selected in the project tree and either of these functions are called, no error message appears -- but the window for merging folders / splitting documents appears. There is nothing do to in them.

**Comment by vkbo** [comment]
Yes, these dialogs have been around for a long time and are a bit clunky in use, and have some usability issues like the one you're pointing out here. I haven't done anything to improve them because when I implement #1002, they will need to be rewritten anyway. I plan to make a new combined split/merge tool after that is implemented.
