### ISSUE TITLE
Make list of "status level" and "importance level" sortable

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1035]
This is a small one, but nice-to-have. Unless one already knows which "status levels" and "importance levels" one uses and sets them all up before using them, chances are I will come up with a new status or importance mid-way through. I like my things color-coded and in order, so if the new status or importance logically/hierarchically would go in-between already existing items, that's not an option from the UI.

After typing this feature request, I had a look at `nwProject.nwx` and re-arranged the order there. It seemed like my change was handled gracefully (?), so that's a workaround.

Example image of an unsorted list to show what I mean:
![2022-04-08___18_49_05](https://user-images.githubusercontent.com/60368695/162486569-2a50d398-0d3c-44c9-9325-985e2264ff40.png)

**Comment by vkbo** [comment]
This is actually a bug. They are supposed to be drag and drop in the settings.

**Comment by vkbo** [comment]
Seems I removed the old drag and drop feature a while back due to a rewrite, and never implemented it again. Since I've just rewritten how status and importance flags work, it was easy enough to add this feature back.

I've added a move up and move down button to the Project Settings dialog, so you should now be able to do this. It will be included in release 1.7.
