### ISSUE TITLE
Apply "Toggle Comment" to all selected text

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1042]
When I use the "Toggle Comment" function on a bunch of selected text that has multiple paragraphs, only the paragraph that has the curser in it gets converted to a comment. Perhaps the function could toggle the comment state on all selected paragraphs instead. If the selected text has mixed paragraphs (comments and non-comments), the function could first convert all paragraphs to a comment, and on second use to non-comment paragraphs.

(As I'm opening so many issues and feature request, I wanted to also say THANK you so much for your work. I dabbled with a few different writing softwares, and novelWriter is the one that stuck with me. It feels so cozy and clean in what it does, runs lightning fast on my 14 year old netbook, stored inside a Dropbox, I can use it seamlessly between my Windows and Lubuntu machines, the project files are tiny, and thanks to your tip somewhere here I also use GitHub as backup and version control. Thank you <3)

**Comment by HeyMyian** [comment]
I only cared about the comments, but the behavior is actually consistent with all block formatting options - they only apply to the paragraph with the cursor. Inline formatting doesn't - they always apply to the first paragraph in the selection (or a part of the first paragraph if only a part is selected of course). Perhaps you could consider the other formats too, if you decide to rewrite the feature. If it makes a lot of sense wanting to apply "Heading 3" to multiple selected paragraphs, I don't know.

**Comment by vkbo** [comment]
It makes no sense to apply heading formats to multiple paragraphs. That is what the feature was originally designed for though. I then extended it to comments, then to alignments and indentation. The latter three makes sense to change.

**Comment by vkbo** [comment]
PR #1690 adds a new "ignored text format" which is just a `%~` instead of `%` in front of the paragraph. This modified version will always exclude the text from manuscript builds even if you include comments. It's just an optional feature, and something I want for my own writing.

In any case, in the context of adding that, I made the comment, ignore text, and reset format commands apply to multiple paragraphs, Since the first two are toggle commands, they will make the decision based on the first of the selected paragraphs, and apply it to the remaining in the selection.

I hope this is good solution to this request.
