### ISSUE TITLE
A new project in a location with an existing project fails after the wizard

### ISSUE THREAD

**Issue by aaribaud** [vkbo/novelWriter#1058]
### Description
* NovelWriter (justly) rejects the creation of a new project it its location already contains an existing projects.
* However, this rejection comes after completing the wizard.
* This means the user was permitted to fill in project details even though these will be lost due to the rejection.
* Rejection should happen as soon as the document location is known.
### Steps to reproduce the behaviour
* Create a project in a new location
* Close the project
* Create a new project at the same location
* On completion of the wizard, creation is denied because of the location.
### What I expected to happen
* On the second wizard screen, once a location is entered, progress to the next wizard screen should be possible only if location is valid (nonexistent or existent but empty); if progress is not possible, then the reason should be stated below the field for entering the location.
### error dialog shown at end of wizard:
> A project already exists in that location. Please choose another folder.

**Comment by vkbo** [comment]
This should not even happen because the Wizard will append a folder to the path, matching the chosen project name.

* Did you try to create a project with the same name as another project?
* Or, did you manually remove the project name from the bath?

It should be fairly easy to add checks for these two scenarios.
