### ISSUE TITLE
expand collapse all

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1122]
Would it be possible to add an "expand and collapse all" functionality both to the left column of the files and folders tree and also to the Outline view? I often need to have only one small part open, or on the contrary to have overview to all items. Manually clicking dozens of items is difficult. This feature would help. Thank you.

**Comment by vkbo** [comment]
Sure, I can add it to the project tree. However the Novel and Outline views are not actually trees, so that is more difficult. I'm not sure what to do there.

**Comment by vkbo** [comment]
Since I'm already doing large updates to the Project Tree, I'll add your first suggestion right away for the next release.

Also, a correction to my first response: The Outline/Novel view will no longer be trees in the next release, but tables. So they will not be collapsible. In the current release they are. There are numerous issues with that, which is why I'm changing it. However, I will look for some way to preserve the current feature if I can make it work.

**Comment by snden** [comment]
Thanks a lot. I think the expand/collapse function is more important in the left part when browsing through folders and files, although it would also help in the Outline view. I know it looks simpler from the user's point of view than it can be written in software code.
I have one more suggestion, but I will write it in a separate post.

**Comment by vkbo** [comment]
It is relatively simple to add in a tree widget. It already has the code for it. It is used when you load a project to expand all items that you had expanded when you saved the project last time. The items are not expanded by default.

**Comment by vkbo** [comment]
Expand/Collapse All has been added for the Project Tree. It will be available in the 1.7 release.

**Comment by snden** [comment]
I'm playing with version v2.0-beta1 and the expand/collapse function, and I found out that the option to create a new file and a new folder disappeared from the context menu, as well as from the main menu. Isn't it a error? Or is there another way? I can't figure out how to do it.
Also, when I choose the expand/all function using the context menu, it only works on subfolders, not the whole tree. Is this desired behavior? (Interesting and looks like it will be useful.)

**Comment by vkbo** [comment]
Due to the number of options for adding new items, it has it's own menu now. It is accessed by clicking the `+` button at the top of the tree. You can trigger it by the keyboard shortcut `Ctrl+N` as well.

All actions affecting the project as a whole are available from the menu button at the top of the project tree as well. That includes the expand/collapse feature for the whole tree. There are no places to add that as a context menu inside the tree itself.

Anyway, I just released 2.0 RC 1. It should be available from Launchpad in a few minutes. The RC 1 release also adds quick links for easy navigation of the project tree.

**Comment by snden** [comment]
Thanks for the info, I'm going to install 2.0 RC 1 :-)

**Comment by vkbo** [comment]
It's still pending on Launchpad. You can see the status here: https://launchpad.net/~vkbo/+archive/ubuntu/novelwriter-pre/+packages
