### ISSUE TITLE
Metadata with a different format in the exported file

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1134]
Would it be possible to distinguish the metadata from each other so that it has a different style in the exported file? In . odt - style, in .html - .class? Then it would be possible to work with the metadata in another editor (change font size, color, hide...)

for example in html:

\<span class="Locations"\>
\<span class="Characters"\>
\<span class="POV"\>
\<span class="Timeline"\>
\<span class="Objects"\>
\<span class="Focus"\>
\<span class="Synopsis"\>
\<span class="Comment"\>
\<span class="Tag"\>

**Comment by vkbo** [comment]
I've added classes for the meta data to the HTML output.

Example:

```html
<p class='meta meta-pov' style='margin-bottom: 0;'><span class='tags'>Point of View:</span> <a href='#tag_Bod'>Bod</a></p>
<p class='meta meta-plot' style='margin-bottom: 0; margin-top: 0;'><span class='tags'>Plot:</span> <a href='#tag_Main'>Main</a></p>
<p class='meta meta-location' style='margin-top: 0;'><span class='tags'>Locations:</span> <a href='#tag_Europe'>Europe</a></p>
```

It is not practical for the ODT output since I'd have to add specific styles for each kind of meta data. Since you cannot hide text in an ODT file like in HTML, if you need to filter out specific tags, you can do so with the filter added to the Manuscript Settings tool in #1723.
