### ISSUE TITLE
Formatting codes display inconsistently when shift+enter is used

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1150]
When I set _a part of text as 'emphasised'_ using underscores  and do shift + enter in that part of text:
```
_a part of text 
as 'emphasised'_
```
it still appears as italics in the edit window, but not in the preview window. When I edit another file and come back to this one, it doesn't appear as italic now. But just delete the shift + enter and do it again and the formatting will appear again. But still only in the editing window.
Likewise for all `%comments` incl. `synopsis`, `**strong emphasis**`, `~~strikethrough part~~`.
```
**strong 
emphasis**, ~~strikethrough 
part~~.
```

**Comment by vkbo** [comment]
Firstly, GitHub uses markdown, so all the text you just entered is treated as markdown. I cannot see what you are trying to illustrate without having to click "edit" to see what you typed. You can add plain text blocks with triple backticks, which will not be formatted. I've fixed this in your comment.

Anyway. `Shift + Enter` is not a line break in the editor widget. The Qt framework inserts a [line separator](https://unicodeplus.com/U+2028) instead, which is different from a proper `Enter` which produces a [paragraph separator](https://unicodeplus.com/U+2029). The line separator does not create a new text block (the unit Qt uses for a paragraph) but the paragraph separator does. Hence, the syntax highlighter treats the whole thing as a single unit when you use `Shift+Enter`.

However, these special characters are all replaced by regular line breaks `\n` when the document is saved to file, so the distinction no longer exists. Therefore they are later treated as separate blocks.

Originally, single line breaks were stripped out of the raw text and replaced with spaces, as is the norm in markdown text. However, some users didn't like that, so I removed that feature. What you are seeing now is a consequence of that.

There is no reason to use `Shift+Enter` in novelWriter, so the short answer is that you should not. The other solution is to block their use, which may be useful to avoid confusion.

In either case, this is not a bug per say.

**Comment by vkbo** [comment]
Actually, you can see what I mean by entering a comment with a Shift+Enter in it, and save and reopen the document. The comment will now be split up.

I'm going to track this as a minor issue as it is probably a bit confusing. I will make a fix that just blocks this use of `Shift+Enter`.

**Comment by snden** [comment]
Yes, I know, github uses markdown, and before editing the text you could see how it was processing it. For example, how **highlighted text** shows as highlighted even if it is written in two lines **highlighted
text**. If the intention is for Novelwriter to handle it differently, that's fine, and I apologize for the bug report. But I didn't read about this feature in the documentation. Maybe I wasn't paying enough attention while reading.

**Comment by vkbo** [comment]
novelWriter does not span highlighting across multiple lines. That is intentional. The exception here is that the line separator isn't a line break even if it appears like one visually.

Anyway, this is not a feature. It is just how the Qt text editor works. All I can do is add code that either blocks line separator characters or replaces them when they are entered.

The decision to convert them to regular line breaks when saving the file as raw text is a decision made by the Qt library, but I have the option to manually process the plain text myself instead and for instance preserve these line separator characters. If so, they would be preserved between saves, and show up as you expect in the generated output. That may actually be a useful feature. But this may be even more confusing for users who don't intend to type a `Shift+Enter`.

I will give this some more thought and implement one of these solutions for the next release.

**Comment by vkbo** [comment]
Hmm, looking at the code, I see this is a restriction caused by the need to support Qt framework versions prior to 5.9. For those earlier versions, the distinction between line and paragraph separators is always lost when saving as plain text. In order to support `Shift+Enter` properly, I will have to drop support for older versions of the framework. It isn't really a problem since Qt 5.9 has been around since 2017.

For 5.9 and later I manually replace the line separators to be consistent with older versions. If I set 5.9 as a minimum requirement, I can drop this and allow line separators in the saved files.
