### ISSUE TITLE
Errors on startup: Could not create folder: /home/yuri/.local/share/novelwriter/syntax

### ISSUE THREAD

**Issue by yurivict** [vkbo/novelWriter#1180]
```
ERROR     Could not create folder: /home/yuri/.local/share/novelwriter/syntax
ERROR     FileNotFoundError: [Errno 2] No such file or directory: '/home/yuri/.local/share/novelwriter/syntax'
ERROR     Could not create folder: /home/yuri/.local/share/novelwriter/themes
ERROR     FileNotFoundError: [Errno 2] No such file or directory: '/home/yuri/.local/share/novelwriter/themes'
```

Version: 1.6.5
Python-3.9
FreeBSD 13.1 STABLE

**Comment by vkbo** [comment]
Yeah, on a new install on a computer that's never had novelWriter before, the `~/.local/share/novelwriter` doesn't exist at the point when it tries to create the `syntax` and `themes` folders. This should not happen the second time novelWriter is run as it will have created the data folder then.

It's not a problem for the app itself. The issue is handled quietly, aside from the printed errors. Still, I should make a fix.
