### ISSUE TITLE
Handling of exported (active/inactive) check marks in the project tree

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1198]
I'm opening this issue to suggest small but impactful usability improvements in the Project Tree View's **Project Content** . Some of these features are commonly found in popular desktop software.

**Editable Item Labels**

When an item is already selected, allow single-clicking its label to rename it _in-place_. If in-place editing is not feasible to implement, then the single-click should act as if F2 has been pressed, opening the Item Label prompt.

**Set status / Set importance**

The dropdown menu item named "Set status to..." for novel files and the one named "Set importance to..." for notes both could use an additional, separate option to manage the available importance choices. Effectively, each one would be a shortcut to the Project Settings dialog, under the Status tab and Importance tab respectively.

This way users that have not entered the Project Settings dialog before (or that do not normally have it in mind) will be more aware that the options are customisable.

> Note by maintainer: Split out into separate issue #1203

**Cyclable file properties in the tree view**

Perhaps by using the mouse wheel or simply by clicking on the visual cues for file properties (exported, importance) it should be possible to cycle among its available values. A ✅ checkmark would cycle to a ❌ cross, a color square would cycle to the next color square (and re-draw its tooltip).

The downside is that it creates special case considerations about mouse input. (Does the mouse wheel scroll the tree view or cycle the property? Does a click select a file or cycle the property?) The upside is it allows for instant, low-friction property changes.

**"Exported" property tooltip**

Add a tooltip when hovering over the checkmark/cross with a string of text explaining its relevance. E.g. "This document will be included in the finished novel."

> Note by maintainer: Partially solved by #1200, and will be made somewhat irrelevant by planned changes.

**Comment by vkbo** [comment]
> **Editable Item Labels**
> 
> When an item is already selected, allow single-clicking its label to rename it _in-place_. If in-place editing is not feasible to implement, then the single-click should act as if F2 has been pressed, opening the Item Label prompt.

The single- or double-click to edit feature in software is consistently annoying in my opinion. 99 times out of a 100 that i trigger this, it's by accident. Editing the label in-place is more sensible now that it is only the label left that uses a dialog. I still need the pop-up dialog for most cases, but perhaps not for `F2`. The main reason I kept the dialog is that I plan to add an option to have it sync with the first header of the document, which needs a toggle switch.

> **Set status / Set importance**
> 
> The dropdown menu item named "Set status to..." for novel files and the one named "Set importance to..." for notes both could use an additional, separate option to manage the available importance choices. Effectively, each one would be a shortcut to the Project Settings dialog, under the Status tab and Importance tab respectively.

Great idea. I'll add this.

> **Cyclable file properties in the tree view**
> 
> Perhaps by using the mouse wheel or simply by clicking on the visual cues for file properties (exported, importance) it should be possible to cycle among its available values. A white_check_mark checkmark would cycle to a x cross, a color square would cycle to the next color square (and re-draw its tooltip).
> 
> The downside is that it creates special case considerations about mouse input. (Does the mouse wheel scroll the tree view or cycle the property? Does a click select a file or cycle the property?) The upside is it allows for instant, low-friction property changes.

It also has a huge potential for making mistakes as you have to take care not to hover the mouse on any of the icons when you want to actually scroll. A click-through for the checkmark is not a bad idea, but cycle for the status/importance I'm not so sure about. In principle, I can add actual checkboxes, like the ones you see in forms (and on the new merge dialog).

> **"Exported" property tooltip**
> 
> Add a tooltip when hovering over the checkmark/cross with a string of text explaining its relevance. E.g. "This document will be included in the finished novel.

I disagree, because a partially correct, partially wrong, explanation is worse than none. Whether the document is included or not also depends on build settings. I don't really want to start adding long descriptions in tooltips either. There is a "what's This" feature in the Qt framework that is intended for this. I have decided against using it primarily because it should then be used in a lot of places for consistency. If nothing else, it will add a massive load on translations. We also have a global word limit on Crowdin, so I've been trying to cut down on verbose tooltips and dialog boxes.

I think the usage of the checkmark will be more self-evident with the change proposed in #1196. I've also made the manual easy to access from the menu. In the installed version, the PDF is included and can be opened from the Help menu, so it is also available offline. It is explained there what it does.

**Comment by tmarplatt** [comment]
> In principle, I can add actual checkboxes, like the ones you see in forms (and on the new merge dialog).

An advantage of converting those to actual checkboxes is that currently the same red cross is being used in the Project Content and for the close editor/close viewer buttons. It's the same visual cue for two different, unrelated behaviours, which is another UX issue.

Of course you could also simply use a different set of checkmark/cross icons :smile:

**Comment by vkbo** [comment]
I'm aware of this, but there are no other such icons in the icon set. My only other option is using an icon with a checkmark in a box for the checked state, and the empty box for the unchecked state.

I have considered designing a brand new icon set from scratch, but it's a lot of effort and I like the design of the Typicons. SOme of the icons are my own designs though, but those are mostly the tool buttons on the search box.

**Comment by snden** [comment]
As for tooltips, I also think they should be everywhere or nowhere to be not confusing. But the more I work with the tree, I lose overview of which folder contains some file that won't be exported. It would be helpful to have such an indicator for folders as well. For example, if the folder contains all items that are intended for export, it would have a 'tick' icon, if it contains all items that will not be exported, it would have a 'times' icon, and if there are files of both types in it, it would have a different icon . For example like this:
![typ_tick_times2](https://user-images.githubusercontent.com/61266290/196974887-08c93990-34a6-4ef6-badb-66011c40199d.svg)
![typ_tick_times1](https://user-images.githubusercontent.com/61266290/196974893-3f5f431d-c276-416a-bace-c40fb9d6444a.svg)

**Comment by vkbo** [comment]
I plan to add the feature to the folder, yes. It will show the state of all sub-items. My idea was to add a yellow `–` (minus) for mixed state since this is quite common. The problem is what to do with documents with sub-documents. They have their own exported state as well as that of the child items.

The whole selecting files for export thing will be completely redesigned in 2.1 anyway due to #971, so I'm not changing anything this release. Except perhaps renaming the "Exported" label to Active/Inactive. When the build tool is redesigned, the check mark will mostly be an indicator to the user when they work on the documents, so there will be less of a need to look through the tree for these marks. Thus I may only add the mixed state icon to the folders, and leave parent documents only with an icon reflecting their own state.

As for tooltips, I decided in a convention a while back that I've been slowly implementing. All buttons without text shall have a tooltip explaining what they do. Tooltips can also be used to show meta data. Like, hovering over the status/importance icon will show the label for the icon. I am no longer adding tooltips as help. Mostly for the reasons mentioned above.

**Comment by snden** [comment]
I was thinking about how to solve the labeling of folders and files that contain other folders or files, regarding export. I tried several alternatives and took a screenshot for overview clarity. I am attaching one of the variants, it seems to me that color could work. I tried the considered 'minus' for folders, but what if it was possible for folders to allow disable the export of all their contents? Then they could have a 'tick' symbol to indicate that all or some of their contents will be exported, and 'times' symbol to indicate that nothing they contain will be exported. It would be useful to be able to disable the export of multiple items in one place, regardless of their individual settings.
![tree2](https://user-images.githubusercontent.com/61266290/197466841-998dbef4-c487-44cf-81b7-6afd0c303946.png)
![tree1](https://user-images.githubusercontent.com/61266290/197466846-a7b9cfeb-245c-4a48-a7f0-0e2dfef814ac.png)

**Comment by vkbo** [comment]
While I'm happy for the input here, and I will look at a solution, we now have an issue that this thread discusses multiple features that while they're all concerning the project tree, are also completely different features. There really shouldn't be discussions about multiple features in the same ticket. I cannot then actually solve them separately.

I'm going to split the suggestion to add a "manage label" feature for status/importance labels out into its own thread. This thread will now only be about the export tick feature.

The edit label in-tree I think I will not do. I have made a few attempts at it before, and I never arrived at a satisfactory solution.

**Comment by vkbo** [comment]
> I was thinking about how to solve the labeling of folders and files that contain other folders or files, regarding export. I tried several alternatives and took a screenshot for overview clarity. I am attaching one of the variants, it seems to me that color could work.

Keep in mind novelWriter is themeable, which includes the icons. I try to write the code in such a way they they don't assume colour coding. The current themes do have colours indicating things, like chapters are red, scenes are blue, etc. But that is not actually coded into any logic, not written into the documentation.

It can still be done, but it needs to be considered carefully. It cannot be implemented in a way that requires the documentation to talk about icon colours. That is why I prefer to rely on symbols that relay the information in a more intuitive manner.

> I tried the considered 'minus' for folders, but what if it was possible for folders to allow disable the export of all their contents? Then they could have a 'tick' symbol to indicate that all or some of their contents will be exported, and 'times' symbol to indicate that nothing they contain will be exported. It would be useful to be able to disable the export of multiple items in one place, regardless of their individual settings.

You are still thinking of this in terms of an export flag. I have already started to move away from that and towards using it as an indicator of inactive text components. In the new Build Tool, which documents are exported will no longer be controlled from the project tree, so the need for bulk operations for exports will no longer be relevant.

Just made a quick example of ways to solve the icons;

## Active + Inactive + Mixed

These are the standard icons for documents with no child documents, and folders.

![active](https://user-images.githubusercontent.com/1619840/197491246-9ce629a8-901a-4c2a-b82b-df34c45cf06e.png) ![inactive](https://user-images.githubusercontent.com/1619840/197491245-09ff4a4e-5a03-4a04-a6a8-315b67ea1434.png) ![mixed](https://user-images.githubusercontent.com/1619840/197491242-cc75f0c2-16e2-4264-b5d8-2d8ace6b7b18.png)

## Option 1 for Documents with Children

The main icon is for the parent document, the sub-icon for the children

### Active document with active / inactive / mixed children

![active-active](https://user-images.githubusercontent.com/1619840/197491568-99b089d8-3b34-4938-b5e9-2f4712b9b707.png) ![active-inactive](https://user-images.githubusercontent.com/1619840/197491567-fabb04b8-e3fb-4027-8286-6674cde0c368.png) ![active-mixed](https://user-images.githubusercontent.com/1619840/197491564-42cbfe02-4420-4f88-974a-fc3d2ef55507.png)

Inactive document with active / inactive / mixed children

![inactive-active](https://user-images.githubusercontent.com/1619840/197491749-48b5bc51-a6c6-4ddc-ab6c-5323cb1e1ed5.png) ![inactive-inactive](https://user-images.githubusercontent.com/1619840/197491747-6df42f4d-a0aa-4307-9e77-578ef4897eb4.png) ![inactive-mixed](https://user-images.githubusercontent.com/1619840/197491746-68ce77d7-c254-42be-9596-529beba5eb75.png)

## Option 2 for Documents with Children

The main icon is for the children documents, the sub-icon for the main document. These icons are only used in the case where a parent document has mixed children.

![mixed-active](https://user-images.githubusercontent.com/1619840/197492227-f3961268-e2b9-447f-81e4-6f3a89eab741.png) ![mixed-inactive](https://user-images.githubusercontent.com/1619840/197492224-44f2d616-fc54-4bf8-93a9-cafc789ed037.png)

I prefer option 2, as it is the least complicated.

**Comment by vkbo** [comment]
I spent a lot of time trying to find an optimal way to propagate information about mixed active/inactive status in folders. I got it to work, but it isn't optimal and I'm not sure the result was all that helpful in light of the changes regarding documents with child documents, and the fact that the flag will no longer directly indicate export status in the 2.1 release.

I did update the icons though, so that they don't overlap with other icons. I also added an icon for the elements that don't have an active/inactive flag, just for the sake of visual consistency.

The icons are as follows, for active, inactive, and no value, respectively:

![checked](https://user-images.githubusercontent.com/1619840/198883890-b34badaf-5362-4cf2-929a-d7b44d801e44.png) ![unchecked](https://user-images.githubusercontent.com/1619840/198883892-000477b3-38e2-4273-b0c8-5d54343df9b8.png) ![none](https://user-images.githubusercontent.com/1619840/198883891-19ac2a92-cfb1-44ca-8bd6-19c0ec45f235.png)

I've also updated the status / importance icons next to them to have a similar look. These icons are not loaded, but generated on the fly based on the colour choice of the status / importance label. Previously, the icons was just a square pixmap. Now it is a rounded box with the same margin as the active / inactive icons. It looks a bit more consistent.

![image](https://user-images.githubusercontent.com/1619840/198884060-fa30fa40-bfb1-438c-9397-520f47531dda.png)

I think I will stay with this solution for now, and close this ticket. The other ideas have been split out into other issue tickets, and have mostly been added.

**Comment by tmarplatt** [comment]
New icons are excellent!

**Comment by snden** [comment]
The new icons look very good. There is a lot of work to be seen. I think experience will tell more. But I'm thinking about that too because it's an interesting problem. I tried one more solution. Try to judge it:
![tree-expanded](https://user-images.githubusercontent.com/61266290/199180779-ed71d614-a956-4b85-87ba-dd9a5c86feb3.png)
![tree-collapsed](https://user-images.githubusercontent.com/61266290/199180782-efd38531-0887-4f32-a612-f79e9a8f9ab5.png)

**Comment by vkbo** [comment]
Those icons are too big. The sub-icon extends over the edge icon area.

In any case, I could probably make those icons work, but as I mentioned, the problem isn't the icon design, but coming up with a sensible implementation on how to detect what icon each item should show.

I wrote an implementation that works. It used a 4 bit number and used the first bit to signify an item being inactive and the second for active. The third bit indicated if any of its child items were inactive and the fourth bit indicated that any of its child items were active. This produced a list of 12 possible states (there are 4 invalid states out of 16 total).

Now, this worked perfectly, except for each item added to the tree, it needed to loop over all its child items and its chain of parents to the top, and flip those bits. That's a O((n/2)²) problem in the worst case, as the tree is built top-down. These are the kind of things you really want to avoid running into with Python. Python scales very poorly in nested loops.

I could probably run this as a backwards loop after the tree was initialised to get it to scale as O(n) and then use the above algorithm for individual changes, but there are a bunch of other cases were bulk actions are performed where you'd need a mix of the two. It means I'd have to implement both algorithms and make them work together without making mistakes. It's all doable, but I don't think it's worth the effort for a feature that will be a lot less relevant in the 2.1 release.

Incidentally, the accumulated word count algorithm works in a similar way, except it only propagates upwards in the tree from any given item. It doesn't care about the items below it. So it is linear in depth of the tree, which is always a small number even in a large project. In total it is O(xn) where x is the average depth of the tree.
