### ISSUE TITLE
Width of Tree pane is set by length of Label field

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#120]
Some of my document titles are 50 characters long. They're long because they include a synopsis. When I double click on a document name with a wide title the tree pane abruptly widens. The editor and document panes are compressed into the remaining space.

It's quite a jarring and unexpected behavior.

Consider allowing the Label field below the tree view to wrap or to display ellipses in place of characters for which no room remains to display. See the attached screenshot:

![Screenshot from 2019-11-03 12-24-26](https://user-images.githubusercontent.com/8484427/68091472-fee9cb00-fe34-11e9-9dbb-4d9e074f93ed.png)

**Comment by vkbo** [comment]
That is strange. The Qt widget itself should behave like you request, and it does on my computer. the label field shows with an ellipsis and never automatically resizes. I'm not sure what causes this. Can you check in the About Qt box to see which version of Qt you have?

Alternatively, if you run novelWriter with the `-d` flag, it should print the version of Qt and PyQt.

**Comment by vkbo** [comment]
Ah, wait, you mean the bottom panel below the tree view, not the label in the tree itself. That should be an easy fix.

**Comment by johnblommers** [comment]
Yes, the bottom panel below the tree view where it reads Label. That field forces the tree view pane to become very wide. I can only imagine what might happen if the user used a few hundred characters for a document name ;-)

**Comment by vkbo** [comment]
Yeah, I was just concerned at first that older version had a different behaviour for the double click on the tree, or a different default setting. It has an auto-expand feature on double click, but that's vertical expansion.

Anyhow, the fix was straight forward. Just let the label field word wrap when it runs out of space. just to be on the safe side, If the label is longer than 100 characters, it is also truncated.

You're running on a version of Qt that has all the features novelWriter uses, so that's all good. I had to add version checking on a couple of things.

**Comment by vkbo** [comment]
Fixed with PR #122.
