### ISSUE TITLE
Allow to add new scenes to chapters through the right-click mouse menu

### ISSUE THREAD

**Issue by marek-lach** [vkbo/novelWriter#1206]
I am currently running **novelWriter 2.0 RC1** on Windows and have noticed that it is not yet possible to add new scenes under chapters through the right click mouse menu options.

![novelwriterftallowaddingscenestochaptersthrougrightclickmenu](https://user-images.githubusercontent.com/45913977/197790298-688f375f-25b0-4901-9547-29f3eeba8e8a.PNG)

I am unsure really how to add new scenes to chapters after the project has been created at all really, as there's not an option to _Add a new scene under selected chapter_ neither in the Project, nor the Document sub-menus. So that may be this feature request...

Thank you for your development efforts, they are much appreciated!

**Comment by vkbo** [comment]
You add new items to the project with the `+` icon at the top. The menu entry was moved here because there are now a lot of options, and the list will be extended by new features.

The add new items menu can be triggered with the `Ctrl+N` keyboards shortcut as well.

The documentation is not yet updated to reflect these changes, so the only way to find out currently is to look around the GUI. The documentation will be updated for the full release, but there will be an RC 2 release first.

**Comment by vkbo** [comment]
Also, you should switch to the dark icon theme when you use a dark GUI theme. You are currently using light coloured icons on a dark theme, so there is a mismatch.

I will add a checker to this as well to alert you that you are mixing dark and light themes.

**Comment by vkbo** [comment]
Actually, I will reopen this. It may be useful to connect the new items menu to the context menu as well. It may be messy to have it in two places though. I'll see if there are more requests for it.

**Comment by vkbo** [comment]
The icon size for all of the icons in the project tree is the same as the ascent of the font. This is done so not to create gaps and misalignment. It is used in all places icons are aligned with text.

In the final 2.0 release, icons will be chosen by the theme instead of set manually by the user. This should avoid problems with mixing different dark/light settings for theme and icons.

Anyway, I'll consider adding the new items menu to the context menu. It is literally just two lines of code. I'm just concerned it will be messy to have it multiple places.

**Comment by marek-lach** [comment]
> In the final 2.0 release, icons will be chosen by the theme instead of set manually by the user. This should avoid problems with mixing different dark/light settings for theme and icons.

For myself, I think that is a very satisfactory and sufficient solution to the issue.

> Anyway, I'll consider adding the new items menu to the context menu. It is literally just two lines of code. I'm just concerned it will be messy to have it multiple places.

In light of the above, I don't think this is necessary anymore. I just did not notice the separate icon theme setting originally. Will this close this issue as resolved now, thank you.
