### ISSUE TITLE
Also support h1. to h4. declarations for headings in the parser

### ISSUE THREAD

**Issue by marek-lach** [vkbo/novelWriter#1213]
This is a low priority feature request, but the way I understand it, novelWriter actually has its own markup parser, which is loosely inspired by Markdown.

The issue I have is somewhat peculiar, because I use a small-scale 8'' tablet when I travel, that does not have a full-scale keyboard and I have not yet found how to type the `#` character on it using the British English keyboard, without having to constantly switch to EN_US to be able to type markdown headings.

Although this is overall a very minor problem, a solution could be, if novelWriter also recognised the syntax `h1.` as a level 1 heading, which is the syntax of [Textile markup](https://textile-lang.com/) and could be typed comfortably on a compact keyboard regardless of layout.

![support_setting_of_headings_also_through_h1  declaration](https://user-images.githubusercontent.com/45913977/198699566-8309efe4-6fa3-4664-aa5c-c00eff7f96de.PNG)

**Comment by vkbo** [comment]
As a general principle, I don't want to over-complicate the syntax of the editor. It is already custom enough as it is. It would be better to find a different solution. Currently, you can apply formatting through the Format menu as well. Is that not a usable alternative? After all, you don't add that many headers.

You can also use keyboard shortcuts with the control key pluss the number 1 to 4. I guess that doesn't help you much in this case.

novelWriter is designed to be used with a keyboard. Which is why there are no format buttons like there usually is in writing applications. However, it is doable to add a formatting toolbar as an opt-in feature. It's quite a bit of work though as the buttons would all need icons, which may or may not exist in the icon set I am using.

**Comment by marek-lach** [comment]
> Currently, you can apply formatting through the Format menu as well. Is that not a usable alternative? After all, you don't add that many headers.

> You can also use keyboard shortcuts with the control key pluss the number 1 to 4. I guess that doesn't help you much in this case.

To be fair, those are all pretty good solutions.

**Comment by vkbo** [comment]
Currently, you can only apply block formatting on a non-empty line, which means you have to type the header text first. However, I plan to change that in #1178.

**Comment by vkbo** [comment]
I'm changing these to "close as not planned" rather than "completed". I use the list of closed issues to write the changelog, and this helps me to figure out which ones I can ignore when writing.
