### ISSUE TITLE
Sync with s3 compatible

### ISSUE THREAD

**Issue by kromonos** [vkbo/novelWriter#1268]
Similar to https://github.com/vkbo/novelWriter/issues/383 I would love to see a sync to a S3 compatible space, like Minio.  
My reason for this wish is, that Minio is able to provide a version control as well as redundancy, if configured as cluster.  
Minio offers an [SDK for Python](https://min.io/docs/minio/linux/developers/python/minio-py.html), which looks very promising. My experience with Minio is, even for simple storage, that it's way faster, as if one would use e.g. NextCloud via Webdav.

**Comment by vkbo** [comment]
I have no plans to implement a cloud component to novelWriter. Partially because I strongly dislike the cloudification of software, but also because it introduces a bunch of security concerns that I am not willing to deal with. I leave it to the user to decide what sync software to use on their file storage. A lot of them leave a lot to be desired in terms of privacy, and I have no intention of stepping into that whole space. novelWriter is specifically designed to work well with file synchronisation tools in that it works on small, plain text files, and do hash checks to prevent unintentional overwrites.

In the context of version control, the idea is simply to use it as a way to track changes, and has nothing to do with synchronisation per say. That is an incidental byproduct if the user decides to push to a repo. My intention with git was never to push the repo, rather than use it to track changes.

I doubt I will implement a full version control system for novelWriter. I am, however, considering implementing a way to version files by simply saving multiple copies. Another benefit of running on plain text files. In any case, that is the purpose of #383. It is not really a high priority feature as the user can at any time generate a zip file of the project via the backup feature as a snapshot in time.

**Comment by kromonos** [comment]
Sounds reasonable. Thanks for clarifying.

**Comment by vkbo** [comment]
No probs. Don't get me wrong, I am happy for ideas. I realise I came across a little dismissive. I really don't like the cloud from a privacy POV. :)

**Comment by kromonos** [comment]
> Don't get me wrong,

Don't worry. Everything is fine and I can understand the reasons. :)
