### ISSUE TITLE
Unhandled exception on loading v1.4 file

### ISSUE THREAD

**Issue by peter88213** [vkbo/novelWriter#1283]
```
Environment:
novelWriter Version: 2.0.2
Host OS: linux (5.11.0-43-generic)
Python: 3.8.10 (0x3080af0)
Qt: 5.12.8, PyQt: 5.14.1
lxml: 4.5.0
enchant: 2.0.0

KeyError:
'98acd8c76c93a'

Traceback:
  File "/usr/lib/python3/dist-packages/novelwriter/gui/mainmenu.py", line 132, in <lambda>
    self.aOpenProject.triggered.connect(lambda: self.mainGui.showProjectLoadDialog())

  File "/usr/lib/python3/dist-packages/novelwriter/guimain.py", line 890, in showProjectLoadDialog
    self.openProject(dlgProj.openPath)

  File "/usr/lib/python3/dist-packages/novelwriter/guimain.py", line 525, in openProject
    self.rebuildTrees()

  File "/usr/lib/python3/dist-packages/novelwriter/guimain.py", line 841, in rebuildTrees
    self.projView.populateTree()

  File "/usr/lib/python3/dist-packages/novelwriter/gui/projtree.py", line 163, in populateTree
    self.projTree.buildTree()

  File "/usr/lib/python3/dist-packages/novelwriter/gui/projtree.py", line 1027, in buildTree
    self._addTreeItem(nwItem)

  File "/usr/lib/python3/dist-packages/novelwriter/gui/projtree.py", line 1694, in _addTreeItem
    self._treeMap[pHandle].addChild(newItem)

````
Test data is a generated project supposed to be version 1.4. I cannot exclude the possibility that the data does not correspond exactly to the specification. 
See:
[https://github.com/peter88213/yw2nw/tree/main/test/data/normal_v1_4.nw](https://github.com/peter88213/yw2nw/tree/main/test/data/normal_v1_4.nw)

**Comment by vkbo** [comment]
That nwx file seems to be generated from the alpha version, so it is not from a released version. I cannot guarantee that any file generated at any point will work, only project files from released versions.

The issue here is apparently with the trash folder. The definition of the trash folder has changed in the file format, so likely it isn't being added correctly and therefore doesn't exist when the item inside it is being added. It still shouldn't crash though. Even if the file is from an unreleased version of the code.

**Comment by peter88213** [comment]
Actually, there is an error message mentioning the Trash folder preceding the exception.
Feel free to  use the data for "bad case" testing (this also comes up short in my tests).

**Comment by vkbo** [comment]
I would like to prevent it from failing on this, but as I said, this is not a supported file format (the 1.4 version is misleading).

**Comment by vkbo** [comment]
Here are samples of all the valid project file formats which are tested against: https://github.com/vkbo/novelWriter/tree/main/tests/files

The issue with the trash folder is that it has `type="TRASH"` which is invalid in 1.4. It should be `type="ROOT"`.

Since 1.4 never made it to full release, only a pre-release, there is no real need to support it in a converter, but novelWriter does support loading a 1.4 file from the beta release where it was added.

**Comment by vkbo** [comment]
I've located the source of the problem, which is that the type conversion `TRASH` to `ROOT` is only done if the file version is 1.3 or less:

https://github.com/vkbo/novelWriter/blob/66cc3777dc5072b5139013bfcd44e4edf5b83336/novelwriter/core/projectxml.py#L431-L433

Since your XML file is from an unreleased point in the code, I don't think that itself is an issue. However, the construction of the project tree should still be able to handle the case and not crash, All project data should be validated before loaded. So this still needs a fix.
