### ISSUE TITLE
Display issue with mixed_input-none.svg

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1297]
I was looking at some icons to make a custom theme for myself and I noticed the paths in `mixed_input-none.svg` are not joined correctly:

![2022-12-20___01_31_04](https://user-images.githubusercontent.com/60368695/208554015-1d3e73e7-e12b-4b4c-b5e2-16c88e08d5eb.png)

It's actually visible in the GUI, that's why I bring it up:
![2022-12-20___01_25_59](https://user-images.githubusercontent.com/60368695/208554048-c08376f3-4942-4822-b980-865ed7196ad4.png)![2022-12-20___01_25_42](https://user-images.githubusercontent.com/60368695/208554050-53aa466f-b901-4b89-ac96-10082259d2e7.png)
I fixed it:
![2022-12-20___01_29_44](https://user-images.githubusercontent.com/60368695/208554061-3f65b9ad-0717-4c7f-9fd1-6701295fa4fa.png)![2022-12-20___01_29_32](https://user-images.githubusercontent.com/60368695/208554064-149b8847-c969-466e-978f-fb09c7d311a9.png)

I forgot how to make a pull request, so here are the corrected svg files; I hope you find them helpful. I changed nothing but what was inside the respective `<path d=" ... ">`.

typicons_dark: 
![mixed_input-none](https://user-images.githubusercontent.com/60368695/208554128-77169435-d52f-4a1e-bea8-64d944fe919f.svg)
typicons_light:
![mixed_input-none](https://user-images.githubusercontent.com/60368695/208554175-13cd3bf6-574e-4ee9-bdaa-0130e014102c.svg)

---

By the way, is support for icon themes planned? And if planned, is it right around the corner or rather far off?

**Comment by vkbo** [comment]
Thanks! It's not visible on my screen, but it looks like it depends on how the anti-aliasing picks up the two objects. I made the icon from rotating the box of the other icon to make it closed. I probably forgot to union them after. It's easy to fix.

As for icon theme support, it has been there for a long time, and I removed it in 2.0 because I wasn't planning on adding more icon themes as it is a lot of work to maintain them every time there are GUI changes. I plan to modify the loading process so that you can include custom icons in your custom themes folder. It's just a minor modification of the lookup path logic.

**Comment by vkbo** [comment]
Merged to the `patch` branch for release 2.0.3
