### ISSUE TITLE
Open another instance of novelWriter from within novelWriter

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1303]
I frequently find I want to open another project to cross-reference some words. I'm aware there are options to start another instance of novelWriter from the nwProject.nwx file in question, or the start menu or the console. But the option is missing from novelWriter itself: The menu entry "Project" -> "Open Project" will always prompt the currently open project to close.

I propose the addition of a menu entry below that, "Open Another Project".

Alternatively, "Open Project" could do just that, open the "Recent Projects" window, without prompting to close the current project. As it works now, "Open Project" is just a shortcut for the sequence "Close Project" --> "Open Project". I personally have never experienced a use case for this, so I'm wondering if there is a specific reason it was designed that way.

(I swear I'm finding these issues and ideas because I love your software so much. I'm working with it every day. I'd still bash my head against the maze that is all of Scrivener's distracting features if it wasn't for novelWriter.)

**Comment by vkbo** [comment]
novelWriter is not capable of having more than one project open, so the only option available is to open another instance of the app. The whole project behaviour of novelWriter is modelled after VSCode, and code editors in general.

Since only one project can be open, the previous one has to be closed first. At some point I made the open project process automatically close the old project first so you don't have to do that manually. I guess there is no strict need for the close project command other than that the closing process still has to be there in order to open a new project. Adding it to the menu is just a matter of completeness. I cannot remove the functionality itself.

The feature implied by the issue title is something I could look into. I haven't given it much thought before because I'm used to just right clicking the launcher and selecting "New Window", which is how you'd do it in a lot of other apps I use too.

Don't worry about posting issue threads. It's all good feedback!

**Comment by vkbo** [comment]
I'm closing this. Multiple instances of novelWriter can run just fine in parallel, so you can start multiple ones, or double-click a novelWriter project file in the file explorer.
