### ISSUE TITLE
Converting a folder does nothing

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1305]
Context menu on a folder (not a root folder) in either the Novel section or the Notes section, and selecting...

- Transform -> Convert to Novel Document or
- Transform -> Convert to Project Note

... does in fact do nothing; the folder stays a folder. It doesn't matter if there are elements in it or not. This is me using the current AppImage. Running from terminal with --debug also produces no output upon the action.

**Comment by vkbo** [comment]
Hmm, the two options you see there are the menu entries that convert documents from one type to another, not folders into documents. For some reason they are showing up also for folders instead of the options that should show up. They have the same text in the menu entry, so the distinction only exists in the code. Looks like a bug introduced when simplifying the menu entries. It's easy enough to fix.

Thanks for reporting it.

**Comment by vkbo** [comment]
Ok, I've fixed it. I'll try to do a 2.0.3 release on the weekend. There are a couple other minor issues to fix too.
