### ISSUE TITLE
Format > Align left/right/centre inserts a line break when formatting a blank line

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1349]
**The problem**

Changing text alignment works fine when formatting an existing paragraph. But when starting a new paragraph, and the cursor is at an empy line, applying any alignment will insert a line break before entering the alignment markup. Even if there already is a blank line above the cursor.

**How to reproduce**

1. In the editor, enter a new line.
2. Hit Ctrl+6. Same results with Ctrl+5 and Ctrl+7 and through the menus.
3. novelWriter will have added a second line with alignment markup.

**The expectation**

If I've already entered a blank line and am pre-applying alignment to the current blank line, novelWriter should avoid entering a new line break before it.

**Comment by vkbo** [comment]
Both this and #1350 are side effects of a change I made in #1178. Before this change, you could not apply formatting to blank lines, so the logic in the alignment feature only ran on populated paragraphs. This can either be fixed by either reverting that change only for alignment, or by splitting the logic. I'll have a look at both options.
