### ISSUE TITLE
Viewing more than one item in the last column of the novel view

### ISSUE THREAD

**Issue by nyex** [vkbo/novelWriter#1351]
Hello!

I've been using v.2 for some time now and I have a bit of a problem with the project tree sidebar (I think that's how it's called in English). I like it that you can now select what you want to display next to the wordcount (I had been using @ pov to list the characters in the scene just so I could get the names to show on the sidebar), but now it only displays the first item before the first comma. 

I can understand some (most?) would only have one character as @ pov or maybe even @ focus, but I use it to mark which characters are present in the scene/chapter and now I need to change to the outline view or hover over the name to see the complete list (or click the little arrow next to it): 

![screenshot_20230210-130225](https://user-images.githubusercontent.com/15344684/218146773-d1747b11-d256-4161-b838-012ac37750b8.png)
(an example with hovering over one of the names).

Any chance you'd consider allowing for more than one item to show there, like it was before? (here's an old screenshot I found: 

![screenshot_20220915-094810_305x229](https://user-images.githubusercontent.com/15344684/218146843-37c2da4f-6291-47c1-9872-c54d5a650bac.png)

**Comment by vkbo** [comment]
By the way, you can post images directly here in the issue. Those external images tend to disappear after a while, which makes it difficult to read issues later.

Anyway. So, the reason there is only one item shown is that there isn't much room/ I chose to only show one so I didn't have to clip the list of names. Since you can no longer resize the columns, that was sort of the only viable option. If you click the arrow, you should get a full report of all the details about the heading entry.

I guess you are using it slightly different than intended as well. The `@pov` or `@focus` is really only intended for one character. For listing which characters are present, you're meant to use `@char`, but that column isn't available for this view.

I'm happy too look at other ways to display the information here. Maybe also let you choose how many names to show. But the main problem is that there isn't a lot of room for information in this panel. The Outline View is intended to be the full overview tool.

**Comment by nyex** [comment]
Edited it with the images!

I figured it was intentional, but since it was something that was possible before, I wondered why it wasn't possible anymore. Since now you can also chose `@plot` which could be used in tones of different ways that wouldn't always be one word (I think?) I thought it was worth asking about it.

I imagine there's no way to make the columns resizeable again? Or just make the word count column smaller, since (I mean, never say never) that one usually doesn't need that much space?

I started using `@pov` for the character list just because it got listed there, yeah, oops. I wouldn't mind if the list got clipped, though, or if maybe the columns' proportions adjusted themselves according to the size of the sidebar and then showed more or less of it, though that might be a weird solution.

**Comment by vkbo** [comment]
The word count column should always be the size of the longest number, so it is always minimum space.

It is trivial to add the rest of the names for the last column. The data is already there in the tooltip. Here's what happens if I change the code a bit and add three names to a file in the sample project:

![image](https://user-images.githubusercontent.com/1619840/218149199-861353be-131d-4ee3-8731-ec2126e581cd.png)

I have hard coded a limit that the column cannot take up more than 25% of the width of the panel. I suppose one solution is to let the user choose how much size to allow for the column. Even just a few standard options like 20, 30, 40, and 50 % or something.

**Comment by vkbo** [comment]
Here's the same with 40% allowance for the column:

![image](https://user-images.githubusercontent.com/1619840/218150685-bfb1ee4f-bd72-4dad-bed8-25960a8230c7.png)

**Comment by nyex** [comment]
Oh, right, I forgot about the titles (since I barely use them), they also take up space. Smart me.

Both solutions look awesome already, specially if you consider sometimes the titles do get inevitably clipped, so it doesn't look weird at all if the last column also gets clipped sometimes. Of course being able to select the size would be ideal >.>

**Comment by vkbo** [comment]
The old header bar with resizable columns went away with the redesign, but adding a way to set sizes manually may be useful anyway. I'll think about it. I guess I could make a little settings tool for each of these views called "Column Settings" or something with some proper options.

If this requires any larger changes, it will have to wait for a while until release 2.1. Smaller things I can change for 2.0.x, so maybe I'll make some temporary tweaks.

**Comment by vkbo** [comment]
I've added a few fixes for the next release planned for the weekend, and included this one. Basically, I added a "Column Size" menu entry in the novel tree menu where you can select a size between 15% and 75%. The column now also shows all entries in pov, focus and plot, not just the first.

If you want the labels translated to Portuguese, you can do that here if you wish: https://crowdin.com/project/novelwriter

There are a few other labels that need translating as well if you have the time 😃

**Comment by nyex** [comment]
Awesome! Thanks :)

I thought the program was already fully translated, but I had been meaning to take a look if the 2.0 update that changed anything that needed translation. Will definitely check it out when I can :)

**Comment by vkbo** [comment]
There are always new or changed strings that need translating, but usually just a handful so it's pretty quick to do it.
