### ISSUE TITLE
links to 'references' do not work

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1378]
In versions 2.x, the links in the browser section - at the bottom - 'references' do not work. When I click on a reference, nothing happens, the referenced chapter does not appear. In version 1.6.6 this still works. I've been running Novelwriter from appimage since version 2.x.
![novelWriter - Gutta Cavat Lapidem_001](https://user-images.githubusercontent.com/61266290/221399594-c36da0bd-855b-4e35-a5cb-ed23a486995c.png)

**Comment by vkbo** [comment]
Confirmed. This is due to a change in how the titles are indexed, which changed in 2.0. However, this particular feature still tests that the clicked link is on the old format before opening the document, which is of course no longer the case so it does nothing.

Apparently this is not covered by tests. This is a very old part of the code, and some bits are still not covered. A path needs to both fix the bug and add test coverage.

**Comment by vkbo** [comment]
I will try to get out a fix on this, and the other two issues in the 2.0.6 milestone, later tonight.
