### ISSUE TITLE
Several Spanish strings are not being used throughout the GUI, rendered in English instead

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1386]
For some reason, a good number of es_419 strings all over the GUI are being rendered in default English. Initially I thought they were some of the newer ones that I translated recently and didn't pay much attention, but the problem has persisted after the most recent 2.0.x releases.

I'm currently using Linux Mint 20.3 Cinnamon (Qt version: `5.12.8+dfsg-0ubuntu2.1`). I wiped my `~/.config/novelWriter` folder for a fresh installation but the problem persists.

I verified the `i18n/nw_es_419.ts` file and it looks good. The strings are not missing, but they are instead not being used. 

I'm attaching a non exhaustive list of examples:

![menus](https://user-images.githubusercontent.com/16073344/221719936-be1f207f-dfc6-41a2-a5fc-a419fbacc216.gif)

![Preferences](https://user-images.githubusercontent.com/16073344/221719965-4307e8d0-77f4-424c-be4f-7c8559e5d076.png)

**Comment by HeyMyian** [comment]
Cannot reproduce with 2.0.6 (Windows) for any language.

**Comment by vkbo** [comment]
One question: are you manually replacing ts files downloaded from Crowdin to verify them, or are you looking at installed translations?

**Comment by tmarplatt** [comment]
@vkbo I'm running nW from source, no changes to the worktree. I, uh, am supposed to build the .qm files myself every time I pull the repo? I assumed they were built anew into every new translation commit being merged.

**Comment by tmarplatt** [comment]
Well that's a big oops from me then. I built the binary translation files now and things are working as expected. Guess I'm going to add the `qtlrelease` command to my launch script.

**Comment by vkbo** [comment]
At this stage I don't really expect most users to be running from source any more. But the docs are there just in case. I usually work from source myself, but that's because I use my writing sessions also as beta testing 🙂 

You may also find that you cannot create sample projects from the new project wizard if you haven't run the setup.py command to generate the sample project asset. Same for opening the PDF manual from the Help menu. The PDF is included in all releases so that you can use novelWriter offline and still have access to the docs.

**Comment by tmarplatt** [comment]
My confusion stemmed from the change to Crowdin. I'm not really familiar with the build scripts and simply assumed the binary files were being included. Thanks for clearing that up.

**Comment by vkbo** [comment]
Sure, no probs. I should have guessed earlier that this was the issue. I was just assuming you were using the releases.
