### ISSUE TITLE
Some markdown leads to spelling errors

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1415]
I hope I'm doing this right by separating the spell checking into two different issues. Background to #1414:

I don't actually want to write without the spell checker, but some situations with markdown are recognized as spelled wrong, leading to permanent red squiggles. There is no way to add those [sequences of characters] to the dictionary either.

For example:
`_This word is spelled wrong?_`
vs `_This word is spelled correctly._`

I'm wondering if markdown could be excluded from the spell checking somehow?

**Comment by vkbo** [comment]
This may be some regex quirks. The splitting of words for spell checking is done in the syntax highlighter using the Qt regex class running in Unicode mode. It may not properly detect word boundaries in some cases. Particularly with underscores, which are defined as characters not boundaries. It's just a matter of accounting for all the corner cases I suppose. I have not encountered this particular one before.

**Comment by vkbo** [comment]
I actually want to pull spell checking out of the syntax highlighter class entirely, but I have not yet found a good solution that does not come with a performance hit. I have some ideas using a background worker thread that I want to try out.

The issue now is that there are two different implementations. One for checking spelling, and one for interacting with the word when right-clicking. They behave slightly differently, which is why adding the word to dictionary isn't always possible. Especially in these corner cases. Another reason why I want to add a single solution.

**Comment by HeyMyian** [comment]
Does it help in the meantime if I identify these cases for you? Another one is:

`_It’s just Blablablubb._` where "Blablablubb" is a word manually added to the dictionary but considered spelled wrong, as is `’s`.

But conversely, there is:
`Fantasyword.` (not in dictionary, spelled wrong)
`_Fantasyword._` (not in dictionary, spelled right)

**Comment by vkbo** [comment]
No, I think I know what exactly is the issue. It's just a matter of creating a regex that select all words, but don't treat underscores as part of a word.

This is the current algorithm: https://rubular.com/r/IDmh4pcfAeyWk8

It basically ignores spell checking of words with an underscore, which in itself isn't optimal, but for some reason it treats words with punctuation on the inside of the italics wrapper as a part of the word, which is what causes the issue here.

**Comment by vkbo** [comment]
> `_It’s just Blablablubb._`

This one is interesting too. Due to the underscore, the `_It` part is ignored, so the remaining word is `’s`, which isn't anything either. I wish there was a way to force the parser to consider underscore a boundary character.

**Comment by vkbo** [comment]
I sort of just gave in. I've been trying to fix this issue many times before, but I just added a fix that simply replaces all underscores with spaces before running the spell checker code on the text buffer. It doesn't affect the content of the document, it just hides underscores from the regex parser.

It slows down the processing, but not in any noticeable way for small documents. For large documents, all of this is slow anyway.

**Comment by vkbo** [comment]
When I rewrite this code eventually, I will move the spell checker processing into a parallel thread and only have the syntax highlighter apply the wiggly lines where they're needed, after they have been found. This will put a delay between opening the document and the spell checker getting to each paragraph, but in the majority of cases the delay will not be noticeable.

I may have to put a threshold on when the spell checker finds too many misspelled words and stops highlighting, otherwise I think the editor will just freeze up. This is usually an indication that the wrong language is selected anyway, so no point spending the resources.

**Comment by HeyMyian** [comment]
Fastest repo owner EU, if not worldwide. Seriously, thank you 🙇

**Comment by vkbo** [comment]
Hah, well, I just couldn't *not* investigate those. The spell checker regex has been a looong running issue. It's extra tricky because it needs to treat non-latin characters correctly as well.
