### ISSUE TITLE
Allow touchpad scrolling in text margins

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1425]
Currently, touchpad scrolling (with two fingers or touchpad edge) only works when the cursor is over the text area. Perhaps it could be expanded to allow scrolling also when the cursor is over the text margins.

I only notice this now because on my old netbook with its tiny screen, I had no text margins. I have a 1920p screen now that I operate with a touchpad and immediately noticed I wanted to scroll there D:

**Comment by vkbo** [comment]
The text margin is actually only 1 pixel, the rest is a margin of the viewport itself. I suppose this is why the scrolling does not work, because you're actually not on the document itself. It's pretty much the same as you'd see with the paper sheet and margins in a full document editor, I just don't set different colours on the areas. This is how the max text width feature is implemented (basically defining an invisible paper size).

I can look into whether there is a way to allow for scrolling in these margins in the Qt framework, but I can't remember seeing one.

**Comment by vkbo** [comment]
Found a way to resolve this by using an event filter to catch all mouse scroll events on the editor window and forward them to the central editor text area. It should not only work on the margins now, but also when hovering over the header, footer and even search box when it's open.
