### ISSUE TITLE
Allow custom tag to be changed

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1439]
There's the custom tag. However seeing that you can rename its label, wouldn't it be better to have the custom tag follow the label of whatever it's renamed to? People could have multiple custom tags, each with their own name. This could cause confusion for them if I had the custom tags foo and bar, they would both be considered custom tags by NovelWriter, being cause of confusion.

What I would like to see:

Create new custom tag, and name it "foo", from that moment onward I would address it with `@foo:` in my documents/notes.
Then I'd create another custum tag, and name it "bar", from that moment I would address it as `@bar:` in my documents/notes.
They would show up in the project tree as "foo" and "bar", and so they need to be able to be referenced as such.

**Comment by bar** [comment]
@xahodo I guess you didn't mean to tag me here, right?

**Comment by vkbo** [comment]
Sorry about this. Unfortunately, people keep tagging random users on GitHub due to the @ symbol being used for commands in this application. I've edited the issue and wrapped the relevant parts in backticks to disable tagging.

**Comment by xahodo** [comment]
There's one consideration to take note of with this: fools (me, for example) creating a double tag for a built-in one. "Characters" for example. Will this just result in another category with the same name, which will be iterated, or will it result in an error?

**Comment by vkbo** [comment]
> There's one consideration to take note of with this: fools (me, for example) creating a double tag for a built-in one. "Characters" for example. Will this just result in another category with the same name, which will be iterated, or will it result in an error?

What do you mean by "double tag"? Two "Character" folders? You can do that if you want to. novelWriter treats them as the same and combines the content. It is the type of root folder that matters, not what they're named either. If you have a Custom type root folder named "Characters", the content will still not be treated as characters.

Making the `@` tag user-definable is not likely to happen simply because it makes the indexing system much more complicated. It also means I can never add new `@` type commands, because any give project can have one defined that has the same name.

As discussed in #1556, your best option is to make the type of custom tag a part of its name:

```
@custom: foo/bar
```

If you have a suggestion for a new category you would like added, in addition to the current 6 + custom, you can suggest it.

I'm closing this issue as well since it will not be implemented as suggested due to the consequences as mentioned in my second paragraph above.
