### ISSUE TITLE
Change behavior of asking for a chapter/scene name on creation.

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1443]
Current behavior:
Upon creation of a chapter/scene in the project tree, the user is requested for a name. It's possible to leave the name as is. This behavior from the application pokes the user to create a name for their chapter/scene in advance.

Desired behavior:
Upon creation of a chapter/scene in the project tree, the program just creates an entry with a generic name and allows for changing it later. In an ideal situation the generic names would be numbered, as to differentiate between multiple of them.

Possible compromise:
Make this a configuration option, where users can switch between the dialog appearing on chapter/scene creation or not.

Rationale:
In writing, common wisdom is to first write your chapter/scene, and then name them. If it's done the other way around, writers might find themselves molding the chapter/scene to fit the heading. I've fallen for this trap myself.

**Comment by vkbo** [comment]
You are free to leave the new document with the generic name if you wish, all you need to do is hit the enter key. This is a minor inconvenience compared to the opposite case where you will need to right click and select "Rename" to set the name after you've created the item if you *do* want to assign a name.

The latter path is significantly more friction to the user, so I do not agree that this should not be the default behaviour.

**Comment by tmarplatt** [comment]
First, I wish the "Item Label" dialog had a checkbox that, when checked, _by default_ appended an item counter to the chosen name. Basically what @xahodo is requesting, but also similar to the Formatting Codes of the Build tool, i.e. giving the user the power to choose where and how to insert the counter. So, a simple option charged with more advanced usage if the user is so inclined.

Another wish related to naming: I think there is an argument to be made about having the ability to couple document names (item labels) and first headings. Since novelWriter already autofills the first heading with your chosen document name, why not allow the user to choose which documents should make of that. Make it seamless: all you have to do to rename a label is change the document's heading. novelWriter takes care of the rest.

Either that or a more involved "Update Label" option in the Project Tree/Novel Outline views, which updates all selected document names using the heading in the first line (or no update if there is none).

**Comment by vkbo** [comment]
I've already added a feature to right click a document heading and set the item label to match. Adding a way to right click an item and pull the title from the first heading is a logical next step. Now that multi-select is possible, it is also possible to make it an option for several items at once.

Adding a checkbox to sync them both ways will not happen, as novelWriter will not edit a document that isn't open.

Tasks:
* [ ] Add a context menu entry in the project tree to update the item label to the text of the first heading in the document.
* [ ] Add an equivalent feature for multi-select.

**Comment by vkbo** [comment]
I've added an option to the context menu that will allow easy rename to the main heading of a document, if one exists. It only shows up when right-clicking documents that have a heading.
