### ISSUE TITLE
Allow markdown within a word

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1444]
I find it useful to allow markdown within a word, specifically italics, to emphasize a certain part.

`_penni_less` --> *penni*less
`**penni**less` --> **penni**less
`~~penni~~less` --> ~~penni~~less
Neither work, they output (build tool) the markdown symbols instead applying the formatting. The syntax highlighter also does not recognize it.

Not sure if bug or feature request. I thought not recognizing it was standard markdown behavior, but Discord and GitHub for example know how to deal with it.

**Comment by vkbo** [comment]
Have a look in issue #1337.

I am working on a suitable syntax for sub/superscript, and I think the syntax can be extended to support special cases of complex formatting like you request here. I'm proposing to use `{xx:text}` notation for inserting custom things in the text, where `xx` is a code, and `text` the text to apply it to. In a branch I've added codes for bold and italics as well, and since this is presumably not something you need very often, it's not a too clunky syntax. The highlighter helps make it stand out too.

Join the thread and let me know what you think. I don't want to split the discussion into two places. This notation can also be used for footnotes, and perhaps other features too since it is very flexible and incredibly easy to parse.
