### ISSUE TITLE
Duplicate scenes/chapters/novels

### ISSUE THREAD

**Issue by novakwh** [vkbo/novelWriter#1469]
Hello, first, just to say how much I love novelWriter; thank you for this software!

I've looked around for an answer to my dilemma and can't find the right answer. You may already have a way for me to handle my issue, but I haven't been able to find it yet.

The only possible workflow I can see for revision in the software right now is to edit/type directly into the same document as the first draft. But when I rewrite/revise, I like to leave the entire first draft as/is. So I would like to actually create the second draft as a copy of the first draft, so that I can then rewrite/revise from that point, while still maintaining easy access to the original first draft for review.

I think the simplest way to handle this would be to create the second draft as another novel within the project. That way I could easily switch back and forth between the drafts as necessary, since it does not appear that novelWriter will allow me to open more than one project at a time (I use Mac, if that matters). (To try to make the workflow clear: I write a first draft scene, then n the second draft, I start with a copy of that scene, but rewrite/revise it, while still being able to go back and look at the original first draft for comparison. The exact same workflow may apply to further drafts.)

As it stands right now, I have to painstakingly recreate the first draft contents into the second draft by copying/pasting individual documents as I go. It would be great if there was a duplicate function that would copy a component and allow you to send that duplicate to another novel (or even another project). 

Ideally, I would be able to:

-- duplicate a novel's entire contents into another novel folder, or
-- duplicate a chapter and its scenes into a specific novel folder, or
-- duplicate just a scene into a specific novel and chapter.

In this way, you'd give a writer the choice if they want to move everything all at once, or just move piece by piece without having to do a manual copy and paste.

Some people might also want the ability to duplicate or move scenes/documents into a different project altogether, which I don't see right now as a capability unless I'm missing it. (IIRC, Scrivener has a similar function to this.)

Does this make sense? Thanks again for this terrific software.

**Comment by vkbo** [comment]
While you cannot open more than one project in novelWriter, you should be able to open more than one instance of novelWriter itself. At least I can easily do this on Linux. I'm not sure about Mac since I'm not really a Mac user. On Linux, I can right click the icon and select "New Window".

As for revisions, you can either duplicate the project itself and then open two versions in two windows, or you can export a single document containing the first draft. If you export it as a "novelWriter Markdown" document, you can create a new document in a suitable location in your project, open it, and import the whole thing again from the menu at Document -> Import Text from File.

For individual chapters, you can use the merge tool to assemble a new document from a folder or parent document containing other documents. There is an option to duplicate the content in the process. That should give you a chapter by chapter copy, assuming you created your scene files under a chapter folder or chapter document.

So, there are multiple ways to achieve what you want, without having to do it one document at a time.

That said, there should be a way to duplicate documents or hierarchies of documents. There are many use cases for this, including copying note templates and scene templates. There are other suggestions for similar features, but I'll keep this one as it explains the different options needed for a relevant use case.

**Comment by vkbo** [comment]
I've added a feature for duplicating both single documents, as well as folders/parent documents with all child items. It doesn't rename anything, it just creates an identical copy next to the item selected.

The duplication feature will be available in release 2.1 when it's ready.
