### ISSUE TITLE
Markdown export

### ISSUE THREAD

**Issue by Torsten-K** [vkbo/novelWriter#151]
When exporting to Markdown format, not everything works fine: line breaks and lists are not saved in the correct Markdown format. You can check this with a Markdown editor like Retext or any other.

Xubuntu 19.10, pypandoc is installed.

**Comment by vkbo** [comment]
Hi, thanks for the feedback. The export is still a work in progress, but I'll look into seeing if this can be improved.

First of all, line endings don't have any meaning in markdown, only line breaks (as in empty lines) do. When the export tool parses your file, line endings are ignored unless they are full line breaks. This is intentional behaviour, and is done so that the lines can be wrapped. I'm happy to reconsider this behaviour. If you need hard line breaks, novelWriter supports the hard line break syntax of ending a line with two or more spaces before the line ending. This can also be achieved by pressing `Shift+Enter`.

Secondly, lists are not supported in novelWriter. This is not a full markdown editor, and the formatting features supported are listed in the README. Lines starting with * are therefore treated as regular paragraphs.

I'm considering adding support for lists, but it is not high priority.

**Comment by vkbo** [comment]
Updated the README to clarify that novelWriter is **not**  full-feature markdown editor, and the users should not expect it to be.

This is otherwise covered in the documentation.

**Comment by Torsten-K** [comment]
Thanks for the clarification. To be honest, I don’t like reading manuals too much, and thus I started using your program without reading the docs before, please forgive me.

Anyway, the line breaks work when exporting to HTML, also to TXT, but they don’t when exporting to MD, so my guess is, that it’s a bug. Besides, the HTML5 source code looks quite clean to me, which is great!

I guess I’ll have to dive a bit deeper into your software, and I know that it’s in early stage, so I’m looking forward to further development. Keep up your good work!

**Comment by vkbo** [comment]
> Thanks for the clarification. To be honest, I don’t like reading manuals too much, and thus I started using your program without reading the docs before, please forgive me.

I know what you mean. I never read the manual either. So it makes sense adding it back into the README.

> Anyway, the line breaks work when exporting to HTML, also to TXT, but they don’t when exporting to MD, so my guess is, that it’s a bug. Besides, the HTML5 source code looks quite clean to me, which is great!

Yes, that was indeed a bug. Interestingly, the markdown export seemingly did the same thing as the text export, just on one line instead of two. Surprisingly, those two ways of writing what appeared to be the same code, actually produced different results. There are some interesting quirks in operator precedence when adding operations to old style Pyrhon format statements.

Copied the code from the text export to the markdown export, and hard line breaks are now preserved.

> I guess I’ll have to dive a bit deeper into your software, and I know that it’s in early stage, so I’m looking forward to further development. Keep up your good work!

Thanks!

It's a hobby project mostly driven by what I need for my own writing. I mostly write simulation code and data analysis code, so a GUI app is a different experience. I'm trying to keep the scope of it fairly narrow to avoid it growing to a big project.

**Comment by vkbo** [comment]
Fix added, so the bug should be solved. Closing.
