### ISSUE TITLE
microsoft smart screen flagging the application

### ISSUE THREAD

**Issue by ahmedomar365** [vkbo/novelWriter#1526]
<img width="1280" alt="image" src="https://github.com/vkbo/novelWriter/assets/70892817/e44802d7-9ae5-450e-841c-c7b332d95297">

**Comment by vkbo** [comment]
I honestly have no idea what to do about all the Microsoft anti-open source bullshit. When are you encountering this? During installation?

**Comment by vkbo** [comment]
Please provide some context to bug reports in the future, as it is really hard to guess what's going on. I'm going to assume this happened when you tried to download the installer. When you download the installer, you can select to ignore the warning and keep the file. There is a menu of options next to the download dropdown in Edge.

I filled in the form, but I seriously doubt it will make any difference since Microsoft is actively sabotaging open source projects that can't afford to pay through the nose for signed installers. They have removed other options that existed in the past. If they keep it up, I may have to stop supporting Windows altogether and just focus on Linux users, which doesn't suffer from this type of nonsense security theatre.

In any case, closing this as there isn't anything else I can do.
