### ISSUE TITLE
Building source language files from command line requires Qt6's lupdate

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1538]
While novelWriter claims to use Qt5 and above, when using the supplied scripts to manually build the language binaries, I get the following error:

```
➜ python3 pkgutils.py qtlupdate i18n/nw_es_419.ts

Building Qt Translation Files
=============================
ERROR: This command requires lupdate from PyQt6
```

On my system, `lupdate` is supplied by the `qttools5-dev-tools ` package, which depends on Qt5.

(If otherwise the Qt version requirement for novelWriter has been bumped since, then the source readme file and the i18n readme need to be updated.)

**Comment by vkbo** [comment]
It is supplied by `pyqt6-dev-tools` actually, and is a pure PyQt6 tool and has nothing to do with the Qt framework itself. It processes Python code to extract translation strings and write the `.ts` XML files. Qt's own tool only does this for C++. The maintainer of PyQt never updated this tool to support the 2.1 file format for TS files in PyQt5, so `pkgutils.py` instead uses the PyQt6 version of the tool, which *has* been updated.

This has nothing to do with the actual Qt framework and the novelWriter app itself, so there is no change in dependencies for novelWriter. It's purely a dev tool. I only use it for generating the raw source files I upload to Crowdin, which is something only I have access to do anyway.

The README file in `i18n` is mostly legacy, and for people who prefer to use the Qt Linguist tool for translations rather than Crowdin. It has its advantages, as it shows the string context directly in the source code, which Crowdin does not. That's pretty much the only case where anyone would need to call this command aside from my own maintenance tasks.

I can add a note in the `i18n/README.md` file, sure.

**Comment by vkbo** [comment]
This is not required for building the binary translation files by the way. That's the `qtlrelease` command, which uses the Qt5 dev tools.

**Comment by tmarplatt** [comment]
The move from using setuptools/distutils to the new `pkgutils` threw me off. I was indeed using the wrong command.

**Comment by vkbo** [comment]
There is no "move from using setuptools" (distutils has been completely removed from Python now). The `setup.py` file is deprecated and has been for quite a while, so I removed it. I *had* to rename the file for the rest of the tools in it. It could not remain as `setup.py` since that file has a specific meaning.
