### ISSUE TITLE
Project tree does not scroll when dragging an item to edge

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1561]
Expected behavior:
Project tree view scrolls when the dragged item goes below or above, respectively, the upper or lower boundaries of the widget.

Current behavior:
The project tree widget does not scroll when an item is dragged.

I have a project which is growing. There are more project items than the project tree widget can display.
Sometimes I want to move an item to a position which is currently out of the viewable area. Unfortunately, the widget does not automatically scroll when an item is being dragged.

Workaround (prone to errors and slow):
Drag the item part of the way, drop it, scroll, drag item further, drop it again, scroll, and so on. Until the item is on its intended position.

I hope I was clear enough. I'm not the best at describing an issue.

**Comment by vkbo** [comment]
Ok, so I've investigated this.

First if all, this should work by default as it is the default behaviour of the tree widget itself out of the box.

But, I notice that the whole drag and drop implementation in at least Qt 5.15.8 is severely broken. I haven't really noticed, since it isn't that long since the library was updated on my PC. Not only does not autoscroll work, but also the setting that disables drag and drop onto the empty area of the tree no longer works, which means you can move around root folders, end even drop files onto the top level. The setting in the code that disables this is just outright ignored!

For reference, I tested with the AppImage, which comes with Qt 5.15.2m and there everything is fine. I also tested on a Ubuntu 22.04 box, which has Qt 5.15.3. All is fine there too.

This is incredibly annoying. I would have to add back in a ton of checking code to manually block these actions, and I cannot do it as smoothly as the default library implementation could.

I'll continue to look into it. I need to go have a look in the Qt source code to see when it was broken.

**Comment by vkbo** [comment]
Could you tell me what OS you're running on, and what Qt version is reported by "Help > About Qt"?

**Comment by vkbo** [comment]
Oh, and another thing I noticed is that if you drag a project tree item out of novelWriter and onto another app that accepts drops, the item is deleted from novelWriter by the Qt library, which then causes novelWriter to crash because that shouldn't even be possible.

**Comment by vkbo** [comment]
Ok, I made a new issue for the drag and drop stuff in #1569. They are easier to handle since I can add in two relatively easy checks, which I've done in #1570. This only solves the illegal drop moves internally in the tree.

I'm not sure how to fix the autoscroll issue. It is broken on the library level. All I can do is disable it and implement my own. Let me know what OS and install method you're using. I think you can solve the issue at your end by switching to the AppImage though.

**Comment by xahodo** [comment]
I'm on Qt 5.15.3.
Linux Mint 21.2 (Cinnamon, if that's relevant)

**Comment by vkbo** [comment]
Ok, so you are using the Debian package? Could you download the AppImage and test of autscrolling works there?

**Comment by vkbo** [comment]
I just wrote my own autoscroll implementation after looking at the source code of the C++ library and what it does. I've disabled the built-in one entirely. At least then I control it myself. It wasn't very complicated to add.

It will detect when you're near the top or bottom of the tree area. I set the margin to one icon height from the edge. It's just a convenient size unit available in the novelWriter code. It works by using a function that forces items in the tree into view, and it will just request that the next item out of view scrolls into view.

The effect has a 250 millisecond delay, and only one scroll is triggered every 250 milliseconds. You'll have to wiggle the dragged item a bit to trigger more scrolls, but that's pretty common.

I'll make a release tomorrow with all the recent fixes. let me know how the new autoscroll feature works, and if it needs tweaking. Either by changing the margin, or timing, or how it scrolls.
