### ISSUE TITLE
Preference window initial height

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1604]
This is an issue in the German translation and our looooong words, and it will apply to other languages with similarly long words.

In the most crowded preference tab, "Automation", the German translation has too many lines. On the initial window height, lines get cut off funnily. This is easily fixed by the user by manually dragging the window to be a little bit taller, and the setting thereafter is permanent. Similar to #1551, this might be a usability problem, that's why I bring it up.

Upon further thought, the cause is my novelWriter UI font size, which is 13 (default is 11). I never thought this was excessive, tbh. Maybe there is a way to detect the required height of the content to set the window size accordingly, but feel free to discard the issue based on my self-made predicament. I have no idea how applications are handling/supposed to handle things like this.

Here is what the initial window size looks like in English:
![Screenshot_2023-11-13_03-37-39](https://github.com/vkbo/novelWriter/assets/60368695/52a2e415-ac8c-4e7d-96f7-cba8ed497c9b)

And this is what it looks like in German:
![Screenshot_2023-11-13_03-38-17](https://github.com/vkbo/novelWriter/assets/60368695/eddb24a1-32b4-4394-a8b2-aeda5316159e)

**Comment by vkbo** [comment]
The issue here is only window height. Qt will steal space from wrapped labels if there is not enough room. The solution is to resize the window. The Preferences dialog should remember its height.

It is very hard to calculate the size before hand. The only real solution is to make the settings areas scrollable.

**Comment by vkbo** [comment]
I'm working on updating the layout of the Preferences dialog, and I've converted the whole thing into a long, scrollable page with navigation links instead of tabs. This will solve your problem as well as it can use the vertical space it needs since it has a scroll area for the actual settings.


https://github.com/vkbo/novelWriter/assets/1619840/88c63bb6-428b-463d-8be8-91f8040eb1c8
