### ISSUE TITLE
Clarify Import and Split Workflow

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#161]
It took me a few minutes to understand how to use the new split file feature. Consider documenting  the workflow. I found the following procedure worked well.

### To import a large Markdown document into novelWriter

This procedure begins with an empty project and a large Markdown document with H1 title headings and H2 chapter headings. It ends with a novel folder of title folders each containing their scene documents.

1. Create a new project
1. Click on Novel in the tree pane
1. Create a new document (Menu &rarr; Document &rarr; New Document)
1. Select it in the tree pane.
2. Import a large document (Menu &rarr; Document &rarr; Import from File)
3. Select the imported document in the tree pane
4. Menu &rarr; Document &rarr; Split Document to Folder
5. The Split Document dialog appears
6. Choose Split on Title Level
7. Click Split.
8. A folder with the same name as the document is created containing each title.
9. Click on each title and split each one at the chapter level
10. Optionally continue splitting to the scene level if appropriate
11. Clean up the tree pane by deleting old unsplit documents.
12. Get to work reorganizing and editing your novel

### Notes

- You may inadvertently do a split and create a folder of documents. You cannot delete a folder unless you empty it first. Fortunately the <kbd>Ctrl</kbd><kbd>Del</kbd> keyboard shortcut is a very quick way to remove a folder's documents one at a time because there is no confirmation prompt
- A document deleted from the tree pane winds up in the Trash folder. You cannot move a folder to the Trash. When you delete a document from the trash then it is truly deleted. But novelWriter first prompts you for confirmation.
- You cannot select multiple documents at a time to split them en masse. There is no keyboard shortcut to trigger the Split Document dialog.
- The Split Document dialog does not remember its previous setting so be mindful of which heading level you split your document at.

**Comment by vkbo** [comment]
This will be documented once there is a new release. Currently I just want to test it and tweak it. It is actually interesting to see how a person who didn't get any documentation figured out the feature, which gives me some indication how intuitive it is. I see a few hiccups. I mean, most people don't actually read the manual! :)

The first thing that jumps out is that you thought you could only split on one level at a time. You can split your document in one go. No need to repeat the process. The dropdown list needs to be clearer to indicate that it is about deepest level to split at, not the only level. The later interpretation doesn't make much sense, so I didn't consider this. I will alter the options to say "Split up to level 1" etc.

Now, about your notes.

> You may inadvertently do a split and create a folder of documents.

Not a very likely scenario I think, and since nothing is automatically deleted, no damage is done. Just a bit of cleanup needed.

> You cannot delete a folder unless you empty it first.

I've considered adding recursive delete, but deleting documents isn't something you'd do that often, and recursive deletes are risky. Even if the documents are just moved to Trash, this does destroy the folder structure.

> You cannot select multiple documents at a time to split them en masse.

There has been no need for multiple document select so far because there are no features that truly depend on this. Multiple document drag and drop is messy, and I am reluctant to allow it. Splitting en masse likewise. It's not something you should need to do en masse in the vast majority of cases either once I clarify the UI to avoid misunderstandings.

> There is no keyboard shortcut to trigger the Split Document dialog.

It's not a feature I expect people to use frequently, so I didn't see the need. However, a shortcut is a trivial thing to add with Qt. It's a one-liner. Let me think about what would be a sensible shortcut.

> The Split Document dialog does not remember its previous setting so be mindful of which heading level you split your document at.

I'm considering adding a global dialog options file to hold all states of selected options per project. Currently, some dialog boxes have individual ones, but it's a bit messy. It's on my ToDo list. I didn't bother adding an individual storage option for this dialog at this moment. It will be included in the shared one.

### Additional Points

* Currently, you also have to delete each file in the Trash folder one by one. This pops a dialog box, which makes it a bit tedious for many files. I plan to add an "Empty Trash" option with a single dialog box for confirmation. Pretty much standard file system stuff.

* I have commented out multiple select on the tree in the source code since no feature currently actually takes advantage of this. A drag and drop will only move the item you drag, and ignore the rest if you have multiple selections. The main use I see for multiple select at present is for multiple deletes. I am trying to find a balance between avoiding annoying repetition and reducing the risk of accidental actions. There is nothing more annoying than knowing you accidentally hit a keyboard shortcut that did something, but you didn't quite catch what it was it did.

* I used to have a context menu (right click menu) in the tree. I'm considering adding it back to simplify access to some features. It may be a better solution than having keyboard shortcuts for tasks you don't want to trigger by accident, like empty trash, merge folder, split document, etc. In addition it could hold options for making new files or folders, and quickly change the document layout without opening the edit dialog.

**Comment by vkbo** [comment]
Oh, and thanks for your feedback. This is extremely useful. I got a bit caught up in the details, and forgot the important part. :)

**Comment by johnblommers** [comment]
You're very welcome.  The split feature was worth the wait, is IMHO huge and elevates novelWriter. It was the work of mere minutes to figure out, import and split my 65,000-word NaNoWriMo Markdown manuscript with novelWriter. It took longer to write up my notes ;-)

**Comment by vkbo** [comment]
Great!

Leaving the issue here for now so I can address the points you made, and the points I added.

**Comment by vkbo** [comment]
I think all relevant points here have been addressed by now. I do want to add back in a context menu for the project tree, but I've got that in my short todo list.
