### ISSUE TITLE
Unexpectedly switching to Novel Tree View after adding a new root folder

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1648]
For no particular reason, adding any new root folder will make novelWriter switch to the Novel Tree View (from the Project Tree View, where I use the controls to add the root folder). 

**Caveat**: in a new project, the first new root folder is added without side issues. From the second new root folder onwards, novelWriter will always unexpectedly switch view.

Here's the above, illustrated, on an empty newly created project:

![newrootfoldertonoveltreeview](https://github.com/vkbo/novelWriter/assets/16073344/f976a42b-1f0f-47ed-9086-e62dde3dcf02)

On latest novelWriter 2.2, under Linux Mint 20.3.

**Comment by vkbo** [comment]
In the last release, the focus switch for the project and novel trees was changed into a toggle feature, where pressing `Ctrl+T` alternates between the two tree views. I guess there is remnant code that still calls this when a new root folder is created. In the past, the root folders were created from the main menu, so I expect the focus switch is called to ensure the project tree is visible when the root folder is added. Since the focus code alternates between the trees now instead, I expect this is causing this issue.

That call can just be removed, since the project tree already must be visible to create the root folders.

You can get around this issue by clicking in the editor before creating the root folder, as that will prevent the toggle feature from triggering. It only toggles if the tree view already has focus.

**Comment by vkbo** [comment]
Funny enough, it was an issue report from you that got that line added in the first place, in issue #1376, extracted from https://github.com/vkbo/novelWriter/issues/1368#issuecomment-1444655891

I'll try to preserve that feature still.

**Comment by tmarplatt** [comment]
Yeah, the "first added folder doesn't trigger" behaviour sounded fishy to me as well, but I didn't connect the focus switch to the bug.

Don't worry I'll be here to report the next bug in the chain hehe
