### ISSUE TITLE
Scene separator insert only works properly after a chapter

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1704]
Scene separator is supposed to be inserted only between scenes, but if there is no chapter, it is also inserted before the first scene.

See also (https://github.com/vkbo/novelWriter/issues/1050#issuecomment-1951434598)

**Comment by vkbo** [comment]
Thanks for reporting this. It's not a serious bug (just a little annoying for short stories), so I'll scheduled it for fixing in the 2.3 release.

**Comment by vkbo** [comment]
Thanks for reporting this. It's not a serious bug, just a little annoying for short stories. It's technically not a bug at all since chapter-less stories wasn't considered here. novelWriter is designed for long form fiction, so the logic isn't designed to skip levels, but this is an easy thing to fix, so there's no reason not to.

I'll scheduled it for fixing in the 2.3 release.

**Comment by vkbo** [comment]
Discovered a few issues with the way scene separators and chapter/scene number are handled. I have changed the functionality, and it now works like this:

![Screenshot from 2024-02-24 14-30-21](https://github.com/vkbo/novelWriter/assets/1619840/9487ced9-55af-4a4e-906b-1d1c0b2ab8cd)

Here, "Title" is a new `#! Title` entry, which means chapter and scene numbers are also fully reset. In addition, the flag to hide the first separator after a heading higher than scene is introduced.

![Screenshot from 2024-02-24 14-30-35](https://github.com/vkbo/novelWriter/assets/1619840/5575dcb0-2941-474a-85d1-f7cdf8128967)

For formatted titles, there is no change. They are always printed.
