### ISSUE TITLE
Disable irrelevant buttons in the New Project dialog

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1706]
![2024-02-18___22_33_20](https://github.com/vkbo/novelWriter/assets/60368695/1fa355a0-7f21-4bd2-b9f8-f845d1572a0d)

_Originally posted in https://github.com/vkbo/novelWriter/discussions/1699#discussioncomment-8501436_

**Comment by vkbo** [comment]
The New Project doesn't do anything when you're in the New Project page, but the Browse and Open buttons perform their actions regardless of what page is visible, so one of the two are probably sensible.

When pressing the Browse or Open button when the New Project page is active:

1. Do nothing at all. Just block the action.
2. Switch back to the Project Overview page, but don't perform the actions requested.

I think 1 is the cleanest, but 2 gives some implied feedback about why the buttons aren't doing anything.

Since the two pages are just stacked on top of each other, dropping out of the New Project page doesn't do anything to the already filled in content, so you can just press "New Project" to go back again.

**Comment by HeyMyian** [comment]
Do these buttons come with a distinct "inactive" style maybe?

**Comment by vkbo** [comment]
Not sure. Open and Cancel are standard buttons, and they are different between operating systems. These dialog button boxes are designed to integrate with the style of the host OS, so it's harder to predict how they turn out. As you've seen, disabling a button or control doesn't necessarily mean it looks inactive. The toggle switch looks inactive because I designed it, including the code that paints the different parts, and chose to make it very clear.

I think perhaps option 1 is the safest solution.

**Comment by vkbo** [comment]
Actually, it's only the Open button that needs handling. Browse has nothing to do with either page, and is a functionality all on its own, like Cancel. I think I will just block the open action when the project list isn't visible and leave it at that.
