### ISSUE TITLE
Viewer Panel: visual cue for tabs lacking content

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1719]
**The problem**

The Viewer Panel allows for plenty of useful metadata information to be tallied. But right now the user does not know at a glance which tabs (tabs? pages?) are currently containing information, and which ones aren't. They are forced to click on every single tab to “clear out” the Project's entire metadata.

**Suggested improvement**

When a tab in the Viewer Panel has no contents to show, it should be greyed out, or be disabled, or be displayed with an equivalent visual cue to signify such lack of metadata.

**Comment by vkbo** [comment]
Empty tabs are invisible, except if you run on an older Qt release, which I believe you do from an earlier conversation in #1609.

In other words, this is already implemented. Just upgrade your Ubuntu release!

Qt5 releases will soon no longer be supported due to numerous issues that Qt will not fix because they have moved on to Qt6.

**Comment by tmarplatt** [comment]
> Just upgrade your Ubuntu release!

I've been postponing that, yeah...
