### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by alemvigh** [vkbo/novelWriter#1735]
Being able to set the paragraph spacing would be helpful since it makes the document easier to read while writing, without  having to insert a blank line between each paragraph.

https://github.com/vkbo/novelWriter/issues/654 seems to indicate that this is unlikely to be implemented any time soon, but having it on the roadmap if Qt eventually allows for it without performance degradation or other breakage would be nice.

**Comment by vkbo** [comment]
Setting paragraph spacing would not help mitigate this issue, because the blank line is a part of the plain text syntax, and not merely for visualisation. This is based on Markdown, but this is also how LaTeX works. This will not change, and in fact cannot be changed.

I have a long term project of making a rich text editor with otherwise the same functionality as novelWriter, but I currently don't have time for a new project of this scope, so progress is very slow.

As for the line spacing, Qt chose not to make this a text option, and with the current plain text editor it is not possible. Even setting it on a per-line basis will have no effect since the layout engine simply ignores line height completely. But as mentioned in that ticket, it is kept open in case it becomes possible in te future.

**Comment by vkbo** [comment]
To clarify, it would be possible to add an option to treat single line breaks as paragraph breaks, but that would make the editor practically unreadable as the spacing cannot be changed. Each text block can have a margin, but as with line spacing, for the plain text layout, this settings is ignored. You'll just end up with a wall of text.

In my other project, I do use a rich text editor as the core editor, and there I have much more flexibility.
