### ISSUE TITLE
Wrong error when opening nonexistent project

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1737]
I created and deleted a test project. When trying to open this test project from the list, the error says:

> Not a known project file format.

I think the correct error should be one of these strings?

> Project file not found.
The project path is not reachable.

It would also be great to return to the Welcome screen when the opening of a project fails. Chances are I want to try again.

**Comment by vkbo** [comment]
The error type is correct. The text is just misleading. It's a generic error caused by the folder missing the project file because you deleted the parent folder. The result is that novelWriter doesn't recognise the project format (i.e. the folder structure). The error was actually added for the case of single file projects, which hasn't been released yet, but I'll swap it with a more sensible error type.

As for the Welcome dialog, this happens after the Welcome dialog has done its work and returned the selected path to the main GUI, so it is already closed. I'll look into if it can be reopened. It is of course available from the Project menu still.

**Comment by vkbo** [comment]
#1740 adds a check after the path returned from the Welcome dialog has been processed by the main app. If the process does not result in an open project (assuming one was not already open), the Welcome dialog pops up again.
