### ISSUE TITLE
Is there any chance we could get a different date format?

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1739]
Every time I see `03/09/24` I must perform extreme mental acrobatics to understand what it means, if at all x(

I personally am in favor of `2024-03-09`, but maybe there is a way to get this format from the operating system?

**Comment by vkbo** [comment]
All dates presented on the GUI uses the local format, so if you get the `03/09/24` format, it means the local format is not accessible, that is, it's read as `None` by Python. This is likely a problem with your setup. novelWriter makes no decisions on date and time formatting. I would never willingly default to a US date format, I can assure you. 😄 

![image](https://github.com/vkbo/novelWriter/assets/1619840/64953715-62a4-49ec-aba8-b947c29346c3)

See the [Python docs](https://docs.python.org/3.11/library/datetime.html#strftime-and-strptime-format-codes).

Maybe there is a way to change the fallback format. I have never encountered a case where Python cannot figure out the local format. On what platform are you running novelWriter now? And how is it installed?

**Comment by vkbo** [comment]
I know I can set the C locale from Python, I have so far just avoided messing with this as it may cause other problems. Using system settings made more sense to me, at least as long as it works. So I am curious to know why it is not working on your setup.

**Comment by HeyMyian** [comment]
This happens in KDE Neon with the AppImage as well as in Windows. The system language for both is en_US. Time locale is `en_SE` in Linux and "English (Germany)" in Windows, neither of which should result in `mm-dd-yy`. 

The screenshots on Crowdin also show `mm-dd-yy`, is that what you use?

**Comment by vkbo** [comment]
So, this boils down to what Python does then. It seems to be pulling the system language setting, which is also what the docs seem to indicate. That may be why you're getting US format, and not that it isn't finding the setting (`None`).

I have all my computers set to English UK, so I get a readable date format, which is what the screenshots show too.

In either case, the issue lies outside of novelWriter, and I am a little reluctant to implement custom formatting options, because there are so many out there. But I can look into it.

**Comment by HeyMyian** [comment]
> I know I can set the C locale from Python, I have so far just avoided messing with this as it may cause other problems.

Out of curiosity, what other problems can come from using time locale?

But thanks, I understand now why it happens. I can more readily accept my suffering when I know it is of my own making 😄

**Comment by vkbo** [comment]
You should just come to your senses and switch from US English to UK English 😄 

Anyway, the problems I'm referring to is that the setting is not actually a Python setting, but something that affects the C library in the CPython threads. Changing it at runtime is not even thread safe. In addition, you can't always set the locale code directly. Sometimes you have to set `en_GB.UTF-8` or something like that to make it work. I don't fully understand the difference, neither how it affects cross-platform support. It isn't even consistent on Linux distros.

That's why I don't want to mess with it.

A possible solution is to get rid of Python datetime formatting altogether and let Qt handle it. It has its own localisation implementation that is compatible with GUI localisation.

I also use localised number formatting, which would also be affected here. Not just dates. The benefit of using the Python built-in localised formats is that they require a lot less code. Standard formatting syntax already has support for it.

**Comment by vkbo** [comment]
Ok, it wasn't so difficult, just *a lot* of stuff to change. The code in #1745 works.

The problem with this implementation is that it uses the GUI locale selected in novelWriter, and that is a very limited set of locales. If the GUI local of the system isn't available, it falls back to UK English. So in Sweden, for instance, the user would get UK date and number formats instead of Swedish.

I don't think this is optimal, so I would have to look into solutions before I decide to merge this.

**Comment by HeyMyian** [comment]
> let the user choose between a set of hard coded date formats

I'm thinking this is disproportionate if we're talking only about the dates that are currently displayed in novelWriter - to my memory only at the version check?

I remember features to display "file creation date" and "file modified date" are somewhere in the pipeline.

There seems to also be a hardcoded yyyy-mm-dd in the statistics.

**Comment by vkbo** [comment]
> I'm thinking this is disproportionate if we're talking only about the dates that are currently displayed in novelWriter - to my memory only at the version check?

It is. The only places where dates are shown are on the Manuscript preview, release dates on Welcome and About, and last opened date on Welcome.

Maybe a switch somewhere in Preferences to use ISO date format would be enough. That should solve your case where you have US English system locale and don't want US English dates.

> I remember features to display "file creation date" and "file modified date" are somewhere in the pipeline.

It was implemented a long time ago, and it shows ISO date.

> There seems to also be a hardcoded yyyy-mm-dd in the statistics.

Stats uses ISO dates. Otherwise the list cannot be sorted by date.

**Comment by HeyMyian** [comment]
>>   I remember features to display "file creation date" and "file modified date" are somewhere in the pipeline.

> It was implemented a long time ago, and it shows ISO date.

I just realized this today 😄 This is what not reading all version notes gets me!

> Maybe a switch somewhere in Preferences to use ISO date format would be enough. That should solve your case where you have US English system locale and don't want US English dates.

From my point of view, you could close this issue as "not planned" and "not a bug". I initially thought the date issue was something inherent in novelWriter and I don't want to create unnecessary fuzz.

**Comment by vkbo** [comment]
Sure, but the issue does bother me a little too. For instance, Python sets the UK English date format to `dd/mm/yy`, but I would prefer `dd/mm/yyyy` myself, so I've been considering a way to override it.

Perhaps it can be solved as simply as default to use system localisation, and add a switch in Preferences to use GUI localisation instead for dates and numbers.

**Comment by vkbo** [comment]
Ok, I've made a new and simpler attempt in #1755.

If the selected GUI locale can be loaded (the translation files are available) the dates will be formatted according to the same locale settings. If the chosen GUI locale cannot be loaded, the formatting falls back to system locale formats as Qt sees it, instead of Python.

This means that if your GUI is displayed in German, so will the date format. Regardless of system locale.
