### ISSUE TITLE
Show File Details Improvement

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1783]
Menu --> Document --> Show File Details

1. To get at all the details (the file name for example), I need an extra click on "Show Details". Why not show everything directly?
2. Consider adding "Show File Details" menu item to the Project Tree View Context Menu

**Comment by vkbo** [comment]
1. The path is deliberately hidden away to discourage editing the files directly. This was changed in #1510 as part of 2.1. There isn't really reason to do so, and editing them outside of novelWriter causes problems with the index. The created/edit dates are there because of a feature request, otherwise the dialog box would have been removed entirely.
2. I don't want to overload the context menu with options that are rarely used.
