### ISSUE TITLE
Shortcode formatting can't be toggled

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1804]
Steps to reproduce:

1. Type a word
2. Apply a format with shortcodes to the word
3. Highlight the word
4. Apply the same shortcode format again

Expected behavior:

* The shortcode formatting is removed.

Experienced behavior:

* More shortcodes of the same type around the word.

---

Slightly related:

When highlighting a word and applying a markdown format to the word, the word stays visually highlighted. Repeated use of the markdown format however merely removes the highlight without removing the format. Otherwise, toggling markdown formatting works as expected.

**Comment by vkbo** [comment]
This is not a bug at all. The toggle feature of the markdown symbols do not apply to shortcodes. They are insert-only. `Ctrl+Z` will undo the insertion.

The related issue does seem to be a bug. Could you open a separate ticket for that?

**Comment by vkbo** [comment]
To clarify: the reason why markdown codes toggle is that they only work when applied correctly and cannot be repeated, so there is code in place to ensure you cannot get duplicate markup. This does not happen with shortcodes. Double bold is still just bold, while double markdown bold is nothing. Just four asterisks.

**Comment by vkbo** [comment]
Huh. sorry for all the replies, but this got me testing a little what can and cannot be done with shortcodes.

This parses perfectly fine because shortcodes are very flexible:

![image](https://github.com/vkbo/novelWriter/assets/1619840/5f432fa7-b5eb-4e9b-aec1-398de84183b3)

However, the generated HTML cannot be rendered correctly with overlapping formats in Qt, so the viewer doesn't show "document" in italics:

![image](https://github.com/vkbo/novelWriter/assets/1619840/54755173-79dd-4a3b-99fa-0f616b39df61)

The Open Document output does handle it:

![image](https://github.com/vkbo/novelWriter/assets/1619840/127aa327-5bfb-4b29-9e8b-cf23f14b6231)

And so does Firefox, so the HTML limitation is on Qt, not general:

![image](https://github.com/vkbo/novelWriter/assets/1619840/47b063e9-559c-4312-8093-ef3db619fa11)

**Comment by HeyMyian** [comment]
> To clarify: the reason why markdown codes toggle is that they only work when applied correctly and cannot be repeated, so there is code in place to ensure you cannot get duplicate markup. This does not happen with shortcodes. Double bold is still just bold, while double markdown bold is nothing. Just four asterisks.

Thanks for clarifying that, it makes sense that `[b][b]Text[/b][/b]` is not an issue when rendering. Would you consider the proposed toggle as a QoL improvement though? I envisioned a regex check if the highlighted word is enclosed by specific shortcodes, and if the shortcodes are present, remove them.

**Comment by vkbo** [comment]
Since shortcodes can both be arbitrarily placed, nested and overlap, it is much more complicated to check for than just for markdown codes. I don't think it is worth it. The toggle feature for simple markdown, which includes three possible symbols, and only one at a time, is already quite complicated.
