### ISSUE TITLE
Global Search Enhancements

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1830]
Created an issue from earlier discussion (#1798):

- global search panel: add some preceding context in global search matches (full word or even more?)
- improve/fix automatic update of the search panel

plus suggestion:

- start search without extra click on the magnifying glass after the follwing events:
  - Ctrl+Shift+F with selected text non-empty
  - button events: case sensitive on/off, whole word on/off, regex on/off

**Comment by awqk** [comment]
> Pressing `Ctrl+Shift+F` and then `Enter` will achieve this, so I'm not sure I see the need.

1. VSCode does it. 2. It doesn't hurt. 3. I don't like pressing keys when I am not yet sure where the focus is.

> I was going to add this before the release, but didn't get around to it.

I know. What is the proper way you want to keep track of the small things? Let's say a small thing is not very important, involves only a few lines of code, and should be done some time down the road.

**Comment by vkbo** [comment]
> I know. What is the proper way you want to keep track of the small things? Let's say a small thing is not very important, involves only a few lines of code, and should be done some time down the road.

I prefer separate issues for separate features. I organise them into release milestones as tasks, so it makes it easier to throw in minor things into releases when I have the time. Small issues, even one-liners in terms of code change, is fine.

For instance, the "plus suggestions" in the original post here could be in a separate issue since they only require a line here and there to trigger a refresh in the already existing signal handlers for the button clicks.

**Comment by vkbo** [comment]
I think I managed to get it to include the whole leading word. It's a bit tricky because it has to first find the preceding line break, then preceding space. Needs some real life testing in case there are corner cases I haven't thought of yet.

![image](https://github.com/vkbo/novelWriter/assets/1619840/abba3a45-66a9-41ce-946d-c0373216b5dd)
