### ISSUE TITLE
Build Tool Preview Position

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1837]
Would it be possible to remember the preview position after an update?

During the final edits, I like to view the text with a different font and/or different line wrapping, to make errors overlooked before stand out better. After a fix, it would be nice if the preview returned to its previous position, give or take a paragraph.

To view the edits, my earlier workflow was:
- pandoc -t epub
- reload epub reader (they usually do remember the reading position)

Now it could be, less one step:
- refresh preview

... if it weren't for the need to find the reading position again.

**Comment by vkbo** [comment]
Sure, should be easy to add.

**Comment by vkbo** [comment]
The code for this was already there, but since the preview window is cleared before it is updated, the scroll bar was always at 0 when its position was recorded. So it would always restore to 0 as well.

The position is now saved before the clear() call, and restored on the same timer that hides the progress wheel. If the position is restored too early, the document hasn't finished rendering, so it may not scroll all the way. The progress bar timer is on a 300 ms delay, and that should be enough.
