### ISSUE TITLE
Status icon settings & multiple projects

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1847]
Just noticed the status icon config is part of the project settings. Especially with the upcoming new features #1810, I would want to do the setup only once, and use the same setting for all my projects.

Please consider making this a global setting, or allow import/export, or copy from other project. Maybe it is as simple as storing the settings in a separate file in the meta subdirectory, to allow manual copy between projects, and have "Rebuild Index" update the usage statistics.

**Comment by vkbo** [comment]
The already provided solution for this is to create a template project. You can create new projects from a template from the new Welcome dialog.

I'll update the documentation on this, since it is not mentioned.

**Comment by vkbo** [comment]
Also, they cannot be global. Each status/importance label is associated with a unique key. The user interface ensures you cannot delete a key that is in use. If they were global, there would be no way to check this and you will risk erasing information from other projects when you make changes.

The only safe way to handle this would be to allow for import/export. However, this too is non-trivial since you cannot clear existing status labels on import, since they are in use. How do you then consolidate the imported changes? The only option is to append them, and you have to manually go through all your documents and switch to the new ones, before you delete the old. There is no easy way to automate this, so it would require a merge tool that is a medium sized feature task a fair bit of effort to implement.

The only clean way is to use templates.

**Comment by vkbo** [comment]
Hacking the `.nwx` file is never the solution, but always a workaround, sure 😄 

Anyway, I can convert this to a feature request as an import/export implementation. But as I said, it will not be implemented in a while. There are a lot of more impactful features to work on, and I don't seem to be able to make much of a dent in the number of requests as new ones come in all the time,

I did think a bit more about how a merge tool could work. It could compare the label text and update the colour and icon settings for those that have the same name (and ignore the unique key), and add the ones that do not. It is a lot simpler, and the user can simply cancel the Project Settings dialog if it ends up a mess. The changes are not applied directly.

Incidentally, the original implementation only used the status label text as the key. But that got a bit clunky when the user renamed them as all documents using it had to be updated. That's why I switched to a random generated key in version 2.0. It's the same logic used for document file names. Disconnecting the label from the actual entry makes a lot of things easier in the code, and a lot more robust against code errors.

**Comment by awqk** [comment]
> I don't seem to be able to make much of a dent in the number of requests as new ones come in all the time

I will try to slow down a bit :smile:

**Comment by vkbo** [comment]
For now, I've implemented it in the easiest possible way: A plain export of labels to CSV, and an import feature that appends them as new labels. It's up to the user to transfer the old labels to the new ones if this is done on an active project.

It should at least make it easier to set for a new project.
