### ISSUE TITLE
More suitable sidebar icons?

### ISSUE THREAD

**Issue by zxygentoo** [vkbo/novelWriter#1855]
After a couple days of **serious** use, the sidebar icons kinda bug me a little big :joy: 

This icon set does the job, and for small size (like in project tree view) they are indeed pretty charming. At larger size however, they are kind of bold and not that visually harmonious.

Attached is a PoC comparison with some alterative icons from the [feather icons](https://feathericons.com/) which is a MIT licensed open source icon set. (And I took the liberty of rearranging some icons so they make more sense to me) 

To me this seems fit better with that overall simple clean and snappy feel of novelWriter. (In my opinion, in contrast to most open source projects, NW's UI is pretty well done for its resources, function and honesty goes a long way in design. Kudos :)

At the end of the day, these things are always subjective. So just put this out there to see if you might be open to PRs like this or not.

Cheers,
Alex

![icons-compare](https://github.com/vkbo/novelWriter/assets/811633/12070a52-0b1e-4e78-9871-4f246f8c195b)

**Comment by vkbo** [comment]
I am happy to look into a new icon theme, but I personally don't like "feather". I've looked at them before. In fact, I looked at a lot of icons before landing on Typicons. The problem is that a lot of them are limited, so I have created a bunch of icons from pieces of other Typicons. I also created all of the formatting icons from scratch, and it shows. I'm not a graphic designer after all. 😄 

Due to the number of custom icons, it would probably be best to have a dedicated icon set designed. There are no standard icon themes that cover all use cases. I hope someone one day will design a new theme for novelWriter.

In the mean time, it's perfectly possible to create your own icon and colour theme for novelWriter. It's covered in the manual under [Customisations]https://novelwriter.io/docs/more_customise.html).

**Comment by zxygentoo** [comment]
Agreed. Feather is just used as an example here. I think you did a pretty nice job here (not only the icons, the UI in general). Current icon set works quite well for daily use, the bigger sidebar icons are the only thing that's stand out for me (who is generally more on the picky side for these things).
