### ISSUE TITLE
The synopsis tag is not documented

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#186]
The %synopsis: field is not yet documented (though it's present in the sample project. But why isn't it @synopsis: like other tags?

**Comment by vkbo** [comment]
Documentation is updated on release, and when the features are complete, so just hang on a bit. I don't want to spend a lot of time rewriting documentation before I'm done.

When novelWriter is out of alpha and beta I will probably switch to a develop+master branch structure of the project, where master branch is always latest release and updated documentation.

Anyway, the synopsis feature is implemented the way we discussed in Issue #70.

The rationale is: The `synopsis:` keyword is a modifier to the comment, but it is still just a comment. The synopsis keyword just ensures the indexer captures it. All other code ignores it like other comments. The @ tags are meant for references, which is why they have the @ symbol.

**Comment by vkbo** [comment]
To avoid confusing the synopsis feature with other keywords-value structures, I could perhaps loosen the syntax. Any comment starting with the word synopsis could be parsed as a synopsis by the indexer. Meaning it could be any of the following:

```
%synopsis: Some text
% Synopsis: Some text
%    synopsis. some text
```

Would that make it more intuitive? I can easily modify the regex to handle it, and always highlight the "synopsis" word so the user knows the parser recognises it.

This seems to do the trick:
`/(^%)([ ]*)(synopsis)\b/i`

**Comment by johnblommers** [comment]
Thanks for clarifying why the synopsis is different from the tag.

My sense is that the following syntax should be seen as a synopsis:

1. `%` begins the line, followed by
1. zero or more whitespace characters, followed by
1. [Ss]ynopsis:  followed by
1. the synopsis  text which may include leading and trailing whitespace, ending with
1. newline

I wondered about multi-line a synopsis but that's pushing the idea that a synopsis be brief.

**Comment by vkbo** [comment]
The regex above will look for a `%`, any number of white space characters (zero or more), the word "synopsis" with any capitalisation, and any word ending (punctuation, space, whatever). The third group will be highlighted by the syntax highlighter.

Newline will end the synopsis, as all parsing is done by lines. As you say, multiple lines isn't really a synopsis any more, so I think restricting it to one is fine. The indexer class currently has one variable for the synopsis, and if you write two under the same header, the second will just ov erwrite the first.

**Comment by vkbo** [comment]
The restrictions on the synopsis marker has now been relaxed. As long as "synopsis:" appears as the first word in the comment, regardless of capitalisation, the comment is flagged as a synopsis comment. Added in PR #191.

Leaving the issue open until the documentation is updated.

**Comment by vkbo** [comment]
Documentation updated in PR #202
