### ISSUE TITLE
Changing “Application font size” causes “Document font size” to be ignored

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1862]
Not claiming cause and effect here, but I have reproduced this behaviour, on v2.4.1 fresh configuration and _running from source_:

- In preferences, under Document Style change your font size to something non-default, like 18 pt.
- Confirm the new document font size change in editor and viewer.
- In preferences, under Appearance, change your application font size to something non-default, like 14 pt.
- Restart novelWriter, load a project
- Editor and Viewer are now showing text in a very small font, 10 pt-ish (as opposed to the 18 pt above).
- You can force a font size “refresh” by entering the Preferences dialog and hitting “Apply” without further changes.

This does NOT reproduce when running the v2.4.1 AppImage. Font sizes are displayed as expected. 

Is this maybe another old uncool PyQt version thing? I'm on 5.15.6

**Comment by vkbo** [comment]
I cannot reproduce this from source. I'm guessing it is font-related maybe? What font are you using?

**Comment by tmarplatt** [comment]
On a fresh install (aka no `~/.config/novelwriter`) the default selected font family, for both Application and Document style, is Ubuntu. It's also the Application font I'm using on my current config.

**Comment by vkbo** [comment]
Tested again with 2.4.1 on both Ubuntu 22.04 and 24.04, and still can't reproduce the problem. I noticed that the heading font doesn't rescale when changing size (until the app is restarted), so I'll fix that at least.

**Comment by vkbo** [comment]
Ok, so ...

* Ubuntu 22.04 is running Qt 5.15.3
* Ubuntu 24.04 is running Qt 5.15.13
* My system is running Qt 5.15.8
* AppImage is running Qt 5.15.2

So, it could very well be an issue with Qt 5.15.6 maybe.

I did make a change in 2.4.1 to only set the document default font for the editor and viewer, instead of the whole panel's font (see #1842) so maybe that triggered a bug in 5.15.6. On which OS version did you encounter 5.15.6?

**Comment by tmarplatt** [comment]
> On which OS version did you encounter 5.15.6?

This is Linux Mint Cinnamon 21.3, based on Ubuntu jammy, [here is the package information](https://packages.ubuntu.com/jammy/python3-pyqt5).

**Comment by vkbo** [comment]
It's the Qt5 version that generally matters. PyQt5 is just a Python wrapper. But since I cannot reproduce the problem, it's really hard to debug. I'm guessing it's a Qt issue since none of this is actually handled by novelWriter. The setting is just forwarded to Qt.

I guess the only thing I can try is to spin up a new VM ...

**Comment by vkbo** [comment]
I've set up a Mint 21.3 VM, and can reproduce the error there, as well as #1875. I'm pretty sure what change it's related to, and I'm also pretty sure there is a Qt bug behind it, but I'll figure out a workaround.
