### ISSUE TITLE
Support for nested lists

### ISSUE THREAD

**Issue by julichan** [vkbo/novelWriter#1867]
Hello,

It would be nice to have support for multiple nested list like in the original markdown specs.
The number of spaces before a bullet would indicate the list level.

I may rarely use this feature in the story of a book itself but it can be very useful in other parts such as characters, items, plot and location items and more specifically to organize plots and characters synopsises. here is an exemple:

https://itsfoss.com/markdown-nested-lists/

Thanks,

**Comment by vkbo** [comment]
Please see the pinned issue #815 "Frequently Requested Features".

novelWriter isn't a Markdown editor, but a plain text editor that uses some Markdown syntax, as well as other syntax forms, for formatting content. There are no plans to implement full Markdown support, partially because it requires multi-line parsing, something novelWriter currently doesn't support. It only processes the text line-by-line.

Also, since the editor isn't intended to use a fixed width font, indentation as markup isn't going to work very well.

While I understand the use case, this will likely not be implemented.
