### ISSUE TITLE
Cannot double-click a heading to edit it in Outline view

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#187]
Double-clicking on a scene or chapter heading in the Outline pane could send the writer to the editor, but nothing happens. Instead the writer has to locate the corresponding heading in the Tree view and double-click it there. That's more friction.

**Comment by vkbo** [comment]
Only the core functionality is in place, but what you request is an intended feature. The double-click is currently caught, but only echoed to terminal output. I will add it very soon.

Just wanted to note that I merged the core Outline feature before everything else was added since the branch contains a major rewrite of the indexing class. It kept causing conflicts with other code and changes. I will add the rest of the features soon, and in time before I make a new release.

**Comment by vkbo** [comment]
Double-clicking the entry in the outline tree will no open the relevant document in the editor, and the editor will scroll to the title position if not at the top of the file.
