### ISSUE TITLE
In-line @tags

### ISSUE THREAD

**Issue by Totobal5** [vkbo/novelWriter#1883]
When I started using this program I realized that `@tags` cannot be used in a line with more text, but must be used in a separate line. I would like to know if you can consider the idea of being able to use `@tags` in line with more text, the tags I would like to see are the following.

1) `@char`
2) `@location`
3) `@entity`

I also think that the syntax of: `@tag: tag1, tag2` should not be allowed with inline tags.

i check for other feature-request with this idea and i not find one, i hope i am right if not i am sorry!!

**Comment by vkbo** [comment]
First of all, use backticks around @ -tags when posting here. You are actually tagging a lot of people on GitHub when you do this, and everyone's tagging the same people over and over due to the keywords in novelWriter (I'm sorry everyone who got an email now, probably for the nth time).

Firstly, to clear some common misunderstandings about tags and references. These you mention are references, not tags, as they are defined in the documentation. The tag is the target of the reference, set with `@tag`. The expectations of inline tags is usually down to a misunderstanding of what tags are in novelWriter, and people think of social media post tags instead. 

Now, onto the point. What syntax would you use for inline references then? You haven't mentioned that. Since the text *is* the text that actually goes into the novel, injecting syntax into it comes with a lot of parsing rules on how to convert them to the final text. How exactly do you envision that working here?

The logic behind the current system is to keep the meta data separate from the text, hence the tags are on the same line. You can use them anywhere in the document, so they can be next to the paragraph where you first mention the person or object you want to reference, so there isn't much of a problem keeping it close to the source if that is what you wish.
