### ISSUE TITLE
View unsaved document

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1884]
Opening a view to an unsaved document doesn't show latest changes, see also #1835.

**Comment by vkbo** [comment]
Since the viewer isn't intended as a preview, it does not automatically update with the editor if displaying the same document. However, if you do look at the same document, it is assumed you are doing this so you can see the difference between what you're editing and what it was before. If you press `Ctrl+R` in the editor, it will update.

This is intentional, and not a bug or missing feature.

**Comment by vkbo** [comment]
On second thought, maybe I misunderstood this request? If so, please clarify and I'll reopen if relevant.

**Comment by awqk** [comment]
> Since the viewer isn't intended as a preview, it does not automatically update with the editor if displaying the same document. However, if you do look at the same document, it is assumed you are doing this so you can see the difference between what you're editing and what it was before. If you press `Ctrl+R` in the editor, it will update.

I am thinking this might be a bit of hit-and-miss. When opening, you don't know if auto-save has already overwritten the earlier version you may want to view, therefore, nw should display the latest version. Once the view panel is open, it shouldn't update automatically, as you said.

**Comment by vkbo** [comment]
I reopened this as requested. I'll add a check that saves the editor before opening the same document in the viewer, but only in this specific case.
