### ISSUE TITLE
Characters do not show up in outline view column

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1887]
What I did:
1) Created a chapter
2) Created a character note with tag.
3) Added character tag in the chapter document.
4) Switch to outline view.

Expected result:
The character name shows up in the character column with the relevant document in the outline view.

Actual result:
The character name did not show up in the character column with the relevant document in the outline view.

Note:
The character name _did_ show up in the "reference tags" panel.

Workaround:
restart NovelWriter. Character name will be there in the character column in outline view.

Relevant info:
NovelWriter 2.4.3
Qt 5.15.3
Linux Mint 21.3

**Comment by vkbo** [comment]
The new meta data for the chapter (the character you added) is not scanned before the document is saved. You can either click `Ctrl+S` or wait until the autosave timer kicks in. By default it is 30 seconds, but you can change that in Preferences,

I cannot see that there is a bug here other than that you didn't give it enough time to update. Please confirm.

**Comment by xahodo** [comment]
I tried this with a second character (however, in the same chapter). Both the chapter file and character file were specifically saved (ctrl+s). The second character only showed up in the outline view only after a restart nw.

I tested with one character, it behaved as it should. Thinks go wonky with two characters, apparently. Whether the second character is referenced in the same document or a new one does not seem to matter (at least, this is the behavior I am getting). The second document and character have both been saved.

**Comment by vkbo** [comment]
I tested with three characters, so it isn't that. Maybe something else is going on.

Keep in mind that the outline doesn't auto-refresh. It refreshes only when you switch to it, so staying there looking at it will do nothing. There is a refresh button in the toolbar for manually refreshing it. Restarting novelWriter is not necessary in any case.

The way it refreshes can maybe be improved, but the reason it doesn't do it all the time is that it isn't very efficient because it assembles a lot of data for a big project. That's why there is a manual refresh button there.

**Comment by xahodo** [comment]
I checked some more and followed your suggestions.

I was wrong, the refresh button fixed everything. I apologize for any inconvenience I may have caused with this issue.

**Comment by vkbo** [comment]
Oh, that's perfectly fine. Don't worry about that 😃 

At least there is no bug, so I'll close it. I'm planning to look into how it refreshes. The references panel uses a more dynamic refresh method that just updates changed lines.
