### ISSUE TITLE
Setting a default writing project directory

### ISSUE THREAD

**Issue by paulkater** [vkbo/novelWriter#1930]
Maybe I am overlooking something in the settings, but I would like to set a default writing project directory somewhere.
For backups, there's a setting where to put the backups, which is awesome. I put all my writing in a specific directory, but when starting a new project, the default is my home directory. The 'browse' option, in the project selection window, seems to remember the last-used directory, which (for me) would also be a candidate for that default project directory.

Thank you for considering this idea.

**Comment by vkbo** [comment]
novelWriter stores the last used directory for some things, but not everything. I'm not very happy with how that is implemented, so I'm thinking about having it remember last directory for each tool that needs a local path, and have them all default to home on first use. That way, each tool will always suggest the last use directory.

This is less user effort than having to go into Preferences and set a path. It also has the benefit of remembering all of them separately.

The backup setting will of course remain since it is an automated feature.

**Comment by paulkater** [comment]
That's a lot better than my idea. Awesome. Thank you!
