### ISSUE TITLE
Path names contain square characters

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#194]
I like the option to include the path to each document. Is my system missing a system font or am I seeing artistic license? The path separator is a rectangle, as if there is font substitution going on. I've attached a screenshot to illustrate.

![NW](https://user-images.githubusercontent.com/8484427/80927458-e6f6f380-8d52-11ea-80dc-2cf32e2dd71f.png)

**Comment by vkbo** [comment]
It's the unicode character for right-pointing triangle. Evidently it doesn't exist in all fonts. I checked a bunch of standard fonts, but it is clearly missing in your system font. I didn't want to use the `/` character because there is nothing that disallows slash in document titles, and for a Windows user it may be counter-intuitive as Windows uses `\`.

I will find a way to solve this.

**Comment by vkbo** [comment]
Follow up question: Does the checkmark and cross show up on the switches on your desktop, like in the below image?
![image](https://user-images.githubusercontent.com/1619840/80942883-32a6ad00-8de6-11ea-9f46-1033e5ded5a1.png)

**Comment by vkbo** [comment]
Just had a quick look at the unicode character used, and it isn't the standard triangle character. I will replace it with what seems to be the correct one, and update the header later tonight. Most likely it will render properly then. I also forced the use of the HTML entity rather than the pure unicode, so your local Qt library may then try to replace it with an equivalent as well.

**Comment by johnblommers** [comment]
The check mark and cross characters do appear correctly on my system.

**Comment by vkbo** [comment]
Great! I just merged the fix for the missing unicode character, and this should now be fixed. I replaced it with the `›` character.
