### ISSUE TITLE
Please provide a 32bit version

### ISSUE THREAD

**Issue by starFaith2007** [vkbo/novelWriter#1945]
The 32bit version is really important for people like me who like to write with older devices, thank you

**Comment by vkbo** [comment]
For which platform?

**Comment by starFaith2007** [comment]
> For which platform?
windows 32bit,thank you

**Comment by vkbo** [comment]
Still need more info. What Windows version?

**Comment by vkbo** [comment]
As detailed in the issue template you saw when you created the request, it is really important that you provide the details of what you are asking for. It is extremely rare a one-liner is enough for a feature request.

It may also be helpful to know what device we're talking about. It is already a lot of work providing all the packages, and I don't have the capacity to support very narrow use cases.

novelWriter itself is both platform and architecture independent. As long as there is a working Python environment with PyQt5 installed, you can simply run `pip install novelwriter` and you should have it up and running. Spell checking may or may not work, as it is a little more restricted.

**Comment by starFaith2007** [comment]
Sorry for this late reply, there was a problem with my email and it didn't alert me to your inquiry.
The Win version is:Windows 10 Enterprise LTSC 2016

**Comment by vkbo** [comment]
Sure. Just needed to know whether it was anything older than Win 10, which isn't supported. Since Win 10 is the last that comes in 32 bit, and I'm having a ton of problems making these Windows installers, I'll haven't yet decided whether it's worth it. As mentioned, it you install Python 32 bit, you can install novelWriter with `pip install novelwriter` as a Python package. The only difference is that you don't get the launcher icon on the desktop.

**Comment by hifron** [comment]
Today's tools are not anymore tested on 32bit platforms and if installer(somehow) could be made then it will be untested. If there is need for some purpose(because LTSC may have much longer support than the end of next year) custom packaging(maybe somehow easy to use) may be proper but as said it could be untested and then support request or issues could be or not could be filled or use other software in this large space(especially on Windows).

**Comment by vkbo** [comment]
I've been looking into this a bit. It seems that neither Qt6 nor PyQt6 is officially released as 32 bit. Since novelWriter will be switching to Qt6 soon, any 32 bit support will be short-lived. I don't think it is worth the effort.

As novelWriter has no architecture requirements on its own, as it is pure Python, it can run just fine on 32 bit from the official PyPi package as long as there exist 32 bit versions of its dependencies and Python itself, as already mentioned. So it is still possible to use ... for now.

I'm not sure when the switch to Qt6 will arrive, but the only thing holding it back now is support for older Ubuntu LTS releases. However, since there are unfixed bugs in Qt5 that keep causing issues, switching to Qt6 may come soon regardless, as the latest Ubuntu LTS does support PyQt6.
