### ISSUE TITLE
"Go to Tree View" unresponsive the first time when invoked from Outline

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1949]
Noticed in 2.5rc1

To finish up the German translation, I tried to figure out what the updated string "Go to Tree View" does. I'm not sure I'm seeing the desired behavior here, it seems a little weird to me. Reproduce:

1. Open a project
2. View -> Go to Outline
3. View -> Go to Tree View

### Expected
Go to Tree View. I assume this means "focus the left panel and/or toggle the left panel between **Project Content** and **Outline of Novel**"?

### Observed
Nothing changes. Only invoking "Go to Tree View" another time has the expected effect.

Maybe I'm misunderstanding what these functions do? Does the "Outline" (without the left side panel) qualify as a kind of "tree view"?

**Comment by vkbo** [comment]
No, you're right in what you expect. Sine it is a toggle effect, it will first focus then toggle. However, that may misfire when it's in Outline view because even though the tree view is visually hidden, the project tree view is on top and thus "visible" in the stack of project, novel and search as far as the code is concerned.

Should be easy enough to fix,
