### ISSUE TITLE
UI: some elements in settings don't react to appearance change

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1951]
Here I switched from "Dracula" color theme to "Default Dark Theme" and some pink color from Dracula remains. Closing and re-opening the settings will show the correct colors, but considering that all other colors update immediately on theme change, this looks like an oversight?

The pink text also doesn't seem to immediately react to a change in application font size.

![Screenshot_20240630_114434](https://github.com/vkbo/novelWriter/assets/60368695/0e53c628-542c-4717-be4e-41e100febbdc)

**Comment by vkbo** [comment]
Only the main UI is updated when you change theme, not the dialog boxes. Most of them still do change due to the underlying Qt framework having its settings updated, but some text elements have novelWriter specific colour settings, like the help label text. These do not change without a restart. Neither does window border and a few other things. It will never be a complete update without a full restart of the app. Changing font is also incomplete and needs a restart. There is a dialog box that pops up about this, and it says right there that it "Requires restart to take effect".

It has always been like this, so it is nothing new. There just haven't been any UI themes where the difference is this obvious before.

The only way around it is to write a ton of code that goes and updates every single custom item, which will still not fix it all. The only clean and complete update comes with a restart.

**Comment by vkbo** [comment]
I'm re-opening this. I changed the header labels of the editor and viewer to use this same coloured help text label, and those do need to be updated on theme change. They don't have this feature, so I need to add it. The editor and viewer already have dedicated theme update methods, so in this case it's a straight forward fix.
