### ISSUE TITLE
Build Tool Preview Indent

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1961]
The first line indent em size doesn't add up in the Preview.

AFAICT 3.0em should be equal to 0.5in for a 12pt font, assuming an em size of 16px.
Right now (2.5RC1) it looks like it's twice as much.

Line spacing em looks accurate.

**Comment by vkbo** [comment]
Yes, it seems you're right. The preview document class was using the font height, not the font ascent, as the reference unit. It also meant that headings were slightly larger than intended.

The Open Document export is correct, as it uses the font point size and 72 DPI for the calculation, and outputs everything to the document in metric units (cm).

**Comment by vkbo** [comment]
It's only about 25% too big though. Here are the numbers:

```
Point Size: 12.0
Height: 20.0
Ascent: 16.0
Descent: 4.0
```

**Comment by awqk** [comment]
It's confusing stuff, are we talking px or pt here? Compared to libreoffice build output it has to be more than 25%.

My guess is you should be using the font size, in this case 12pt and not 16px.

This also fits numbers floated a lot around the Internet where a point is 4/3 of a pixel, and the em of a 12pt font is 1/6in.

**Comment by awqk** [comment]
Actually, I was confused, it's only slightly off, which might fit 25%

**Comment by vkbo** [comment]
The preview is in pixels, so I have to calculate it in pixels. For a 12 pt font, 1 em is 16 px. Screen pt to px is by convention 72/96 at 1.0 scale (and more for high DPI screens). I use this calculation to match icon size to GUI font size.

Open Document is in physical units based on the pt, and pt are by convention 72 DPI, so the calculation is that 1 em is `12/72*2.54` to get cm for the output. Drop the 2.54 factor for inches. So I'm confident the ODT file is correct (I checked the XML as mentioned), and by the screenshot above, the preview matches pretty closely. The small difference can easily be down to font kerning,

**Comment by vkbo** [comment]
My 25% comes from 20px/16px (for a 12 pt font). That is, height/ascent. Ascent is the correct value for em, but I was using height in the code. So I'm confident my math is correct now. I've spent a lot of time researching this in the past, especially in relation to high DPI screens, so I know all the factors.

There is still no guarantee the output will be identical in terms of where the indent aligns with the characters on the next line. There is a clear, but small, difference in my screenshot too. This is down to the layout engines that draws the characters. The preview uses the Qt engine, which doesn't necessarily match the Libre Office one, which may not match the browser for HTML output. It could be due to pixel round off, font kerning, etc. It's beyond the control of novelWriter anyway.
