### ISSUE TITLE
Build Tool: Indent First Paragraph

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1965]
What's this setting supposed to do?

I don't see a difference in the preview (2.5 RC1).

**Comment by vkbo** [comment]
Please use discussions to ask questions.

But to answer it, it also enables first line indentation for the first paragraph in a new section. This is not commonly done in English, but apparently it is in for instance Chinese (according to the feature request).

**Comment by awqk** [comment]
```
#! title

### first scene

the first line of this paragraph is always indented, even with indent first paragraph disabled.

```

**Comment by vkbo** [comment]
Ok?

![image](https://github.com/vkbo/novelWriter/assets/1619840/19d771cb-a137-468a-9313-ec2e8268fdeb)

**Comment by vkbo** [comment]
Also, if it was a bug report, please say so. It didn't look like it was.

**Comment by awqk** [comment]
![gnome-shell-screenshot-36q7cy](https://github.com/vkbo/novelWriter/assets/160403624/9584b028-f407-44c6-bc38-8a0e0ca51e40)

**Comment by awqk** [comment]
Ok, it works while in the same file, it doesn't when there are different files.

Didn't know what to expect, hence no bug report.

**Comment by vkbo** [comment]
Yes, so it is not the example you posted, which worked just fine. You've found some corner case, which is indeed a bug report.

**Comment by vkbo** [comment]
Since each document is processed separately, there may be some unexpected variable reset somewhere. It does work if you add a second scene though.

**Comment by awqk** [comment]
Sorry, didn't expect my example would work, so next time, I will test before posting.

**Comment by vkbo** [comment]
Ah, I see what is happening. The indentation is added in the second parsing pass, while headings are parsed on the first pass. So when the scene title is hidden and at the top of a file, the title entry, which disables the indentation, is not present on the second pass, so it defaults to indent if indentation is otherwise enabled.

If you turn on titles for scenes, it works as expected. In the single file case, the indentation is switched off due to the `#! Ttile` part, not the `### Scene` heading.

![image](https://github.com/vkbo/novelWriter/assets/1619840/2670769b-bc75-4f08-a0ed-f4122f249615)
