### ISSUE TITLE
Modify build tool to support heading formatting

### ISSUE THREAD

**Issue by cakenggt** [vkbo/novelWriter#2023]
Many authors, when submitting their novels, do so in [Shunn Modern Manuscript Formatting](https://www.shunn.net/format/novel/). Currently the build tool in novelWriter does not allow certain aspects of this formatting to be implemented, leaving those features as an exercise to the writer to add in after export. These features are:

* The title page's top-left contact information and address
* The title page's bottom word-count
* Unstyled chapter headings
* Vertical space above each chapter heading

**Comment by vkbo** [comment]
The problem is that there are many formatting standards, and supporting them explicitly is not planned simply because it is a big can of worms. novelWriter also lacks the formatting capabilities for some of these standards.

The best general solution for title pages is to create your own cover page template and use that. See @peter88213's answer in this discussion for more details: https://github.com/vkbo/novelWriter/discussions/1975#discussioncomment-10044454

See also the LibreOffice docs on [Working with Master Documents and Subdocuments](https://help.libreoffice.org/latest/lo/text/swriter/guide/globaldoc_howtos.html).

> * The title page's top-left contact information and address

I'm not sure why this cannot be achieved already. You can add this to your first page of the project if you wish. You can also insert spacing to push the title further down on the page after the address using `[VSPACE:5]` for 5 lines, or whatever other number you want. See the documentation on [Vertical Space and Page Breaks](https://novelwriter.io/docs/usage_format.html#vertical-space-and-page-breaks) for more details.

> * The title page's bottom word-count

This is indeed not possible. I've considered adding a way to insert certain variables into the text. I think that belongs in a separate feature request. I'll make one and reference this ticket.

> * Unstyled chapter headings
> * Vertical space above each chapter heading

Your last two points are features that can definitely be added to the build tool. The "Additional Styling" section for Headings could add more options. There are already internal settings in the build system to adjust header margins, but they aren't currently exposed to the user. It is fairly easy to add settings for that.

**Comment by vkbo** [comment]
Added #2024 to cover the word count point. This ticket will cover the heading formatting request.

**Comment by cakenggt** [comment]
Thank you @vkbo for your detailed reply!

As for the left-aligned contact information, perhaps I am misunderstanding the title page format, but when I input the following into the title page, the build output has the contact information on the first page alone, and then the title on the second page, whereas I imagined they would be on the same page together.

```
firstName lastName <<
addressLine1
addressLine2

#! storyTitle
```

**Comment by vkbo** [comment]
Yes, if you use the `#! Title` format for the manuscript title, it will add a page break before the title. You don't have to use `#!` though. You could just to `>> Story Title <<`, or `>> **Story Title** <<` if you want it in bold.

I can add an option to drop the page break before the novel title as well in Build Settings > Headings.

**Comment by vkbo** [comment]
The following changes have been made to the Manuscript Build tool:

* Add a set of centre and page break switches also to top level titles.
* Generalises the "ODT Documents" section to "Document Options":
  * Change the colour switch option to only apply to headings (this will be needed in the future)
  * Add a switch to disable font scaling of headings, meaning they're the same size as the text.
  * Add a switch to toggle bold font weight on headings.
* The "Document Options" switches now also apply to the preview.

**Comment by vkbo** [comment]
With the changes about to be added in #2073, the Manuscript tool can generate a cover page like this, which will be included in the sample project.

![image](https://github.com/user-attachments/assets/691659c7-2c0a-4fbb-b530-8ea4ece566dd)
