### ISSUE TITLE
Auto-indent pragraphs in the editor

### ISSUE THREAD

**Issue by Siriiiiitr** [vkbo/novelWriter#2143]
I am a novel writer from China, thanks to the author for his contribution
I need a function "two spaces for the first line indentation", in China, all paragraphs need to have two spaces on the first line
My novel is published on the Internet, I usually don't use the print function, I noticed that there is a function of first line indentation when printing, but I usually don't need it, when I finish a chapter, I will directly copy the article to the Internet
So I hope that when I press the enter key to enter the next line, it can automatically type two spaces, or maybe there is a plug-in that I don't know about that has already completed this function? Please let me know, thank you very much for the author's contribution again!

**Comment by Siriiiiitr** [comment]
![捕获](https://github.com/user-attachments/assets/abf2f321-7da9-4e52-ab8b-f5a55a246ae6)

like this

**Comment by Siriiiiitr** [comment]
![捕获](https://github.com/user-attachments/assets/ca388967-b9e6-49d7-ae74-795543f0077b)

like this

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the keyPressEvent method in GuiDocEditor to automatically insert two spaces at the beginning of a new paragraph when the Enter key is pressed. This change addresses the request for automatic indentation in Chinese writing style.

You can review changes in this commit: https://github.com/jacks-sam1010/vkbo-novelWriter-2143/commit/eeee5cc2ba1e5654b808a85d29a60e2cd43e76bc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Siriiiiitr** [comment]
Thanks for your reply.
I don't know if I understand you correctly, are you saying that you are working on solving this problem?
when can I expect to see the new version?
Thanks again for your reply

**Comment by Siriiiiitr** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modify the keyPressEvent method in GuiDocEditor to automatically insert two spaces at the beginning of a new paragraph when the Enter key is pressed. This change addresses the request for automatic indentation in Chinese writing style.
> 
> You can review changes in this commit: [jacks-sam1010@eeee5cc](https://github.com/jacks-sam1010/vkbo-novelWriter-2143/commit/eeee5cc2ba1e5654b808a85d29a60e2cd43e76bc).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.


Thanks for your reply.
I don't know if I understand you correctly, are you saying that you are working on solving this problem?
when can I expect to see the new version?
Thanks again for your reply

**Comment by Siriiiiitr** [comment]
I'm really sorry, I'm not a programmer, I can't understand the code... and I don't speak English... I use Google Translate... I don't even use github, but I signed up for this software because it's worth it, your software is really great.
Thanks again for your contribution

**Comment by vkbo** [comment]
Hi, I'm the author of this application. The AI-generated solution presented here is not a usable solution and will not be implemented.

As for the request, novelWriter is a plain text editor, and this kind of formatting is not applied in the editor itself, but when you run the manuscript build. Even if you self-publish, I recommend using it as it is where all of the formatting is applied. You can also generate Markdown documents there.

There is also a second reason why this cannot be implemented as suggested. In order to start a new paragraph, you need a blank line, A single line break is not enough. Thus you cannot auto-insert spaces on enter key presses without first knowing what the intention of the line break is, so this would require a number of checks on when to add the breaks. It can of course be done with more elaborate code, but as I mentioned, the editor is really not the correct place to apply this sort of layout formatting.

**Comment by vkbo** [comment]
@jacks-sam1010 Please *do not* make a pull request with that code. It is not usable for the feature request, it introduces two bugs, and leaves redundant code. This is a horrible solution, and I don't want this kind of AI spam on my repo. I have a very low threshold for blocking this sort of stuff, so be warned.

**Comment by Siriiiiitr** [comment]
> Hi, I'm the author of this application. The AI-generated solution presented here is not a usable solution and will not be implemented.
> 
> As for the request, novelWriter is a plain text editor, and this kind of formatting is not applied in the editor itself, but when you run the manuscript build. Even if you self-publish, I recommend using it, as it is where all of the formatting is applied. You can also generate Markdown documents there.
> 
> There is also a second reason why this cannot be implemented as suggested. In order to start a new paragraph, you need a blank line. A single line break is not enough. Thus you cannot auto-insert spaces on enter key presses without first knowing what the intention of the line break is, so this would require a number of checks on when to add the breaks. It can of course be done with more elaborate code, but as I mentioned, the editor is really not the correct place to apply this sort of layout formatting.

Thank you very much for your reply.
It sounds like you are not willing to add this feature...Im so said for hear that.
Because I had to give up this excellent software. Every time I repeatedly enter a space, it will increase the number of times I use my fingers. In China, we type about 50K times a day on the keyboard. Every extra keystroke is a burden.
A space is only about 1/3 of a Chinese character, so we need to type 6 spaces to leave two characters.
But I have a different opinion on your second statement. The feature you mentioned does not need to be that complicated.
In China, almost all novel software has this simple function, because each of our paragraphs must leave a two-character space at the beginning, but some people do not like to leave a two-character space.
So the developer gave us an option in the software options. Whenever we use the Enter key to wrap a line, we can choose whether to leave two characters, instead of forcing the Enter key to enter two characters every time.
But even though we have so many software, I still chose the software you developed, because all our software needs to be connected to the Internet. 
Although I have to give up this software, I hope you can continue to keep this feature without cloud functions and Internet connection.
Maybe you can really consider this simple function, which may greatly increase the use of Chinese authors.
I have tried about 20 novel writing software, and your software is ranked second in terms of overall level. Another one has a bad networking function and was exposed to steal other people's works.
Thanks again for your contribution and reply

**Comment by vkbo** [comment]
> Thank you very much for your reply. It sounds like you are not willing to add this feature... [...] Maybe you can really consider this simple function, which may greatly increase the use of Chinese authors.

What I'm saying is that the Chinese indent rule has already been implemented in the Manuscript tool. This is by request from Chinese users. I'm happy to add features for Chinese, as for other languages, and I have done so many times. But they must be added in the correct place.

What I'm saying is that the editor is the wrong place to add this feature. It uses Markdown style paragraphs with an empty line between each paragraph, and no indentation. This is the wrong place to add the indentation you want. The editor is plain text, without formatting.

> The feature you mentioned does not need to be that complicated.

No, but it needs to work with other features. If spaces are added to titles, keywords and comments, these will not work. The editor does not expect lines to be indented in the editor. It is designed that way because it is based on Markdown. Indentation in Markdown is used for quotes, code sections and lists. Not for the purpose you request.

**Comment by vkbo** [comment]
I'm closing this since the feature requested already exists in the Manuscript tool, and adding this type of formatting to the editor is not appropriate. English also uses this type of indentation, but the editor requires blank lines for paragraph breaks as mentioned, so similar requests have been rejected before also for English.

The indentation is not necessary for the writing process itself, and the content in the editor is not generally suitable for copy/paste as a final formatted text. Adding such a feature with break with the intended usage of novelWriter.
