### ISSUE TITLE
Project Tree View Set Folder Status (2.6b2)

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#2145]
"Set Status to" in the right-click context menu does not work for folders any more.

It's not doing anything, no error message.

Likewise: "Set Importance to".

**Comment by vkbo** [comment]
Confirmed. Thanks! I'll look into it.

**Comment by vkbo** [comment]
Fixed in main for RC 1. I have no idea why, but apparently I added a check in the code that only applies the status/importance values to project items of type "FILE". I've removed those checks.

For multi-selections, setting the status for folders should still work in Beta 2, if you're actively testing with the Beta 2 release. The RC1 release will not be out for a few weeks.
