### ISSUE TITLE
System requirements cannot be met with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#243]
According to novelWriter's GitHub page:

> It is recommended that novelWriter runs with Qt 5.9 or later, and Python 3.6 or later. Running with Qt as low as 5.2.1 and Python 3.4.3 has been tested, and worked in the past, but there are no guarantees that this will keep working as these are not a part of the test builds.

On an up-to-date Ubuntu 16.04 LTS system Python3 is at version 3.5.2 and Qt is at version 5.5.1. novelWriter will launch but upon pressing F5 nothing happens in the GUI and in the console we read:

```
 Traceback (most recent call last):
  File "/home/johnb/Applications/novelWriter/nw/guimain.py", line 761, in buildProjectDialog
    dlgExport = GuiBuildNovel(self, self.theProject)
  File "/home/johnb/Applications/novelWriter/nw/gui/build.py", line 257, in __init__
    self.saveODT = QAction("Open Document (.odt)")
TypeError: arguments did not match any overloaded call:
  QAction(QObject): argument 1 has unexpected type 'str'
  QAction(str, QObject): not enough arguments
  QAction(QIcon, str, QObject): argument 1 has unexpected type 'str'
```

My guess is that it's Qt related. Thoughts?

**Update**: Ubuntu 18.04 meets the novelWriter system requirements because it has Qt 5.9.5 and Python 3.6.9. And novelWriter works fine there. (Tested that in a VM).

**Comment by vkbo** [comment]
Yes, it's Qt-related.

novelWriter is using a number of features that have been implemented during the life time of Qt5. As stated, the lowest version I've tested with is 5.2.1. I handle this by saving the version number of Qt in a variable, and check for it whenever I use a feature that was added after Qt 5.0. Usually check the Qt documentation for "added in Qt 5.x" something something, and then add a workaround to the code.

During development, and automatic testing, Qt 5.12 or higher is used, so if the version added information is missing or hard to find in the documentation, I may miss it. That is the case here. The QAction constructor fails as there is no option option to omit the parent variable prior to Qt 5.7. That information is buried in one of the three contructor descriptions: https://doc.qt.io/qt-5/qaction.html#QAction-2

It is easily fixed by just passing a parent to it, so I'll get on that.

The Travis-CI builds currently run on Ubuntu 18.04 with Python 3.6, 3.7 and 3.8. Older versions are not regularly tested, which is why there is no guarantee the compatibility will remain. Especially with pre Python 3.6 versions because there were some significant changes in 3.6. One of the key ones is that dictionary keys now retain the order in which they were added, as opposed to before where they were ordered by the hash of the key. This has major implications for how the project structure is stored in memory, since each project tree item is a key in a Python dictionary. If you load the child element before the parent element, it fails to reconstruct the project tree. There's a fairly convoluted function in the NWProject class that sorts this out though, and I'm still trying to avoid depending on dictionary key order in new code, but it can be a bit tedious at times.

I will try to retain Ubuntu 16.04 compatibility until end of life next year though.

**Comment by vkbo** [comment]
Fixed and tested on Ubuntu 16.04

**Comment by johnblommers** [comment]
One of my computers remains on Ubuntu 16.04 LTS specifically for testing purposes. IMHO code tends to become more robust the more platforms it can run on. And as you noted, Ubuntu 16.04 LTS is still under active support until April of 2021, so it's the right thing to do. However I tend to keep my systems more or less current. He says, as he's still running Ubuntu 19.10 on his main rig.

**Comment by vkbo** [comment]
Ubuntu having a 5 year LTS without upgrading libraries much is not something I feel I must support, despite their LTS claim. Especially when they stay on Python 3.5.x which is quite outdated and that novelWriter no longer officially supports. Python 3.6 is a "soft" lower limit due to testing, but as long as it is minimal effort to keep it working on 3.4 and 4.5, I can make fixes for it. I have lots of virtual machines with the last 5 LTS releases of Ubuntu, so I can still check that it runs. 12.04 is definitely gone (has Qt4), 14.04 worked last time I checked.
