### ISSUE TITLE
Unclear help in Build Novel Project dialog

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#250]
The help reads:

> ## Build Overrides
>
> **Novel Outline Mode**: This option will build an outline version of the novel rather than the full thing. It overrides the title format settings without changing them. Each title will be written out, and the synopsis text will appear instead of the body text of the files. Some of the other options are still available in Outline Mode. 

But there isn't any section entitled Build Overrides or Novel Outline Mode.

My guess is that this is intended to suggest the following preset to generate an outline with just the headings and the synopsis, a very handy thing:

- Include synopsis &check;
- Include comments &cross;
- Include keywords &cross;
- Include novel files &check;
- Include note files &cross;
- Ignore export flag &cross;
- Exclude body text &check;

**Comment by vkbo** [comment]
That's correct. It was in there when I wrote that text, but I actually removed that option because it hard coded a bunch of settings that I myself wanted to tweak when I wanted to use it on a real project. Instead, I made the Exclude body text option so you could make your outline with whatever meta data and comments you wanted.

I'll update this too in PR #249, and at the same time add all the title formatting codes into a tool tip.

**Comment by vkbo** [comment]
I decided to remove the help button and text. It isn't consistent with how help is provided elsewhere, which is mainly through tooltips. I've instead written tooltips that explain how each field or switch is used.
