### ISSUE TITLE
Why are there pound signs in Outline View

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#296]
In the Outline View the name of each heading has a single # sign in front of it.

Why is it there?

![Screenshot at 2020-06-07 16-45-24](https://user-images.githubusercontent.com/8484427/83982850-b15ba200-a8de-11ea-851e-3de42559ac22.png)

**Comment by vkbo** [comment]
It's an icon indicating that this is a title, and the second column is a file.

I've always added the # symbol in front of these headings to indicate that they are headings. It just took me a bit longer to add them here because I wanted to use an icon instead of the character itself. The Timeline had it, and so does the split document tool.

In any case, I'm considering replacing them with something that indicates H1 to H4 headers instead.

By the way, there are now 4 different icon themes that have icons that make a bit more sense than the system icons for root folders, etc. The grey set for light backgrounds is activated by default, but since you already had a config file, it doesn't override your settings.

**Comment by vkbo** [comment]
I'm considering replacing the icons with a set ranging from this for level 1 headings:
![image](https://user-images.githubusercontent.com/1619840/84139255-d7ed1a80-aa4f-11ea-9e4e-d3134da3e37b.png)
To this for level 4 headings:
![image](https://user-images.githubusercontent.com/1619840/84139312-eb988100-aa4f-11ea-96f7-ffae36b21cc2.png)
