### ISSUE TITLE
Opening the read view on a file that contains an empty tag crashes the program

### ISSUE THREAD

**Issue by MatthewMarinets** [vkbo/novelWriter#298]
Hitting ctrl+R or selecting "view document" from the Document dropdown to open the view pane  crashes the program if the page contains an empty @tag. After this crash occurs, attempting to reopen the project crashes Novelwriter instantly as it tries to open the same view. I'm able to work around the issue by opening the offending document in a different text editor and removing the empty tag.

`@tag\n`, `@tag:\n`, and variations containing spaces all cause the issue (if the tag appears red in my editor pane, then the crash will happen when I try to view it).

I've recreated the issue while running `novelwriter --debug >log.txt 2>&1`, and have attached the logfile.

[log.txt](https://github.com/vkbo/novelWriter/files/4744035/log.txt)

I'm running Novelwriter on Windows with Python 3.7.2. I haven't been great about upgrading in the last couple months so I'm not sure when this was introduced.

Edit: Forgot to specify, I pulled from main earlier today. Running `novelwriter --version` returns `novelWriter Pre-Release Version 0.8.0rc1 [2020-06-01]`

**Comment by vkbo** [comment]
Thanks for this report. I will fix this right away. It's a trivial fix.

It is really unfortunate that novelWriter crashes on startup. That leaves the user with no other alternative than to edit project files directly to try and bypass the bug. The last viewed document is reopened on launch, so this loading really needs to be more robust even after I've fixed this issue.

**Comment by vkbo** [comment]
Bug confirmed. Interestingly, on Python 3.8.2, this doesn't cause a crash. Seems 3.8 is trying to handle the out of bounds error.

The bug was caused by the tokenizer returning a length one array. The HTML converter only checks for a length 0, but expects at least length 2.

To ensure that novelWriter does not crash on parsing text like this, especially at such a critical time as when opening a project, I wrapped the entire converter block in a try/except construct. The preview window will show an error message if it fails to generate the preview instead of crashing.

The same has been added in the Build Novel Project tool, as it uses the same underlying converter.
