### ISSUE TITLE
Optional Document Footer Bar

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#301]
Taking an idea from other writing tools, I would like to add an optional footer bar to the document editor window. It will be of similar design to the title bar, but have the option to show live word counts and possibly a word count target progress bar.

Similarly, for the document viewer, the footer bar can have buttons to toggle show comments and the reference panel. That means I can also change the layout container of the reference panel to work like the details panel in the outline view.

The footer should be optional, as the aim is still to provide a clutter-free environment, and this one is bordering between clutter and information depending on your preferences and style of working.

**Comment by johnblommers** [comment]
A toggle to show comments is an outstanding idea. This opens up the possibility to toggle the synopsis as well.

An option to toggle the footer display is also a good idea because ... clutter.

This reminds me of a story I heard a long time ago. Bill Gates asked his team why the Apple TV controller was so vastly simpler than MSFT's media center controller. He was told because media center had more features. And he bought it.

This explains why MSFT Word has such a cluttered look and feel. The ability for a designer to provide the features a user needs without a lot of clutter takes genius such that Steve Jobs had in ample supply. Gates is a poser in contrast.

My point being that engineering the human interface to provide all of the necessary functionality without making it look like the flight deck of the Space Shuttle is a goal worthy of aspiration.

**Comment by vkbo** [comment]
I just pushed a bunch of commits to a new PR that will redesign the references panel below the document viewer to use a splitter design like in the Outline view. This was a;ways the intention, but when I first designed it, I couldn't figure out how to get what I wanted. Now I know a lot more about how I can bend Qt to my will.

The new design has a footer bar, where I've moved the show/hide references button, and the sticky switch. This bar will not be optional, as the reference panel depends on it, but the one I'll add for the editor will be customisable.

I still need to add the toggle switch for show/hide comments. I think that belongs in the top bar though. The fact that the synopsis comments are not shown currently, is technically a bug. It's because the build tool and the viewer uses the same HTML generator, and when I made the synopsis a special case of the comment type, I forgot to update the viewer.

**Comment by vkbo** [comment]
About the design philosophy, I agree. Clutter just gets in the way. That's why I've loved to work in FocusWriter in the past. But it lacks the organisation tools I need. Other tools are the opposite.

I have also used Scrivener, but I find it a bit too cluttered. But I also dom't like the extreme minimalism, so I'm aiming for some middle ground.

There are many other feature rich writing tools out there, but many of them don't care much how the app looks, and I cannot work like that!

**Comment by vkbo** [comment]
The rendering of Synopsis text in the Document Viewer has been fixed in #311.

**Comment by vkbo** [comment]
The document footer bar has been added in #348. It is currently not optional, but it only shows the document status and the current word count. The latter is especially useful as it has been removed from the main status bar.

Due to the low information content, and mostly being empty space and part of the document margin, I don't think I'll add the option to hide it. I could possibly make it go away for the full screen mode though.

**Comment by vkbo** [comment]
Added the option to hide the footer in distraction free mode in PR #351.
