### ISSUE TITLE
novelWriter is lacking a global search and replace

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#305]
Search and replace only work when actively editing a document. I'd like to suggest a global search and replace feature.

I've got a situation where I want to replace all occurrences of YYY with ZZZ in all of the documents in my project. Right now I have to go one document at a time and repeatedly click the magnifying glass until each replacements are done.

Preferred is a global search and replace that lets me change all occurrences of YYY with ZZZ in one fell swoop. Perhaps when it's done the number of replacements is displayed.

**Comment by vkbo** [comment]
Yes, I'm aware of this shortcoming and I've thought a bit about how to implement it in the past. @Number042 has brought it up too in conversation.

Redesigning the current search/replace tool is next up on my todo list anyway, so I'll give this some more thought. This is not a small task though. The current search/replace feature just hooks into the built-in functionality of the Qt text editor. A global search can be implemented looping over files and using Python string search, but a global replace is an entirely different matter.

As I've mentioned before, I'm not very keen on opening the can of worms that is bulk altering files. One of the bedrocks of novelWriter's stability is that any editing of text happens within a single well-tested Qt widget. What I can do, though, as a step on the way, and perhaps sufficient, is to extend the search tool to allow continuing the search in the next file when reaching the end of the current file. That would allow sequential search/replace.

I'm in any case extending the search tool to add case sensitive searches and possibly regex. I will also move it into a hovering box (like in VSCode) rather than a layout inserting itself into the top edge of the editor box, an implementation that clutters the main window code a bit (same as the reference panel did, which I've now redesigned).

**Comment by johnblommers** [comment]
> What I can do, though, as a step on the way, and perhaps sufficient, is to extend the search tool to allow continuing the search in the next file when reaching the end of the current file. That would allow sequential search/replace.

That approach would be a huge step forward. It's what the user now does manually. A secondary and also huge issue that that the replace operation today is done one click at a time. I can't replace all YYY with XXX with one click. I have to click and click and click until it'd done. And there is no clear indication you're done clicking. Perhaps a "replace all" icon is needed for the current document.

Then a second checkbox that says "loop over all documents in the project" would allow novelWriter to do a global find and replace.

**Comment by vkbo** [comment]
I'm not a fan of replace all. I've made so many mistakes with it, and even once hand a book where every occurrence of a specific word had two of its letter uppercased and swapped. Clearly a replace all error that made it past editing and all the way to print. (Probably happened *in* editing.)

But there is a keyboard shortcut for replace, so you only have to press that sequentially. No need to click the GUI button.

There will definitely not be a replace in all documents option. I will add a feature that just continues in next document. I'll also add a global search dialog tool.

Looks like there will be a version 0.9 and maybe 0.10 too before we're ready for 1.0. I'm freezing features now for 0.8 and switching to bug fixes. The changes right now are fairly well rounded off, and I want to tag this before moving on to the larger changes discussed here.

**Comment by johnblommers** [comment]
I suppose it is good to remember that perfect is the enemy of good enough.

If I really needed a global search and replace I can always write a shell script to process the files.

There will always be a tendency for scope creep in a project. So far it is amazing how nice-to-use  novelWriter has become. It just looks good and is brimming with useful writing features.

**Comment by vkbo** [comment]
But "good enough" is also the doom of open source. Especially when it comes to design. That is something I very much want to avoid. At the same time, I'm actively avoiding features that are overly complicated and can potentially threaten the core robustness of a read file > edit file > save file workflow.

I'm glad you like it. I use it for a few projects myself of course, and every time I use it for an extended period of time, I find little things to tweak. I suppose it helps me avoid the common pitfall of the design intent diverging from the user experience. Although there's always the risk of making it too much to personal preferences so it doesn't work for anyone else.

**Comment by vkbo** [comment]
Just merged PR #314 into the `dev` branch. This is a complete rewrite of the search bar. It is no longer a bar at the top of the document, but a box hovering over it. It has the same search box and replace box as before, but now has a toolbar above this with a set of options:

* Case sensitive search
* Search only whole words
* Use regular expressions in the search
* Loop the search when reaching the end (file forwards or backwards, project forwards only)
* Continue the search in the next file (if loop is enabled, it will loop the project tree instead)

For the replace feature:
* Case aware replace. That is, it will take into consideration first letter capitaliased, all capitalised, or all lower case when replacing text. For instance replacing "One" with "two" produces "Two". Replacing "ONE" with "two" produces "TWO", etc.

![image](https://user-images.githubusercontent.com/1619840/84944268-c823a500-b0e5-11ea-8186-37710468d63d.png)
![image](https://user-images.githubusercontent.com/1619840/84944342-e4274680-b0e5-11ea-9dd0-6f2c0575aaf4.png)

**Comment by vkbo** [comment]
Oh, and an invalid regex should turn the background red.
![image](https://user-images.githubusercontent.com/1619840/84944873-c0b0cb80-b0e6-11ea-851e-8bd810be7d65.png)
