### ISSUE TITLE
The Trash word count does not go to zero when it's emptied

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#333]
After finding myself doing search and replace in the Trash I decided to empty it using the contextual menu. now it's empty but the word count wasn't updated at the time. Later on I closed the project and opened it again. Now the trash word count is zero.

**Comment by vkbo** [comment]
Yeah, the word counts in the tree are not really counted and summed regularly. They depend on an accounting function that will take the word count diff on a file (the one you're working on) and propagate it upwards in the tree (to parent, grand parent, etc.) This function isn't always triggered properly when a document is moved, including to the Trash folder. It is also not triggered properly when files are removed from Trash.

It was written this way because recalculating and propagating all the word counts each time a file is changed may interrupt the flow as this happens on the main GUI thread. I've limited as much as I can all the activity that goes on in the background on the GUI thread while you're typing. I don't want to have those short freeze and race-to-catch-up interruptions in my writing flow. The word count itself happens on a different thread as it definitely causes interruptions on larger files.

These counts, as you point out, are calculated from the individual file counts only when you open the project. This is because no counts are stored for the folder entries in the project file (you can see it in the project XML file). Counts are also updated when you rebuild the index, as the index maintains a word count per heading section within a file. You can always press `F9` and have all of this updated all the way to the project total on the status bar.

I'll have a look at the logic in the project tree class and see if I can make the accounting work properly also when moving and deleting files.

**Comment by vkbo** [comment]
I think PR #335 solves the issue. The project tree wasn't doing anything at all about the word count when files were moved to trash through the delete option, or permanently deleted. The word count is propagated when a file is dragged and dropped, but not completely then either it seems. This has also been fixed as far as I can tell.

**Comment by johnblommers** [comment]
It looks good from my perch as well.

**Comment by vkbo** [comment]
Ok, closing this then.
