### ISSUE TITLE
Auto-Replace fields don't reflect in the Outline View and Tree View

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#341]
So I went through my manuscript using the search and replace feature and changed all occurrences of my protagonist's name `Van` with `<Protagonist1>`. Then in the Project Settings I defined `<Protagonist1>` as `Fred`. Sure enough when I build the project the substitutions occur as expected.

Now switch back to the Outline View. I have `<Protagonist1>` in some of the H3 headings. And sure enough that string appears in the Outline View. That's jarring. I would prefer that the replacement value appears.

Then I noticed that the old protagonist's name `Van` still appears in some documents of the Tree View. A right-click on such a document reveals that I'm seeing the Label and it's not something that the Editor pane lets you change with the search and replace. The label must have gotten set when I imported the document. And there is no search and replace feature that lets me search over these labels. And I expect that using `<Protagonist1>` in the Label won't result in a replacement either.

Thoughts?

**Comment by vkbo** [comment]
Two things:

**Firstly**, the auto-replace is supposed to be a build-time feature. The Outline View is based on the project index, and is not a build-time object. In order to do what you expect I need to run a mini build on the content of the Outline View. As it is now, collecting the information for the outline is just a matter of collecting the correct values from the index, which is done in a quick for loop over a couple of dictionaries. Having to run through the auto-replace in the middle of this process will complicate things, especially in terms of keeping it up to date when the user makes changes to the auto-replace list.

The auto-replace feature was made because @Number042 requested it. In his novel, a lot of characters have names that are tricky to spell, so to avoid multiple spellings of the same name – or typos – this feature was added. It wasn't designed to be used as placeholder names for characters until the author comes up with that one brilliant name later. Although, I totally see why that could be useful.

My thoughts on the display of the auto-replace is in any case that I consider this a "source code" feature, separate from build time, and only the document (view window) or project build tool will perform the auto-replace. The index is built on the source, and therefore the outline is also reflecting the source. An exported outline will of course be a build.

**Secondly**, about the labels. The labels are not source code data, they are file meta data. So the builds don't process them at all, which is why the auto-replace isn't applied either. Personally, I'd just label the files something like "Protagonist 1 goes to the pub" or whatever.

The design of novelWriter is inspired by a bunch of tools I use, one of them being [Zim Wiki](https://zim-wiki.org/). It too distinguishes between the label of the entry and the main header. But it does allow syncing them as a once-per-edit checkbox in the edit dialog (see screenshot) so I've considered this as a feature.

![image](https://user-images.githubusercontent.com/1619840/85677308-b8005c80-b6c7-11ea-852f-276f27689652.png)

**Comment by johnblommers** [comment]
So I've been defining some `@char` tags to use with the outline view. Then I thought about auto-replace again. How can we use `@char: Tom` and expect `Tom` to be `<Protagonist1>` and then expect the outline view to translate `<Protagonist1>` back into `Tom`?

I'm dwelling on this because I'm not at all satisfied with my character naming conventions. So I was hoping to use auto-replace as a work-around. Otherwise I have to do a global search and replace to change `Tom` to `Thomas` and hope that I don't accidentally change `Tomorrow` to `Thomasorrow`. 

Whole word, case sensitive search and replace seems like the right way to go, rather than auto-replace.

**Comment by vkbo** [comment]
The search/replace tool should now have the features needed for that, and RegEx if the standard options aren't enough.

But you're right, the auto-replace feature isn't flexible enough to handle your needs here. I don't think I can make this work seamlessly either with the way this is implemented. As mentioned, the auto-replace feature is sort of ad-hoc and was added on a specific request, and isn't really incorporated into the cross-reference logic.

I've also considered adding standard auto-replace fields that can be used to for instance generate a manuscript cover page if the user hasn't created a file with layout Title Page themselves.

These are the kind of small things to look at for the 1.0 release candidates I will start releasing soon.

**Comment by vkbo** [comment]
Since the search/replace tool has had the features needed for a while now, I can probably close this. I also don't think I will add the auto-generated title page feature. I've added enough formatting codes in 1.4 and with the upcoming 1.5 that the user can easily make a cover page themselves in whatever format they want.
