### ISSUE TITLE
Apparantly Harmless Error message

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#418]
**Describe the Bug**

When novelWriter is launched at the command line at least two and later on more messages issue:

```
ERROR     No tree item with handle None
```

**To Reproduce**

Launch novelWriter at the  command line. novelWriter launches. Do nothing else. Two messages issue forth back in the terminal.

**Expected Behaviour**

No error messages should issue.

**Screenshots**

![Screenshot from 2020-08-17 14-24-47](https://user-images.githubusercontent.com/8484427/90446015-7a9bc800-e095-11ea-9611-fd4a4af6ce34.png)

**Error Message**

```
ERROR     No tree item with handle None
ERROR     No tree item with handle None
```

**Additional Context**

From the user perspective these message don't correspond to any problem. But these messages should not really emit.

**Comment by vkbo** [comment]
They are indeed harmless.

All project items are identified by a 13 digit hex hash key, which can be seen in file names, in the project XML, and internally as lookup keys in the main dictionary.

The code uses `None` as initial values for a lot of critical variables. This helps ensure the wrong values aren't passed around, and almost all functions handle None values as a safeguard to return without performing the requested action, or use them as a fallthrough value in chains of lookups for various parameters.

The function that prints the above error has just been asked to look up a handle variable that is set to `None`, which of course will always fail, and return another `None`. I don't know exactly where the call comes from, and I plan to find out and inject an if statement to stop the message, but the `None` itself is handled just fine.

**Comment by vkbo** [comment]
Just for the sake of completeness: The error was caused by two lookups in the document footer bar (checking document status and word count) when there was no document open. This happens during initialisation, and whenever a document is closed. In both cases, the document reference value is `None`, because, well, there is no open document. The `None` value was intentional and used to tell the footer to clear the two meta data values. The logic has been altered to check for this earlier and not propagate the lookup itself in the case of a `None` reference.

**Comment by johnblommers** [comment]
And that explains why two error messages on launch.
