### ISSUE TITLE
FR: Discard all changes and close project

### ISSUE THREAD

**Issue by rtiangha** [vkbo/novelWriter#494]
It's a risk 3 days in, but I'm switching from using Scrivener to using novelWriter for NaNoWriMo 2020, and already it's doing everything I wanted to. I'm trying to learn to use the tool as I go along, but my only frustration at this point is that when I close a project, I'm forced to save it because if I click on No on the dialog, it keeps the project open and that makes it hard to play around with settings and features and such on a live project. Sometimes I just want to try something, and if I don't like it, revert back to what was working. Instead, I end up opening up a second instance just to try things and see what happens so that I don't accidentally end up bashing my main project.

So in the close project dialog, I'd love a third choice that would allow me to Discard Changes before Closing or something like that, and for the 'No' button to become a 'Cancel' button instead (which is what it feels like it does; basically it cancels the close operation to go back to editing the document).

Anyway, I already love this tool and am running off of source to keep on the bleeding edge rather than the releases, and I'll be keeping an eye on progress throughout November!

**Comment by vkbo** [comment]
I'm glad you find it useful!

The thing about novelWriter is that you're working on individual files not the entire project at once, so not saving the project doesn't discard changes you've made to the text. This is also why the dialog box doesn't let you exit without saving changes. Doing so would potentially cause inconsistencies in your project. The document files are saved frequently, including every time you switch document. I wrote it this way to make it robust against data loss. The project isn't kept in memory until you save it like in many text editors.

There isn't really any way to get around this. It's at the core of how the application works. If you want to experiment, you don't really have any other option than to have a separate project to play around with. I can see how that is inconvenient when testing things.

I can certainly try to make this clearer when you do close the project. I've also tried to explain this in the documentation and the readme. It's a multi-document editor rather than a single document editor.

I'm curious as to what you want to test that may mess up the project? I know that one shortcoming is that you cannot revert to an earlier version of a document. This is high on my to do list when I'm done with version 1.0. It's a feature I miss when I'm working on my own projects too.

**Comment by rtiangha** [comment]
Ah, I see. Yeah, I finally read through the manual last night before bed; I get how things were designed now and things are clearer on why some things work the way they do.

As for playing around, I mean exactly that. Clearly, I didn't have a chance to read the docs before jumping in, so I was playing around with functionality to see how things worked, toggling things on and off, playing around with tagging and such. I was just a little confused when the close dialog popped up with how it was worded because I thought it was prompting me to save unsaved changes since that's how I'm used to other programs working (i.e. They prompt you to save unsaved changes; and if there have been no changes since the last time you saved, the program just closes). I would have sworn I reverted everything back after experimentation, but the pop up made me doubt that. But yeah, that's because yesterday was Day 1 of using the program for me so I was still learning it.

The docs, btw, are really well written and I like the ability to compile an offline version the program can access since I write mostly offline because online can be distracting. This program seems to work the way my brain works, so I'm really looking forward to putting it through its paces this month. Thanks again!

**Comment by vkbo** [comment]
Yeah, I've taken the approach to automatically save everything you do instead of letting the user handle file and project saving manually. Most similar applications I've used takes a similar approach where you have to create the project and its document before you add content. Document editors tend to take a more manual approach where you start with a blank, unsaved file.

The idea is to just let you write instead of having to think about these things. You can manually force a save of course, but it isn't necessary. Opening a new document will automatically save and close the previous document if you made any changes to it.

It would probably be a good idea to expand a bit on what the design philosophy is in the docs. A lot of it is inspired by code editors, which is what I otherwise use every day. I have implemented a lot of functionality that I'm used to from such tools.

I'll look into making that dialog box clearer anyway.

**Comment by vkbo** [comment]
The close project dialog now states:
```
Close the current project?
Changes are saved automatically.
```

The exit dialog is changed to a similar text.

**Comment by vkbo** [comment]
> The docs, btw, are really well written and I like the ability to compile an offline version the program can access since I write mostly offline because online can be distracting. This program seems to work the way my brain works, so I'm really looking forward to putting it through its paces this month. Thanks again!

I hope it is working as expected. Don't hesitate to report issues, suggest improvements, and point out things that are unclear. This is essential feedback to help me make the app better.

I wrote novelWriter mainly because I couldn't find a tool that worked the way I wanted it to. It is therefore inspired by the tools I'm used to work with as a programmer as well as a writer. I want it to be a bit different, but I also want it to be useful to more people than just me. :)

**Comment by rtiangha** [comment]
The new wording is perfect and makes much more sense; makes it clearer/helps prevent accidental closure of the program too. Thanks so much, and keep up the good work!
