### ISSUE TITLE
Outline grid features

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#498]
Hello!

I just finished my first couple of hours with novelWriter and wanted to give you some general feedback and a feature request.

Installation went according to your directions. The only problem was getting python to install on my Windows PC...

novelWriter, I am happy to report, is a mature and robust novel writing tool, comparable to apps like Scrivener as far as its core features are concerned. My warmest congratulations! I was greatly impressed (and I have tried most, if not all, novel writing / note management apps as a way of procrastinating from actual writing).

Some (very small) usability issues:

* Editor: the top and bottom status lines are truncated, but still usable. I don't know if this issue is due to the size of some system font or it's related to the screen's resolution.

* Tree view: when you single click on a tree element the editor is not updated and the UI then looks inconsistent. (But you can always double-click tree elements and avoid this situation).

* nothing else! Everything works perfectly!

And here is my feature request: it would be great if the outline grid offered features such as sorting and filtering. It would be even greater if the outline remained visible along with the editor, as an alternative way to navigate the document's structure (if you decide to go in that direction then the outline view might function as an expanded version of the tree view).

To give you a use case, in the timeline I have tags "past" and "present". So I would like to sort/filter according to these tags and then navigate the document as if the tagged sections were consecutive.

Again, great accomplishment, all the best!

**Comment by vkbo** [comment]
## Feature Request

> And here is my feature request: it would be great if the outline grid offered features such as sorting and filtering. It would be even greater if the outline remained visible along with the editor, as an alternative way to navigate the document's structure (if you decide to go in that direction then the outline view might function as an expanded version of the tree view).
> 
> To give you a use case, in the timeline I have tags "past" and "present". So I would like to sort/filter according to these tags and then navigate the document as if the tagged sections were consecutive.

The Outline view used to be an independent window. This was fine on a large screen, or dual screen setup, but inconvenient on a laptop, so it was abandoned. The current implementation is a compromise between being able to show a lot of details and being available on the main GUI at the same time.

I have considered adding an outline mode to the main tree view, which would mostly cover your request. I am just a bit concerned it will be a confusing feature as it will look similar to the folder/document tree, but work quite differently in terms of settings and lack the ability to add documents (as it'll be working with headings instead of files). However, I can give it a try and see.

As for filters for the outline view, that is something that can be added. The old implementation of this tool had such filters. I just need to find a good way to implement it in the GUI.

Perhaps I can make an alternative tree view which shows filtered headers. That will leave the current tree view and outline view as-is, and avoid making them too cluttered. It would also make the filtered project outline a distinct tool that would stand out from the other two.

I have to think more about this ...

**Comment by vkbo** [comment]
This feature request should be considered in connection with #76, which is a feature intended to display the structure of the project from the opposite point-of-view. That is, the Outline displays the project from the perspective of its structure in terms of its headers (chapters and scenes). The alternative proposed by the Timeline approach will display the structure from the perspective of a single (or group of) story element(s), character(s), or similar, through the progression of the story.

This complementary perspective may be enough to cover the part of this suggestion to be able to filter specific story elements.

**Comment by johnblommers** [comment]
I like where this is going.

**Comment by jyhelle** [comment]
and so do I ...

**Comment by vkbo** [comment]
I've started adding a "Novel" tab in the project tree panel, which is currently sitting in PR #537 on branch [novel_tab](https://github.com/vkbo/novelWriter/tree/novel_tab). I've also created an issue for it on #541.

I'm not sure yet if this is a useful feature, but I'm playing around with it in an attempt to make the meta data easier to access from the main GUI. I do fear that it may seem a little clunky if I start adding a lot of such features.

**Comment by alexisargyris** [comment]
Is there any way to follow what you are doing without installing a branch of novelWriter? A screen capture perhaps? I'm hesitant to install alternate versions of software I use for daily work.

**Comment by vkbo** [comment]
Personally, I keep the version I use for working on my novels separate from the version I'm working on with the code. I just have two cloned copies of the repository.

But sure, I can post some screenshots. Here's the current state of the tree view tabs:
![image](https://user-images.githubusercontent.com/1619840/102891448-7fff8980-445e-11eb-8eed-d972a3cba5f2.png)

**Comment by alexisargyris** [comment]
I find very useful what I see. So there are two tabs at bottom-left (Project and Novel) and another two tabs at top-right (Editor and Outline). Will all combinations be active?

**Comment by vkbo** [comment]
Yes, they are completely independent.

**Comment by vkbo** [comment]
Since 1.1 is released with the new Novel tree, I think the outcome of this request is covered? The other idea covering the alternative view of the outline content is a part of #76, and is discussed there.

I'm closing this now to clean up the issues list, but if you think these should be separate topics, then we can always re-open.
