### ISSUE TITLE
Status lines get truncated (screen scaling issue)

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#499]
**Describe the Bug**
The editor's top and bottom status lines get truncated.

**To Reproduce**
Just loaded the sample project. The screenshot is from my home PC. In my work PC the status lines are also truncated but less so (i.e. the icons are more visible).

**Expected Behaviour**
Status lines should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/1640855/99834664-3294b180-2b6c-11eb-93b9-ae923511b3a0.png)

**Additional Context**
Please also note that the "view" window cannot go any further down (i.e. in order to become equal to the editor window in height)

**Comment by vkbo** [comment]
I cannot reproduce this. Here's what I can see on my Windows 10 virtual box:

![image](https://user-images.githubusercontent.com/1619840/99862641-d09f7080-2b9a-11eb-9e5f-3bb9b84beccf.png)

Could you please check in Preferences on the General tab what the font family and font size is set to?

**Comment by alexisargyris** [comment]
Cantarell, 11pt. Didn't touch them.

**Comment by alexisargyris** [comment]
Made some experiments. If I change the font size to 9pt the icons become just visible. The difference is very small though. Here is what I see.

![image](https://user-images.githubusercontent.com/1640855/99869534-62779f80-2bd4-11eb-9e93-e1ce4c1423d6.png)

**Comment by alexisargyris** [comment]
After some more experiments I'm thinking the problem is most likely related to how your UI library behaves in different resolutions.

Here is the app window in my main laptop screen (resolution: 3840x2160, scaling: 250%)
![image](https://user-images.githubusercontent.com/1640855/99869790-70c6bb00-2bd6-11eb-951c-efac6ee3d16f.png)

If I drag the app window to my secondary screen (resolution: 1920x1200, scaling: 100%) this is what happens
![image](https://user-images.githubusercontent.com/1640855/99869843-dadf6000-2bd6-11eb-9fcc-258ff7df5d2d.png)

Notice that the status lines become a bit more visible. To clarify: I didn't change the window's size, just dragged it to the other screen.

Side note: I opened two instances of novelWriter at the same time to work on two different folders. Didn't notice any problems.

**Comment by alexisargyris** [comment]
Ha! I found this message in the console window _under_ the novelWriter window:

> "QWindowsWindow::setGeometry: Unable to set geometry 1138x283-511+907 (frame: 1170x371-527+835) on QWidgetWindow/"GuiMainWindow" on "\\.\DISPLAY1". Resulting geometry: 2853x717-893+948 (frame: 2885x805-909+876) margins: 16, 72, 16, 16 minimum size: 1138x283 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1170,371 maxtrack=0,0)"

**Comment by vkbo** [comment]
Ah, it's a scaling issue. I had that thought this morning actually and was about to ask.

The scaling support for Qt5 is a bit dodgy, and especially for non-integer scaling as with your 2.5 times scale. I added scaling support to the code a while back, but since I don't have any such screens at home (I do at work) I rarely test this. It's probably not applying the scaling factors properly to the header and footer. That I can probably reproduce and fix. Will do that today. It should handle this properly.

As for moving novelWriter between screens of different scale, that isn't currently handled and will produce mixed results. Especially for icons as you can see. A lot of the scaling is handled when the GUI is first loaded, during initialisation, and isn't dynamically updated if the scaling changes at runtime.

If you launch the app on the 100% scale screen, it should look normal.

As for opening two instances of novelWriter, that is fine if it's two different projects. The only issue would be if you change Preferences to different values in the two instances.

**Comment by vkbo** [comment]
The truncated header/footer issue should now be resolved with PR #502.

As for dragging the app between two screens of different UI scale, I cannot do anything at the moment as I don't have a setup that allows me to test this (I can scale my desktop, but not individual screens). As I said, this is a known issue, and I hope to look into it later on.

There are some ways to control DPI awareness on Windows, see the [Qt docs](https://doc.qt.io/qt-5/highdpi.html), however I don't have a Windows setup outside of a virtual box, so have limited opportunity to test this. If you feel like playing around with passing setting directly the Qt library, you can add parameters to the QApplication list on this line in the source code: https://github.com/vkbo/novelWriter/blob/6d630d3a1b56ad83e82847edc8bc5c9dbc9ae95f/nw/__init__.py#L283

**Comment by alexisargyris** [comment]
#502 did it! Great work! Thanks

**Comment by vkbo** [comment]
My manual implementation of UI scaling should be able to handle fractional scaling. The issue with fractional scaling is that the scaling factor may result in non-integer pixel values. My code truncates all decimals in the scaled sizes, so it should work fine. Qt5 has started implementing float values for GUI sizes, but I don't think the support is complete in the libraries.

I'll eventually get to handle the automatic rescaling, but it may have to wait until I eventually move to Qt6.
