### ISSUE TITLE
Reference keyword for custom file class

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#501]
In addition to the default note categories (Characters, Locations, etc) I created a custom note category unimaginatevely called "notes". What keyword should I use to reference tags of that category?

**Comment by vkbo** [comment]
You refer to them with `@custom`. All the keywords are listed in the docs, [here](https://novelwriter.readthedocs.io/en/stable/projects.html#project-roots) and [here](https://novelwriter.readthedocs.io/en/stable/structure.html#a-struct-tags).

I should probably add an entry in the Insert meny with these so people who are new to the app so that people don't have to remember them. I sometimes even forget myself!

**Comment by vkbo** [comment]
PR #503 adds a sub menu in the Insert menu where all the valid keywords can be added. This avoids the need to go to the docs to look them up.

**Comment by alexisargyris** [comment]
I think the Insert menu is much better with the sub-menus. Sorry for the @custom keyword. Forgot about it.
