### ISSUE TITLE
Formatting of parts while building a novel project

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#506]
**Is your feature request related to a problem? Please describe:**
I have a book divided into parts (and chapters, scenes, sections). The "Build Novel Project" does not allow numbering the individual parts, i.e. it does not offer the same formatting features as for chapters and scenes.

**Describe the solution you'd like:**
Be able to number a book's parts.

**Describe alternatives you've considered:**
Make each part a separate book.

**Comment by vkbo** [comment]
Parts isn't a separate level of the hierarchy, like chapters, scenes and sections are. Parts is equal to the main title. so it is just a way to split a project into multiple titles. You can use it for multiple books, acts, parts, or whatever you wish. It isn't currently possible to distinguish between different usages of a level 1 title, so it's hard to know which level 1 titles to number and which not to. They also don't have a separate formatting setting.

In addition, the reason chapters and numbers can be numbered automatically is that you may want to rearrange them. It is a lot less likely you want to do that with parts, so there isn't as much a need for it as otherwise.

**Comment by alexisargyris** [comment]
Just to clarify: I understand the intention behind the current implementation of parts. I just tried to propose a use case for providing an additional hierarchy level above chapters. However if it doesn't seem generally useful one can always convert each novel part into a separate book. This approach may have additional benefits as far as the organization of notes is concerned (i.e. _not_ having to separate the characters, locations, etc of each part). Anyway, thanks for your consideration.

**Comment by vkbo** [comment]
Hmm, let's leave the issue open for now.

Currently, there is no room for new levels between the book itself and chapters. Parts are on the same level as the book. However, I have been thinking about taking away the top level as it is practically redundant. That would leave the level one headings free to be exclusively for parts, acts, books, or whatever you want it to be. If so, it could have a number assigned to it. Adding the new format would in itself be trivial.

I will give this a bit more thought.

**Comment by vkbo** [comment]
Follow-up question:

I read your suggestions again. I'm wondering what you think is the limitation of the current system of parts that means you have to split them up into separate projects? Aside from the automatic numbering of parts themselves.

I feel there is something in your suggestion I'm not getting, and I would like to understand it.

**Comment by alexisargyris** [comment]
I gave it some more thought and I now believe I was wrong. My initial idea was that if "Novel" is organised in a number of parts then all note hierarchies (i.e. plot, characters, locations, timeline, etc) will also need to be organised in the same way and the user will end up with something like this:

* Novel: Part 1, Part 2, Part 3
* Characters: Part 1, Part 2, Part 3
* Locations: Part 1, Part 2, Part 3
* Timeline: Part 1, Part 2, Part 3

In such a case it might be more convenient to break the whole project in three parts and keep the text, characters, locations, etc of each part separately.

However this assumption is not necessarily true. A user may decide to list Characters or Locations in whatever order she likes and not by the part in which they appear in the text.

Anyway, this is just idle speculation on my part as I have not decided to follow that direction. If I do I'll let you know.

For the time being I think I would be more than happy if there was a way to insert a page break before each part.

**Comment by vkbo** [comment]
Ok, I see.

If it's more a matter of structuring the project in a way that keeps the different parts separate in the project tree, using folders is one way to achieve that. I've intentionally left the folders as a tool entirely for the user to chose how to use in order to structure the project; novelWriter ignores them. Personally, I have folders for Act 1, 2 and 3 in my projects and sort the chapters and scenes into those folders. The act structure is not visible in my compiled novel, which I don't want either. It's just an aid for me when writing to ensure I have a sensible flow in the story. You can achieve the same with parts, characters and so on.

As for inserting the page break, adding a page with layout "Partition" should achieve that. These pages have a "page break before" setting. So do chapters.

Note that the intention of the Build Novel Project tool is not to create a publishable document (in the case of self-publishing for instance), but a compiled draft or even just an outline.

**Comment by alexisargyris** [comment]
Ah! Partition is what I was looking for! Now I'm all set. No more excuses.
