### ISSUE TITLE
Create a file under root folder Outtakes

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#517]
**Describe the Bug**
Attempted to create a file under root folder "Outtakes" but no such option seems to be available. Is this a bug or am I missing something?

**Comment by vkbo** [comment]
No, it isn't a bug. Outtakes is the folder to drop files you want out of the project into, but don't want to delete (yet). You cannot create files there. But you can create folders to organise them into. Likewise, you can't create files in the trash folder either.

**Comment by alexisargyris** [comment]
Sorry, my mistake. IMO, this "bug" (i.e. being able to create files/documents inside Outtakes) is a good thing, because this way Outtakes behaves like a scrapbook where the user may store either individual files or small pieces of text in one single file.

**Comment by vkbo** [comment]
I can certainly enable the "New File" option again for the Outtakes folder. It's just a flag that removes the option from the menu. Since a new file can be created from the main menu, I need to make the main and the context menu behave equally anyway.

A general principle I've followed when making novelWriter is not to add restrictions on actions unless they can cause errors or introduce unintended behaviour. People may want to use certain features slightly differently than they were intended, which I think is fine. You should absolutely be allowed to rename the "Outtakes" folder to "Scrapbook" and use it as that instead.

The only difference, anyway, between the Outtakes folder and the Novel folder is that the files in the former are automatically excluded from the Outline and the Build Novel Project tools.

**Comment by vkbo** [comment]
The "New File" option has now been enabled in the project tree context menu. It seems like creating files there doesn't cause any problems elsewhere in the code.
