### ISSUE TITLE
Docs don't say how to run novelWriter!

### ISSUE THREAD

**Issue by Synchro** [vkbo/novelWriter#586]
I'm on macOS, and I successfully installed novelWriter using `pip3 install --user novelWriter`, however, once this was done I couldn't figure out how to run it, as I had no idea where it had installed (python desktop apps being a very rare thing). After much searching I eventually found it in `~/Library/Python/3.9/bin`, and I could run it from a terminal by issuing `~/Library/Python/3.9/bin/novelWriter &`. Note there's no `.py` on the end of its name, which made it harder to find as that's what the docs say it's called. It would be really helpful if some hint was given about this in the docs, for *any* platform.

**Comment by vkbo** [comment]
Yes, pip makes that executable. If your system is set up correctly (the bin folder in path), all you should need is to type `novelWriter` into the terminal. I'll add this to the docs.

I know of several Python applications that run on Mac, but usually someone sets up a proper install and run environment for them that is suitable for macOS. I don't have a mac, and know next to nothing about them, so that's something I'd need help with. This is also why the instructions for mac are minimal.

**Comment by vkbo** [comment]
I've updated the documentation and README. Hopefully it's easier to find this information now. :)

**Comment by Synchro** [comment]
Thank you!
