### ISSUE TITLE
Allow for stopwatch pause and resume

### ISSUE THREAD

**Issue by manoelpqueiroz** [vkbo/novelWriter#606]
While it's nice I can either see statistics per session or per day (the latter in some way an alternative to this very proposal), it would be nice if we had controls over the stopwatch when a file is opened, that way statistics wouldn't be skewed should I forget the application open.

I think there are two "basic" (figuratively since I'm aware implementing new stuff is never trivial) features that would allow for writers to deal with the stopwatch the way they prefer:
- Options for auto-stop and auto-restart (which would work separately):
  - Upon no change in text, timer would automatically stop;
  - Upon typing anything, timer would automatically resume;
  - With both manual options set, timer would behave as currently implemented until user actively chooses to stop/resume.
- Create a second stopwatch that would run independently to the user preferences (essentially behaving as currently implemented all the time). That way, tracking both "times" would still be possible even with customisation.

It's not really something necessary, but since novelWriter already has a timer (which in my humble opinion, is a *very* clever feature I haven't seen in other editors), improving upon it would be a welcome addition to this awesome editor.

**Comment by vkbo** [comment]
Thanks for the suggestion. In my first attempt to write this application, which is archived in [novelWriterGtk](https://github.com/vkbo/novelWriterGtk), I had this exact feature. The clock stopped if you weren't active for a given amount of time.

There is already a feature that detects whether you're actually writing or not, and that is the word counter. It runs in the background every 5 seconds, but if you stop typing, the counter stops after a little while too. If you run novelWriter from the command line with the `--verbose` switch, you can actually see it work.

I can easily use the same logic to implement your suggestion. The log file in the project folder (`meta/sessionStats.log`) only records the two time stamps when you opened and closed the project, so I cannot alter this functionality, otherwise old log files wouldn't work. Also, the current stopwatch isn't really doing anything other subtract the time you opened the project from the current clock. I could add a second clock that tracks the inactive time, and add that to the log file as a new column, which if missing would just be taken as `0`. Then that number could be subtracted from the session time as an additional filter in the Writing Stats dialog.

There wouldn't be that many things to change to make this work, so I'll add it to my ToDo list.

**Comment by manoelpqueiroz** [comment]
Thanks @vkbo, I would also like to express here my intent to start contributing to the project, I would like to immerse myself into the open source world through software I really like and would like to see improving over time.

Helping you guys with novelWriter would allow me hone my skills with git, PyQt and software development in general, but since I have absolutely no experience in contributing to anything, I'm not sure how I could understand the project's structure through its files, much less how to contribute without drawing you guys back.

Would you have any suggestions on how to proceed, Veronica?

**Comment by vkbo** [comment]
Currently, I'm the only one working on the code itself. Most other contributions have been to documentation and other files.

Right now I'm mostly working to add new features that I've been planning for a while. I have it all laid out in my head, and I'm working on it across multiple branches. It is not at all trivial to jump into that. Especially since I haven't written all of this down anywhere.

Not to say contributions aren't wanted. Both bug fixes and small feature requests pop up all the time, and they are great places to start as they often don't involve understanding large parts of the code.

I'm not aware of anyone else having spent a lot of time going through the code, but I've been working on adding comments and restructuring it to make it easier to read. I've split the source code up into two folders containing the `gui` and the project `core`. The latter is where all classes that handles the user's project data live. The `constants` folder is for various files used for lookups of values. I'm happy to explain how the code is structured in more detail on specific questions. I suppose the [Discussions page](https://github.com/vkbo/novelWriter/discussions) is useful for that.

**Comment by vkbo** [comment]
Combined with #651, I've added a feature in PR #656 that records how much idle time occurs in a session. The idle time counter starts when the editor has been inactive for 30 seconds, or when the application no longer has focus.

The status bar clock will then appear to stop (it actually just subtracts idle time). The idle time accumulated during a session is then written to the session log together with the rest of the session stats.

On the Writing Stats dialog, the idle time per session or day can optionally be displayed next to the session length column, and the total idle time is always displayed at the bottom. The idle time is also exported to the JSON and CSV files.

I think this is a fairly reasonable solution given the limitations of the current implementation, as the new implementation needs to be backwards compatible. If you really want to crunch your data further, the exported files can be imported to a spread sheet type application.

**Comment by vkbo** [comment]
This has now been merged into `dev`. The final version of it changed slightly from the above description.

* The status bar clock changes icon to a pause symbol when the timer stops because the user is not active.
* The user can choose in Preferences whether the clock should stop at all when the user is idle. The session log will record it regardless, so it doesn't affect the data displayed in Writing Stats.
* The definition of "idle" is either that the app itself no longer has focus (#651) or that the user hasn't made any changes in the document editor for X minutes, where the value can be set in Preferences. It defaults to 5 mintes.
* On the writing stats dialog, the default is to show idle time as a percentage of session time. A switch changes this to show the actual time in HH:MM:SS.
