### ISSUE TITLE
Automatically save before building project

### ISSUE THREAD

**Issue by dazappa** [vkbo/novelWriter#610]
If a document or the project itself has unsaved changes, the "Build Project" function in the "Build Novel Project" dialog will build the novel project with the latest saved changes, not the latest changes open in any editor.

Consider forcefully saving the editor / project when "Build Project" is clicked, before novelWriter performs its actual building functionality to ensure when "Build Project" is pressed it will always build the novel with the latest changes.

**Comment by vkbo** [comment]
The project data is read from the in-memory project dictionary, and the order of items in the tree widget are flushed before the build, so that part is fine. The text from documents are read from file though, and you're probably right that the latest content isn't saved first. It's an easy enough one-line fix to manually trigger the document auto-save function.

**Comment by vkbo** [comment]
Added and merged into the `release` branch, which will be tagged for Version 1.1 RC 1 this weekend.
