### ISSUE TITLE
Disable "Save As" in Build Novel Project until novel is built

### ISSUE THREAD

**Issue by dazappa** [vkbo/novelWriter#611]
There was some confusion the first time I used "Build Novel Project". It was not obvious to me that this was a two step process. I had a project with some chapters and scenes, but the first button I pressed was "Save As" without first clicking "Build Project". This resulted in an exported blank document.

Consider disabling the ability to "Save As" until the "Build Project" has been clicked at least once. This will prevent people from exporting blank documents, and make it more apparent Build Project must be used each time the user wants to export a novel.

**Comment by vkbo** [comment]
Yes, this is a bit quirky, and is scheduled for a rewrite anyway with the module I'm working on that can save `.odt` and `.fodt` files from PR #607. With the new format, the "Save As" button for the Open Document formats will run its own build process, and will behave as you first expected here.

The reason for the current logic is that the preview window uses the same content as the HTML output, so it is just cached in case you want to save in one of the HTML formats. The concatenated source files are also cached. The main reason for this logic is that the save to plain text, markdown, PDF, and the current implementation for Open Document, are all Qt functions for converting the content of the text browser (preview) window, so the window must be populated first.

Adding my own ODT writer (which is a painful file format to generate I may add) I can bypass the Qt library. The Qt markdown is more or less redundant since novelWriter's own markdown is compliant, and the meta data tags can be easily reformatted for compliance as well. The plain text is not very useful. The PDF output is just a shortcut for Print > Save as PDF, and is already a part of the print function. It makes sense for the print to take its content from the text browser, and it anyway produces its own preview on the print dialog. The "Save As" function should not depend on the preview.

**Comment by vkbo** [comment]
After merging #650 into the `dev` branch, all save formats now run their own build process and no longer depend on the content of the preview. This will be a part of version 1.2.

Closing this issue.
