### ISSUE TITLE
download blocked of v1.1 rc1

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#633]
While trying to download Version 1.1 RC1 I got this:

![image](https://user-images.githubusercontent.com/1640855/106393378-69eecc80-63ff-11eb-8543-0c19c6518c19.png)

**Comment by alexisargyris** [comment]
Windows also refused to install it.

**Comment by alexisargyris** [comment]
Question: is the installer going to replace my working novelWriter copy?

**Comment by vkbo** [comment]
I just installed it myself on a virtual machine. Does it give any reason for this? It's just a packaged version of python, the pip dependency, and novelWriter as a `.pyz` file.

Yes, it will replace the existing version. I suppose it's better to tun the testing version from source.

**Comment by alexisargyris** [comment]
For more information the user is directed [here](https://support.google.com/chrome/answer/6261569).

**Comment by vkbo** [comment]
Yeah, I tested it on a Windows version of Chrome too. It's basically warning that you're downloading a file that isn't "commonly downloaded", which is true since I made it less than an hour ago.

Windows is a nightmare to make installers and packages for because it is such a bad platform for software distribution and I really hate dealing with it. I've spent a lot of time rewriting the tool to make this installers, and if Windows throws more nonsense at me, I'm just going to stop. I'm kind of fed up with it.

I had a lot of problems with virus tools mistakenly flagging install files made with pyinstaller as potential malware. The people over at their repo is dealing with tons of issue reports on it: [github.com/pyinstaller/pyinstaller/issues](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed). So I dropped pyinstaller entirely in the end.

**Comment by vkbo** [comment]
You can click the up arrow and choose "keep". I guess that's the only option. I'm not sure what else I can do.

**Comment by vkbo** [comment]
Did you manage to get it running? I'm also wondering if you had this issue with the previous versions?

**Comment by alexisargyris** [comment]
Yes, thanks, I noticed the "keep" option. I just wanted to let you know.

BTW, I just tried downloading again (on a different PC) and there was no complaint this time. As you said, this notification seems to be displayed only while the file is relatively "new".

Regarding installing this version I'm still hesitant. My working copy of novelWriter is the one from the sources -- I did that in order to have access to new features as soon as they are produced. The installer creates a different instance of the application -- correct?

**Comment by vkbo** [comment]
Yes, the installer contains an executable zip file of novelWriter (`novelWriter.pyz`), the three dependency packages from PyPi in a `lib` folder, and a standalone version of Python. All of this is copied into a folder under `C:\Program Files` or the single user equivalent location. These should not interfere with whatever manual folders you may have.

The installer also makes a desktop icon and start menu icon that points to the `novelWriter.pyz` file, and puts a few records into the registry so that you can open a project by double-clicking the `nwProject.nwx` file from any project from the file explorer.

Aside from that, keep in mind that if you open a project with a newer version of novelWriter, and then go back to an older version, novelWriter will throw a warning that you do just that. The project file contains information about what version of novelWriter saved it. If I add new features that add new entries in the project file, these will be lost when you move to an earlier version. There has been no changes in the project file structure since long before first betas of 1.0, and the file format is also versioned to make sure it doesn't break (currently at 1.2), so I'll probably remove that warning soon.

The only issue with switching between versions is that some of them add new config settings to the main configuration file. When you move to an older version, and back again to a newer version, new settings will reverse back to their default values. For version 1.1 that's mainly the chose column widths of the Novel tab and whatever the controls on the Project Details panel were set to.

**Comment by vkbo** [comment]
As for the latest features, I'm trying a branching model that ensures the `main` branch is always the latest stable, plus patches. The `release` branch is for release candidates that will soon go into `main`, and `dev` is for new, experimental features that require more testing before moving on.

**Comment by vkbo** [comment]
> BTW, I just tried downloading again (on a different PC) and there was no complaint this time. As you said, this notification seems to be displayed only while the file is relatively "new". I never had this problem up to now but I've probably never attempted to download a new version so quickly.

I just tested this on a Windows virtual machine, and it still gives the warning on the latest installer. It doesn't give a warning on any of the previous installers. It may indeed just be a timing issue.

Since there is no strong need for an installer, since it's just Python code, I'm considering adding a `setup.bat` file that does the same configuration the installer does, but just locally. Then people can choose not to use an installer at all.

**Comment by alexisargyris** [comment]
Thanks a lot for the detailed explanation of the installer's internals. I'll give it a try tonight, I hope.

**Comment by vkbo** [comment]
I actually looked around to see how difficult it is to just create desktop and start menu icons from the `setup.py` script. It is very simple, so I will add the `setup.py win-install` option for the next release. With this, you can just download the source file, and run this command to add the launcher icons.

This assumes you have Python installed of course. Dependencies can anyway be installed with `setup.py pip`. I'll update the documentation too. I may still add a `setup.bat` or `install.bat` file for users who don't want to use command line, but it will just be a wrapper for `setup.py`.

**Comment by alexisargyris** [comment]
Everything worked very well. No problem at all. The new tab "Novel" is very useful, in my opinion. Thanks!

**Comment by vkbo** [comment]
Great! I will do a release 1.0.4 this week first, then I think 1.1 will be ready within a couple of weeks. I don't expect any major issues with it, I just want to hold off in case I want to tweak some functionality. So I basically need to find some time to do some actual writing so I can test it properly.

**Comment by alexisargyris** [comment]
I'll wait. Writing comes first.

**Comment by vkbo** [comment]
As described in #640, I will no longer provide Windows installers. As mentioned, Windows users will have to download a zip file prepared for Windows, extract it, and if they want launch icons, run the included `setup_windows.bat`. Otherwise, novelWriter can be launched by double-clicking the `novelWriter.pyw` file.

This assumes Python is already installed. The setup script will run the needed `pip` commands. I've rewritten the [novelwriter.io](https://novelwriter.io/) website as well, and added better sections per OS.

I plan to release version 1.1 tomorrow, if I don't find any more issues.

With that, I'm closing this issue. :)
