### ISSUE TITLE
handling of misformed tags

### ISSUE THREAD

**Issue by jyhelle** [vkbo/novelWriter#688]
I mis-entered a tag (did it manually and of course made a mistake : @tme: instead of @time: )

![erreur de tag](https://user-images.githubusercontent.com/47108022/108894596-c31eda00-7612-11eb-90f5-21bad25fe3a6.png)

The tag remained black, which should have warned me, but since it was alone on the page I didn't care, but when later I asked nW to update the project overview ... BANG ! It tried to explain me my error in nWish language :

===========
Environment:
novelWriter Version: 1.3a0
Host OS: linux (5.10.15-1-MANJARO)
Python: 3.9.1 (0x30901f0)
Qt: 5.15.2, PyQt: 5.15.2

KeyError:
'@tme'

Traceback:
  File "/home/jld/trad-nw/novelWriter-dev/nw/guimain.py", line 1581, in _mainTabChanged
    self.projView.refreshTree()

  File "/home/jld/trad-nw/novelWriter-dev/nw/gui/outline.py", line 187, in refreshTree
    self._populateTree()

  File "/home/jld/trad-nw/novelWriter-dev/nw/gui/outline.py", line 381, in _populateTree
    tItem = self._createTreeItem(tHandle, sTitle, novIdx)

  File "/home/jld/trad-nw/novelWriter-dev/nw/gui/outline.py", line 454, in _createTreeItem
    theRefs = self.theIndex.getReferences(tHandle, sTitle)

  File "/home/jld/trad-nw/novelWriter-dev/nw/core/index.py", line 709, in getReferences
    theRefs[aTag[1]].append(aTag[2])

==========

I think mis-formed tags should be rejected with a warning message and quietly ignored

**Comment by vkbo** [comment]
Thanks!

As you mentioned in https://github.com/vkbo/novelWriter/issues/93#issuecomment-784452154, this is the developement version, but the issue exists at least partially in other versions.

Interestingly, I cannot get it to crash, because immediately before the line where it crashes for you, there is a check that the key actually exists in the reference array. The faulty entry is removed. I'm wondering if you have an older version of the code because I added this recently when I added the new `@focus` keyword.

In my version, where there is no crash, I have the following four lines leading up to line 709:
```python
for refTitle in self._refIndex[tHandle]:
    for aTag in self._refIndex[tHandle][refTitle].get("tags", []):
        if len(aTag) == 3 and (sTitle is None or sTitle == refTitle):
            if aTag[1] in theRefs: # Future-compatible. Check can be removed in 1.2.
                theRefs[aTag[1]].append(aTag[2])
```
Can you check if you have the second last line at your end?

In any case, this is indeed a bug because the faulty tag is written to the index file and then the index file is deemed invalid the next time it's loaded. This is annoying. I will make sure only valid keywords are saved to the index. This should avoid the issue propagating to the lookup function where it crashes in your version.

**Comment by jyhelle** [comment]
You're right, I am missing the line
if aTag[1] in theRefs: # Future-compatible. Check can be removed in 1.2.
I downloaded the code end of last week, probably Thursday, I will download it anew tonight
Interestingly, when trying to document the bug I started the system-wide version on my system, so probably 1.1 or 1.1.1 and on this one, after the crash I could no longer reopen the failing project... nW crashed immediately after choosing that project to load.
--
Envoyé de l'application Mail.ru pour Android

**Comment by vkbo** [comment]
Probably 1.1 because the line you were missing I added in 1.1.1 to fix a similar issue. It was added 3 days ago in https://github.com/vkbo/novelWriter/commit/464c7dae0a7d4a1b1346d909338aeac83d282f93.

In 1.2 I'm adding the `@focus` keyword, and I noticed the 1.1 version would crash when loading the index from my sample project written with 1.2 in 1.1. This is why the additional line was added to all, and it is accidental that it prevented a crash for this bug.

Even if it doesn't cause a crash in the recent code, it still writes an invalid index file, so it causes some trouble when loading it also in 1.2 beta and in `dev`.

I identified the missing check, and I'm fixing it in #689.

**Comment by vkbo** [comment]
For your system wide version, 1.1.1 should handle it fine due to the above added line. The invalid index entry is loaded, but the entry should just be ignored by novelWriter. I could not make 1.1.1 crash on this at my end.

I will add the fix for 1.1.2 and 1.2 RC 1. I'm not sure I will even need to release 1.1.2, as 1.2 is almost ready.

**Comment by vkbo** [comment]
Added more extensive testing of the formatting of these lines in #690, for the 1.2 RC 1 release this weekend.

The test now scans these two pieces of text, which should now pass fine with no error. Only the valid entries are accepted.
```
# Jane Smith
@tag: Jane
@tag:
@:
```
and
```
# Hello World!
@pov: Jane
@invalid: John
```

I think that should cover it?

**Comment by jyhelle** [comment]
I think so ! 
In the meantime I opened #691, just to keep you busy ;-)
Jan
--
Envoyé de l'application Mail.ru pour Android mardi, 23 février 2021, 10:34PM +01:00 de Veronica Berglyd Olsen  notifications@github.com :

**Comment by vkbo** [comment]
I may save something for tomorrow too!
