### ISSUE TITLE
Initial entry in the project Auto-replace table

### ISSUE THREAD

**Issue by jyhelle** [vkbo/novelWriter#691]
(v1.3a)
To enter the first pair in the project auto-replace table (Project->Project settings->Auto-replace tab), the cursor cannot be placed in the entry fields. 
One has to enter first an empty pair, then modify it. (well, at least that's the only method I found)
Since we always [try to] discourage users to enter empty fields, it would be better to do as in the (Tools->Project words list) and type the first entry directly...

**Comment by vkbo** [comment]
Yes, this is correct. It is not very intuitive, but this is very old code from all the way back in the beginning in 2018, and some of it is a bit clunky because I was still learning to work with Qt. I can't remember now if there is a technical reason it was done that way. This is not a bug, but I agree it should be changed. I'm in the process of cleaning up that dialog, and I'll take this into consideration as well.

**Comment by vkbo** [comment]
I looked into the code here, and decided to keep the current functionality. These lists are different than the word list because they are maps between values that need to be controlled more strictly, and each entry contains additional data that isn't displayed in the list. We are editing data that is actively used in the project, and extra care needs to be taken to ensure references aren't broken in the editing process. Newly added entries are handled quite differently than edited items, so forcing the use of the add button makes it a lot easier to handle in the code because there is only one pathway to add a new entry, and the form is a pure edit form that always corresponds to an existing entry.

I have instead reorganised the three relevant tabs in Project Settings to make the add/remove buttons stand out more and added a "Select item to edit" text in the text boxes to let the user know they need to select something before editing the entry. This should make the forms more intuitive I hope.

**Comment by jyhelle** [comment]
I understand the rationale behind the edition path. That should be no problem as long as it is described in the doc (although we know users don't read it in much details)
I'll have a look and translate the button text also.

17 mars 2021 12:43:55 Veronica Berglyd Olsen ***@***.***>:

**Comment by vkbo** [comment]
Thanks!

I've moved the 1.3 alpha code to the `testing` branch now as I want to make a beta release ob 1.3 very soon. The `dev` branch has been bumped to 1.4 alpha. At the moment there is no difference, but they may diverge soon, so it's probably best to get the latest translation files from `testing`.

I suppose it will take a few iterations before we figure out the optimal time to update translations. I think it is probably ideal to do it when the code reaches the `testing` branch as no major changes will be made at that point.

**Comment by jyhelle** [comment]
Well, I grabbed the dev code to make the translations, and it says 1.4a0, but as I understand your message above the .ts files are still the same ? Or should I grab rather a testing copy and transfer my trads ?

**Comment by vkbo** [comment]
If you grabbed them today, they are the same.

**Comment by jyhelle** [comment]
OK, I send the translations via email in a few minutes
