### ISSUE TITLE
“Empty Trash” menu option doesn’t empty the trash folder

### ISSUE THREAD

**Issue by gorhu** [vkbo/novelWriter#701]
Hi! Before anything else, thank you for this amazing software.

It isn’t a critical problem but as I noticed on Ubuntu 20.04 (Python 3.8) and Solus 4.2 (Python 3.7), empty trash menu option doesn’t empty the trash folder. Confirmation dialog disappears after I click OK without deleting anything. There isn’t any error/warning I can see even with —verbose and —debug. Deleting items one by one works.

I tried with 1.1.1 and 1.2 rc1.

**Comment by vkbo** [comment]
You are right. That is a recent bug. The code handling this has recently been enhanced, but clearly something is blocking the deletion. I'll look in to that and make sure it is better covered by the test suite as well. I'll fix it for the 1.2 release this weekend.

**Comment by vkbo** [comment]
Problem identified. This is caused by the fix to #629 which adds a check that the tree has focus before performing a deletion. Due to the dialog box asking for permission to delete the files, the tree no longer has focus when the actual deletions are bing performed.

Since the tests run without a GUI, the focus check is forced so tests don't trigger this bug.
