### ISSUE TITLE
CRITICAL  AttributeError: 'QTranslator' object has no attribute 'filePath'

### ISSUE THREAD

**Issue by koraxnyx** [vkbo/novelWriter#773]
Hi, after upgrading novelWriter, it does not open anymore (it worked fine until now)

I'm using novelWriter 1.3 on Debian 10, the error says:

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-isaac'
CRITICAL  AttributeError: 'QTranslator' object has no attribute 'filePath'
  File "./novelWriter", line 10, in <module>
    sys.exit(main())
  File "/home/isaac/.local/lib/python3.7/site-packages/nw/__init__.py", line 284, in main
    CONFIG.initLocalisation(nwApp)
  File "/home/isaac/.local/lib/python3.7/site-packages/nw/config.py", line 394, in initLocalisation
    logger.debug("Loaded: %s" % qTrans.filePath())
WARNING   Could not find main GUI window so cannot open error dialog
`
Any idea would be much appreciated.

Thanks and all the best.

**Comment by vkbo** [comment]
Confirmed. It seems that function was added in Qt 5.15: https://doc.qt.io/qt-5/qtranslator.html#filePath

It seems [Debian 10](https://tracker.debian.org/pkg/qtbase-opensource-src) is running 5.11.3, which is why you see the error. The tests I run use the pip packaged version which I think is on 5.15.4 now. I'm on Debian 11 testing on my PCs, so I got 5.15.2 as well, which is why I haven't run into this myself.

I usually add a version check around calls to the Qt library that are newer that 5.3, but it seems I missed this one. There are thousands of calls to the library, so it happens occasionally. The Qt documentation isn't always accurate on this either.

In any case, I will make a fix ASAP.

In the meantime, if you are confortable with installing packages from pip, the simple solution is to install the pip version. Alternatively, you can simply delete the offending code line as it has no effect on the app itself as it's merely a debug statement: https://github.com/vkbo/novelWriter/blob/35458a7e37c1687987e27e4fb65f6c2d3f9e3322/nw/config.py#L394

**Comment by vkbo** [comment]
New release is up. I tested the fix earlier on Ubuntu 18.04, so it should do the trick.

**Comment by koraxnyx** [comment]
I can confirm that the new release works, thank you very much, you are awesome.

Deleting the offending line worked too.

Thank you very much again.
