### ISSUE TITLE
novelWriter not opening anymore

### ISSUE THREAD

**Issue by AKPhoto** [vkbo/novelWriter#778]
I was happily writing my novel one day and the next morning when I clicked on the shortcut it gave me an error to the effect that the project does not exist and now after trying to reinstall the program numerous times I have nothing... I can see the project files but I can't continue with my novel... I was very happy with novelWriter, now... Not so much. I have not written in weeks. I am an old vb programmer so not totally clueless I tried deleting the folder and reinstalling. I am now thinking of just forgetting about my lost novel and starting a new one using another software as I cannot find my previous bug report and/or answer to it.

**Comment by vkbo** [comment]
I have both received and responded to your previous posts, but it seems you are not getting my responses and instead make a new one each time.

Since these are not actual bugs, as far as I can tell, I would prefer to not have such communication in the Issue tracker. I moved your first post to the Discussions section, which is available here: https://github.com/vkbo/novelWriter/discussions You will find your first post and my response under [novelwriter disappeared from my system](https://github.com/vkbo/novelWriter/discussions/771). This is where I can provide a bit of support, but I'm doing this in my spare time, so there's a limit to how much time I have.

As I've explained, novelWriter doesn't delete your text files, so unless you've accidentally deleted them yourself, your novel is still on your computer where you put it. I don't know why you cannot start novelWriter any more. I assume it is caused by having multiple launchers installed, with one taking precedence. novelWriter uses the standard XDG tools provided by your system to install icons and launcers, and depending on whether you used the sudo command when you installed it, you can end up in different locations on your system. The best solution is to find and delete them all.

I suggest you check if you have one or more of the following files:
* `/usr/share/applications/novelwriter.desktop`
* `~/Desktop/novelwriter.desktop`
* `~/.local/share/applications/novelwriter.desktop`

Delete them all, and run the command again in a terminal window from the folder where you have the copy of novelWriter you want to run:
```
./setup.py xdg-install
```
I suggest you do not use the `sudo` command for this.

You can always launch novelWriter directly from the folder where you extracted it as well. All that is needed is to run:
```
./novelWriter.py
```

If there is a problem with launching novelWriter itself, you should get some error messages in the terminal window. You can increase the detail level of the output by running:
```
./novelWriter.py --verbose
```

**Comment by vkbo** [comment]
I have both received and responded to your previous posts, but it seems you are not getting my responses and instead make a new thread each time. Please try to respond in the existing threads. The issue tracker is the wrong place for help requests, but I'll leave it here for now anyway. I moved your first post to the Discussions section, which is available here: https://github.com/vkbo/novelWriter/discussions You will find your first post and my response under [novelwriter disappeared from my system](https://github.com/vkbo/novelWriter/discussions/771). This is where I can provide a bit of support, but I'm doing this in my spare time, so there's a limit to how much time I have.

I'm not sure what you mean when you say "the project does not exist". As I've explained, novelWriter doesn't delete your text files, so unless you've accidentally deleted them yourself, your novel is still on your computer where you put it. You seem to say this is the case. I don't know why you cannot start novelWriter. From your description of what is happening it is difficult to understand what exactly the problem is.

Previously, you've mentioned that novelWriter doesn't start. If this is still the case, I assume it is caused by having multiple launchers installed, with one taking precedence. novelWriter uses the standard XDG tools provided by your system to install icons and launchers, and depending on whether you used the sudo command when you installed it, you can end up in different locations on your system. The best solution is to find and delete them all.

I suggest you check if you have one or more of the following files:
* `/usr/share/applications/novelwriter.desktop`
* `~/Desktop/novelwriter.desktop`
* `~/.local/share/applications/novelwriter.desktop`

Delete them all, and run the `./setup.py xdg-install` command again in a terminal window from the folder where you have the copy of novelWriter you want to run.

You can always launch novelWriter directly from the folder where you extracted it as well by running `./novelWriter.py` directly from the same location.

If there is a problem with launching novelWriter itself, you should get some error messages in the terminal window. You can increase the detail level of the output by running: `./novelWriter.py --verbose`

Again, I still don't understand from your explanations what the problem is, so it is difficult to suggest a solution. When you use the bug report feature, there is a list of things the bug report should contain so I can understand what is going on. It would be significantly easier for me to help if you followed that description.

**Comment by vkbo** [comment]
Reading your post again, it occurred to me you may be trying to start novelWriter by double-clicking an icon on the desktop. Is that correct?

The installer no longer creates a desktop icon, so if you do have such an icon, it will no longer work. You should delete it. There was never meant to be such an icon in the first place. It was caused by a wrong command in the installer. The correct way to start novelWriter on Ubuntu is to press the `Win` key and start typing novelWriter. The proper icon should show up then. You can right-click it and add it to your favourites of you want.

**Comment by vkbo** [comment]
Since this is not technically a bug, as far as I can see, and there's been no response, I will close this now.

I made some modifications in the installer for version 1.3.2 that will ensure it better cleans up remnants from older installations. This may help the situation you're describing although I still don't get what exactly the problem is.
