### ISSUE TITLE
Both launchpad repos are for 1.5 rc1

### ISSUE THREAD

**Issue by boudiccas** [vkbo/novelWriter#895]
I've been trying to add the repo to my debian 11 box, and eventually I've done so, but repo 'https://launchpad.net/~vkbo/+archive/ubuntu/novelwriter' points to ' novelwriter 	1.5rc1-ubuntu20.04.0 	Veronica Berglyd Olsen (2021-09-10) ', and repo 'https://launchpad.net/-vkbo/+archive/ubuntu/novelwriter-pre' shows ' novelwriter 	1.5rc1+SNAPSHOT-20210911-140622-ubuntu20.04.0 	Veronica Berglyd Olsen (2021-09-11) '

Consequently I've just installed '1.5rc1~ubuntu20.04.0' when I was looking for 1.4.2!

**Comment by vkbo** [comment]
That is correct. The debian packages and launchpad repos have been added from 1.5 RC 1 as is mentioned in the main README. Release 1.4.2 will not be added as that would mean backporting all the build scripts. The organisation of the source files has been changed a great deal as well to make it easier to build debian files, so the backport is not trivial.

The release candidate should be fine. It is only waiting for the updated translation files for the full release. The full 1.5 release will be added on Sunday 19th, and the code base is otherwise ready. I do not make any functional changes to novelWriter between RC and full release. But I do not intend to push RCs to the main repo in the future.

If you prefer to run on 1.4.2 until the main release, I'd just uninstall it with the apt command for now and then install again in a week.

**Comment by vkbo** [comment]
I could perhaps delete the 1.5rc1 releases from the main launchpad repo in the meantime. I'm done testing it, so it should work when the new release is up.

By the way, did you test the recipe from the documentation for setting up the repo and key on Debian? I'm curious if it worked as intended for others too. I too use Debian 11, and made the recipe from my own tinkering. It's in the "latest" version of the docs, not the "stable" which is for 1.4.2.  See https://novelwriter.readthedocs.io/en/latest/setup_linux.html

**Comment by vkbo** [comment]
novelWriter 1.5 has now been uploaded to the main PPA. Only full releases will be uploaded to that PPA from now on, so I believe this issue is resolved.
