### ISSUE TITLE
Solarized Light theme: disabled elements are not greyed out in the menus

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#918]
I don't know if theme bugs should be reported here, but I found this simple one.

When using the Solarized Light main GUI theme, disabled menu elements seem to not be shown as greyed out.

**How to reproduce:**

1. Enable Solarized Light main GUI theme in Preferences > General.
2. Load a project with several root folders, such as the sample project.
3. Go to menu Project > Create Root Folder.
4. All elements inside will show with regular color. But hovering over disabled elements will not fill their background, which is working as expected.

This is under Linux Mint 20.2 Cinnamon.

![Screenshot](https://user-images.githubusercontent.com/16073344/139511240-bbca79d7-94ac-425d-9ebb-0b5afcbc0999.png)

**Comment by vkbo** [comment]
This is a contributed theme and I've never used it myself. The theme files only contain colour settings, which are loaded into the standard Qt Palette. No other customisation is made. I'm not sure how the Qt library decides how to indicated disabled state on menu items based on theme.

Perhaps it can be fixed with style sheets.
