### ISSUE TITLE
~/Desktop is not recognized on macOS

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#92]
novelWriter works just fine on macOS Catalina. But when exporting to LaTeX I attempted to place the `.tex` file on the Desktop by specifying:

```
~/Desktop/Dick_and_Jane.tex
```

But I get an error popup:

```
Failed to open file.
[Errno 2] No such file or directory: '~/Desktop/Dick_and_Jane.tex'
```

The workaround is trivial of course. Specify the full path `Users/johnb/Desktop/Dick_and_Jane.tex` for good results.

I had originally prepared Dick_and_Jane on my Linux box where I specified `/home/johnb/Desktop/Dick_and_Jane` but that did not work on macOS. I had hoped to use the `~` symbol to make it cross-platform. Certainly in the shell macOS understands the tilde character since macOS is a Unix system.

Hopefully there is a cross-platform way in Python3 to express the home directory as `~` but if not it's just a minor inconvenience.

**Comment by vkbo** [comment]
Ah, thanks a lot for testing on MacOS. That is very useful.

In novelWriter I use the Qt file dialogs instead of native dialogs, so this may be a limitation of Qt itself. Unless of course you typed it manually, in which case Python may not automatically expand it. That is a bit strange, because I use `os.path` for all paths, and the `path` module should support `~` as I use it when setting up the config to find the user directory by calling `os.path.expanduser("~")`.

It seems that the expanduser call needs to applied to the path, which I can certainly try to add on the few places where I take file/folder paths like this.

https://docs.python.org/2/library/os.path.html#os.path.expanduser

**Comment by vkbo** [comment]
Testing this, it seems to be an easy feature to add.

```python
In [10]: import os

In [11]: os.path.expanduser("~")
Out[11]: '/home/user'

In [12]: os.path.expanduser("~/Stuff")
Out[12]: '/home/user/Stuff'

In [13]: os.path.expanduser(os.path.join("~","Stuff"))
Out[13]: '/home/user/Stuff'
```

**Comment by vkbo** [comment]
Functionality added in PR #94.
