### ISSUE TITLE
Overall GUI text improvement suggestions

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#923]
Currently there are several strings in the GUI that may need fixes. Here's a list I made while translating nW, grouped by GUI context. Some are suggestions related to UX:

- GuiDocViewFooter
  - `Activate to freeze the content of the references panel when changing document`
    - Maybe this tooltip can be worded better. Right now its meaning is fairly obscure. See below.
  - `Sticky`
    - From a first-five-minutes experience, `Sticky` did a bad job at evidencing what this control specifically does. Does it _sticky_ the window, the open document? How does it relate to its sibling control (`References`)?

- GuiDocViewFooter
  - `Reload the document`
    - Nitpick: `Reload this document` instead, in relation to the document the control is placed on.
  - `Close the document`
    -  Nitpick: `Close this document` instead. Same as above.

- GuiMain
  - `Note: If the program or the computer` ...
    - Suggestion: Substitute the last sentence with `However, it is not recommended if the project is opened in another instance of novelWriter, where overriding the lock may corrupt the proyect.`

- GuiMainMenu
  - `Change the block format to` ... (several strings)
    - `text block` instead of just `block`, avoiding the implicit meaning.

- GuiOutlineDetails
  - `Title Details`
    - Bad description. Perhaps `Document Summary`? 

- GuiPreferencesDocuments
  - `Text width is defined by the margins only.`
    - Suggestion: `only by the editor/viewer margins.`

- GuiPreferencesEditor
  - `Also improves trypewriter scrolling for short documents.`
    - Typo in `trypewriter`

- NWProject
  - `The file format of your project is about to be updated. If you proceed, this project can no longer be opened by an older version of novelWriter. Continue?`
    - Suggestion: `If you proceed, older versions of novelWriter will no longer be able to open this project.`
  - `Cannot backup project because no backup path is set. Please set a valid backup location in Tools > Preferences.`
    - Suggestion: `Tools > Preferences > Projects tab`
  - `Cannot backup project because the backup path does not exist. Please set a valid backup location in Tools > Preferences.`
    - Suggestion: `Tools > Preferences > Projects tab`
  - `Cannot backup project because the backup path is within the project folder to be backed up. Please choose a different backup path in Tools > Preferences.`
    - Suggestion: `Tools > Preferences > Projects tab`
  - `Choose how to pre-fill the project. Either with a minimal set of starter items, an example project explaining and showing many of the features, or show further custom options on the next page.`
    - Suggestion: `many of the available features`

**Comment by vkbo** [comment]
I'll fix the typo and look through your suggestions. I will not specify the tab for the last bulk of suggestions because that means the text will change if I move the settings to another tab, which I occasionally do when the pages become too long. I don't want to trigger the need to update all translations too often.

**Comment by vkbo** [comment]
Ok, so I've gone through you suggestions. I've adapted and implemented a bunch, skipped a few, and added two new enhancement issues triggered by your suggestions.

### Summary

> GuiDocViewFooter: "Activate to freeze the content of the references panel when changing document" Maybe this tooltip can be worded better. Right now its meaning is fairly obscure. See below.

The reference panel feature needs improvement in general and should be redesigned. Split into a separate issue #925.

> GuiDocViewFooter: "Sticky" From a first-five-minutes experience, "Sticky" did a bad job at evidencing what this control specifically does. Does it _sticky_ the window, the open document? How does it relate to its sibling control ("References")?

The reference panel feature needs improvement. See above.

> GuiMain: "Note: If the program or the computer" ... Suggestion: Substitute the last sentence with "However, it is not recommended if the project is opened in another instance of novelWriter, where overriding the lock may corrupt the proyect."

Changed to "Note: If the program or the computer previously crashed, the lock can safely be overridden. However, overriding it is not recommended if the project is open in another instance of novelWriter. Doing so may corrupt the project."

> GuiMainMenu: "Change the block format to" ... (several strings) "text block" instead of just "block", avoiding the implicit meaning.

Rewritten the status bar text for most of these entries. They will all have to be re-translated for all GUI languages.

> GuiOutlineDetails: `Title Details` > Bad description. Perhaps `Document Summary`?

"Document Summary" would be the wrong description since it isn't the meta data of the document being displayed, but the meta data of the title.

> GuiPreferencesDocuments: "Text width is defined by the margins only." Suggestion: "only by the editor/viewer margins."

This setting will be removed, so skipping this for now. See #924.

> GuiPreferencesEditor: Typo in "trypewriter"

Fixed in source and existing TS files.

> NWProject: "The file format of your project is about to be updated. If you proceed, this project can no longer be opened by an older version of novelWriter. Continue?" Suggestion: "If you proceed, older versions of novelWriter will no longer be able to open this project."

Proposed text added.

> NWProject: "Cannot backup project because no backup path is set. Please set a valid backup location in Tools > Preferences." Suggestion: "Tools > Preferences > Projects tab"

Renamed to just "Preferences" instead, avoiding the need to describe menu and dialog layout. Note that on macOS, Preferences is moved by the OS to the application menu, so this isn't even correct on macOS.

> NWProject: "Cannot backup project because the backup path does not exist. Please set a valid backup location in Tools > Preferences." Suggestion: "Tools > Preferences > Projects tab"

Renamed to just "Preferences" instead, see above.

> NWProject: "Cannot backup project because the backup path is within the project folder to be backed up. Please choose a different backup path in Tools > Preferences." Suggestion: "Tools > Preferences > Projects tab"

Renamed to just "Preferences" instead, see above.

> NWProject: "Choose how to pre-fill the project. Either with a minimal set of starter items, an example project explaining and showing many of the features, or show further custom options on the next page." Suggestion: "many of the available features"

Too small a correction to trigger a need to re-translate. This sample project feature will in any case be removed when #841 is implemented, and replaced with a template feature that includes multiple sample projects.
