### ISSUE TITLE
Unhandled error while exiting a project

### ISSUE THREAD

**Issue by vanhamiel** [vkbo/novelWriter#954]
This happens when I close my new project.
Installed novelWriter yesterday.

Environment:
novelWriter Version: 1.5.4
Host OS: win32 (10.0.22000)
Python: 3.10.0 (0x30a00f0)
Qt: 5.15.2, PyQt: 5.15.6

ValueError:
Paths don't have the same drive

Traceback:
  File "E:\Download\novelWriter-1.5.4-minimal-win\novelwriter\guimain.py", line 1505, in closeEvent
    if self.closeMain():

  File "E:\Download\novelWriter-1.5.4-minimal-win\novelwriter\guimain.py", line 1209, in closeMain
    self.closeProject(True)

  File "E:\Download\novelWriter-1.5.4-minimal-win\novelwriter\guimain.py", line 434, in closeProject
    self.theProject.zipIt(False)

  File "E:\Download\novelWriter-1.5.4-minimal-win\novelwriter\core\project.py", line 820, in zipIt
    if os.path.commonpath([self.projPath, baseDir]) == self.projPath:

  File "C:\Users\chime\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 778, in commonpath
    raise ValueError("Paths don't have the same drive")

**Comment by vkbo** [comment]
Ah, that error again. It's an annoying Windows issue I've encountered before. On Unix-like systems all paths generally have a common root path, but Windows have their drive letters at root. I thought I'd fixed those last time such a bug occurred. It is a Windows-only error.

It is caused by your backup location being on a different drive than where you store your projects. I will make a fix, but in the meantime you can get past the issue by keeping the backup location on the same drive. Alternatively, if you don't mind editing the code, you can comment out the whole if-check in novelwriter\core\project.py, line 820 to 836. All it does is check that you are not writing your backup inside the same folder where the project is stored. That would cause an infinitely growing zip file (bug #240).

I'll make a fix tonight, and do another release. It's typical that I get a bug report the day after a patch release, and rarely anything in the weeks in-between! (Not your fault of course)

**Comment by vanhamiel** [comment]
First I'd like to thank you for your fast response. And for all the effort you put on that marvelous tool (found it too late but it's really awesome).
I will not go through the code but I can wait for the fix, indeed I only feared it could cause issues with saves but if it's not the case I have no hurry.
Thanks again.

**Comment by vkbo** [comment]
It only affects the backup, which runs in the background when you close the project, if you have it enabled.

I'm working on the fix now. Should be up in a bit.
